Repository edgelesssys/constellation, pull requests merged in 2022-12, with the labels that each got.

#792 Fix e2e test networking issue
  .github/actions/constellation_create/action.yml
Labels: no-changelog

#791 Enhance release checklist with lessons from release v2.3
  .github/docs/release.md
Labels: no-changelog

#793 Release action: Do not fail if "latest" is not set
  .github/workflows/on-release.yml
Labels: no-changelog

#803 update slsa-verifier
  .github/workflows/release-cli.yml
Labels: dependencies

#785 ci: automated changelog generation
  .github/pull_request_template.md
  .github/release.yml
  CHANGELOG.md
Labels: no-changelog

#811 deps: disable semantic commit message for renovate
  renovate.json
Labels: no-changelog

#816 ci: enable manual e2e runs on any git ref
  .github/actions/find_latest_image/action.yaml
  .github/workflows/e2e-test-manual.yml
Labels: no-changelog

#818 Only upgrade helm releases if versions changed
  cli/internal/cloudcmd/upgrade.go
  cli/internal/helm/client.go
  cli/internal/helm/client_test.go
Labels: no-changelog

#821 image: set runtime-endpoint in crictl config
  bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
  image/mkosi.skeleton/etc/crictl.yaml
Labels: no-changelog

#822 versionsapi: fix cache invalidation
  hack/add-version/main.go
  internal/versionsapi/versionsapi.go
Labels: no-changelog

#823 ci: fix workflows with tokens running on forks
  .github/workflows/test-go-generate.yml
  .github/workflows/test-tidy.yml
Labels: no-changelog

#825 gitignore: add image/prebuilt/*
  .gitignore
Labels: no-changelog

#807 join: make Azure instance names k8s compliant
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  joinservice/internal/kubernetes/kubernetes.go
  joinservice/internal/kubernetes/kubernetes_test.go
Labels: bug-fix

#826 gcp: unofficial support for internal LBs
  hack/terraform/gcp/internal-loadbalancer/.terraform.lock.hcl
  hack/terraform/gcp/internal-loadbalancer/main.tf
  hack/terraform/gcp/internal-loadbalancer/modules/instance_group/main.tf
  hack/terraform/gcp/internal-loadbalancer/modules/instance_group/outputs.tf
  hack/terraform/gcp/internal-loadbalancer/modules/instance_group/variables.tf
  hack/terraform/gcp/internal-loadbalancer/modules/internal_loadbalancer/main.tf
  hack/terraform/gcp/internal-loadbalancer/modules/internal_loadbalancer/variables.tf
  hack/terraform/gcp/internal-loadbalancer/outputs.tf
  hack/terraform/gcp/internal-loadbalancer/variables.tf
  internal/cloud/gcp/cloud.go
  internal/cloud/gcp/cloud_test.go
  internal/cloud/gcp/interface.go
  internal/cloud/gcp/wrappers.go
Labels: no-changelog

#838 fix e2e lb test on aws: call hostname instead of ip
  e2e/internal/lb/lb_test.go
Labels: bug-fix, no-changelog

#837 deps: update sonobuoy to v0.56.14
  .github/actions/e2e_sonobuoy/action.yml
Labels: dependencies

#833 join: deprecate components migration fallback
  bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
  bootstrapper/internal/kubernetes/k8sutil.go
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/QEMU/constellation-services/charts/join-service/templates/clusterrole.yaml
  joinservice/internal/kubernetes/kubernetes.go
  joinservice/internal/server/server.go
  joinservice/internal/server/server_test.go
Labels: no-changelog

#827 image: add upgrade-agent
  .github/actions/build_upgrade_agent/action.yml
  .github/workflows/build-os-image.yml
  cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/templates/gcp-daemonset.yaml
  cli/internal/helm/charts/edgeless/operators/charts/constellation-operator/templates/deployment.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/ccm/templates/gcp-daemonset.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  image/Makefile
  image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset
  image/mkosi.skeleton/usr/lib/systemd/system/constellation-upgrade-agent.service
  operators/constellation-node-operator/config/manager/manager.yaml
Labels: no-changelog
