Repository edgelesssys/constellation, pull requests merged in 2023-09, with the labels that each got.

#2295 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2291 cli: disable smt on AWS via cpu_options
  cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
  image/mkosi.conf.d/mkosi.conf
Labels: no changelog

#2296 ci: fix incorrect signing key for sbom signature and wrong public key in release artifacts
  .github/workflows/release-cli.yml
Labels: bug fix

#2299 cli: correctly trim white spaces for certificates in `verify`
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
Labels: bug fix

#2300 ci: add hint about cleaning up lingering resources on failure
  .github/failure_project_template.md
Labels: no changelog

#2268 image: update to Linux 6.1.46
  image/Makefile
  image/mkosi.conf.d/mkosi.conf
Labels: no changelog

#2303 cli: temporarily disable nosmt via VMM
  cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
Labels: no changelog

#2306 docs: switch to native mermaid support
  docs/docusaurus.config.js
  docs/package.json
Labels: documentation, no changelog

#2308 ci: use updated OpenSearch url
  .github/actions/notify_failure/action.yml
Labels: no changelog

#2309 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2307 ci: use virtee project for sev-snp-measure-go
  .github/workflows/aws-snp-launchmeasurement.yml
Labels: no changelog

#2312 csi: let constructor take care of setting up cryptsetup
  csi/cryptmapper/cryptmapper.go
  csi/cryptmapper/cryptmapper_test.go
  csi/test/BUILD.bazel
  csi/test/mount_integration_test.go
Labels: no changelog

#2316 ci: don't automatically create git tag in release pipeline
  .github/workflows/release-cli.yml
  .github/workflows/release.yml
  dev-docs/workflows/release.md
Labels: no changelog

#2311 cli: move CSP logic to cloudcmd
  cli/internal/cloudcmd/iamupgrade.go
  cli/internal/cmd/iamupgradeapply.go
  cli/internal/cmd/upgradeapply.go
Labels: no changelog

#2302 cli: print ordered measurements list during `verify`
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  internal/attestation/aws/snp/validator.go
Labels: no changelog

#2318 deps: bump go version
  .github/actions/versionsapi/Dockerfile
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/build-os-image.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  WORKSPACE.bazel
Labels: dependencies

#2305 cli: save Helm charts to disk before running upgrades
  cli/internal/cmd/init_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/action.go
  cli/internal/helm/chartutil.go
  cli/internal/helm/helm.go
Labels: feature

#2324 ci: remove aspect workflows
  .aspect/workflows/config.yaml
  .github/actionlint.yaml
  .github/workflows/.aspect-workflows-reusable.yaml
  .github/workflows/aspect-workflows-warming.yaml
  .github/workflows/aspect-workflows.yaml
Labels: no changelog

#2310 cli: new flag to skip phases of upgrade
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/kubecmd/kubecmd.go
  cli/internal/kubecmd/kubecmd_test.go
  docs/docs/reference/cli.md
Labels: feature

#2325 remove deprecated `constellation create` flags
  3rdparty/bazel/org_openssl/BUILD.bazel
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/kubecmd/backup.go
  cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
  cli/internal/terraform/variables.go
  dev-docs/miniconstellation/setup-miniconstellation.sh
  internal/api/attestationconfigapi/fetcher.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/migration/migration.go
Labels: breaking change

#2327 docs: add troubleshooting notes for manually managing helm charts
  docs/docs/workflows/troubleshooting.md
  docs/docs/workflows/upgrade.md
Labels: no changelog

#2322 cli: retry helm apply on any error
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/action.go
  cli/internal/helm/retryaction.go
  cli/internal/helm/retryaction_test.go
Labels: bug fix

#2319 cli: check chart versions against target version in users config before upgrading
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/actionfactory.go
  cli/internal/helm/actionfactory_test.go
  cli/internal/helm/helm.go
  cli/internal/helm/helm_test.go
  cli/internal/helm/loader.go
Labels: no changelog

#2320 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2313 doc: `--skip-flag` in the upgrade workflow
  docs/docs/workflows/upgrade.md
Labels: no changelog

#2326 node-operator: fix data race in executor
  operators/constellation-node-operator/internal/executor/executor.go
  operators/constellation-node-operator/internal/executor/executor_test.go
Labels: bug fix

#2329 api: rename references to moved hack/configapi
  .github/actions/e2e_verify/action.yml
  internal/api/attestationconfigapi/cli/main.go
Labels: no changelog

#2261 bazel: never run buildifier in remote execution
  bazel/ci/BUILD.bazel
Labels: no changelog

#2332 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2333 ci: install helm when deploying log collection
  .github/actions/deploy_logcollection/action.yml
Labels: no changelog, needs backport

#2337 ci: bump install helm action
  .github/actions/deploy_logcollection/action.yml
Labels: no changelog

#2334 chore: bump version.txt
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  version.txt
Labels: no changelog

#2339 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2304 ci: add malicious join test
  .github/actions/e2e_malicious_join/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-weekly.yml
  e2e/malicious-join/BUILD.bazel
  e2e/malicious-join/job.yaml
  e2e/malicious-join/job_template.sh.in
  e2e/malicious-join/malicious-join.go
Labels: no changelog

#2287 cli: store kubernetes version as strong type in config
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/helm.go
  cli/internal/helm/helm_test.go
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  cli/internal/kubecmd/kubecmd.go
  cli/internal/kubecmd/kubecmd_test.go
  e2e/internal/upgrade/upgrade_test.go
  internal/config/BUILD.bazel
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/config/migration/BUILD.bazel
  internal/config/migration/migration.go
  internal/config/validation.go
  internal/versions/versions.go
Labels: no changelog

#2341 bazel: mount AWS credentials file into Bazel container
  bazel/container/container.sh
Labels: no changelog

#2349 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2350 ci: fix racy logcollection in `nop` tests
  .github/actions/e2e_test/action.yml
Labels: no changelog

#2269 attestation: use `go-sev-guest` library
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cmd/verify.go
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  internal/attestation/azure/snp/BUILD.bazel
  internal/attestation/azure/snp/errors.go
  internal/attestation/azure/snp/issuer.go
  internal/attestation/azure/snp/issuer_test.go
  internal/attestation/azure/snp/testdata/BUILD.bazel
  internal/attestation/azure/snp/testdata/attestation.bin
  internal/attestation/azure/snp/testdata/certchain.pem
  internal/attestation/azure/snp/testdata/runtimedata.bin
  internal/attestation/azure/snp/testdata/testdata.go
  internal/attestation/azure/snp/testdata/vcek.cert
  internal/attestation/azure/snp/testdata/vcek.pem
  internal/attestation/azure/snp/validator.go
  internal/attestation/azure/snp/validator_test.go
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
Labels: feature

#2348 join: join over lb if available
  bootstrapper/cmd/bootstrapper/run.go
  bootstrapper/internal/joinclient/joinclient.go
  bootstrapper/internal/joinclient/joinclient_test.go
  cli/internal/terraform/terraform/aws/main.tf
  cli/internal/terraform/terraform/azure/main.tf
  cli/internal/terraform/terraform/gcp/main.tf
  disk-mapper/internal/rejoinclient/BUILD.bazel
  disk-mapper/internal/rejoinclient/rejoinclient.go
  disk-mapper/internal/rejoinclient/rejoinclient_test.go
  disk-mapper/internal/setup/interface.go
  internal/cloud/metadata/BUILD.bazel
  internal/cloud/metadata/metadata.go
Labels: no changelog

#2343 cli: fix Azure SEV-SNP latest version logic
  .github/actions/e2e_verify/action.yml
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/iamupgradeapply_test.go
  dev-docs/workflows/attestationconfigapi.md
  go.mod
  hack/go.mod
  hack/go.sum
  internal/api/attestationconfigapi/BUILD.bazel
  internal/api/attestationconfigapi/azure.go
  internal/api/attestationconfigapi/cli/BUILD.bazel
  internal/api/attestationconfigapi/cli/delete.go
  internal/api/attestationconfigapi/cli/e2e/test.sh.in
  internal/api/attestationconfigapi/cli/main.go
  internal/api/attestationconfigapi/client.go
  internal/api/attestationconfigapi/fetcher.go
  internal/api/attestationconfigapi/fetcher_test.go
  internal/api/attestationconfigapi/reporter.go
  internal/api/attestationconfigapi/reporter_test.go
  internal/api/fetcher/BUILD.bazel
  internal/api/fetcher/fetcher.go
  internal/api/versionsapi/fetcher.go
  internal/api/versionsapi/fetcher_test.go
  internal/config/azure.go
  internal/config/config.go
  internal/config/config_test.go
Labels: no changelog

#2356 ci: fix kubectl version retrieval
  .github/actions/e2e_benchmark/action.yml
Labels: no changelog

#2354 cli: report log collection failure to user
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
Labels: bug fix

#2338 ci: remove verify test for macos during release
  .github/workflows/e2e-test-release.yml
Labels: no changelog, needs backport

#2321 cli: write infrastructure to new state file
  CODEOWNERS
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/cloud.go
  cli/internal/cmd/cloud_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/helm.go
  cli/internal/helm/helm_test.go
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  cli/internal/helm/overrides.go
  cli/internal/state/BUILD.bazel
  cli/internal/state/state.go
  cli/internal/terraform/BUILD.bazel
  cli/internal/terraform/terraform.go
  internal/constants/constants.go
Labels: no changelog

#2323 cli: remove TF ApplyOutput dependency in CLI
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/clusterupgrade.go
  cli/internal/cloudcmd/clusterupgrade_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform_test.go
Labels: no changelog

#2359 cli: remove state on terminate
  cli/internal/cmd/terminate.go
  cli/internal/cmd/terminate_test.go
Labels: no changelog

#2361 ci: recreate coverage report on push
  .github/workflows/test-unittest.yml
Labels: no changelog

#2335 ci: don't pull from detached head
  .github/workflows/on-release.yml
Labels: no changelog, needs backport

#2383 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2392 cli: omitempty infrastructure fields
  cli/internal/state/state.go
Labels: no changelog

#2389 deps: update go to 1.21.1
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/build-os-image.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  3rdparty/node-maintenance-operator/go.mod
  3rdparty/node-maintenance-operator/go.sum
  bazel/ci/BUILD.bazel
  bazel/nixos-support/nixos-support.bzl
  bazel/toolchains/go_rules_deps.bzl
  bazel/toolchains/nixpkgs_deps.bzl
  go.mod
  go.sum
  go.work
  hack/go.mod
  hack/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  operators/constellation-node-operator/api/go.mod
  operators/constellation-node-operator/api/go.sum
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
Labels: dependencies

#2393 init: overwrite kubeconfig address
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
Labels: no changelog

#2336 joinservice: cache certificates for Azure SEV-SNP attestation
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/AWS/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/OpenStack/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/QEMU/constellation-services/charts/join-service/templates/clusterrole.yaml
  internal/attestation/azure/snp/BUILD.bazel
  internal/attestation/azure/snp/validator.go
  internal/attestation/azure/snp/validator_test.go
  internal/attestation/choose/choose.go
  internal/attestation/variant/variant.go
  internal/config/attestation.go
  internal/config/attestation_test.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/constants/constants.go
  internal/crypto/crypto.go
  internal/crypto/crypto_test.go
  joinservice/cmd/BUILD.bazel
  joinservice/cmd/main.go
  joinservice/internal/certcache/BUILD.bazel
  joinservice/internal/certcache/amdkds/BUILD.bazel
  joinservice/internal/certcache/amdkds/amdkds.go
  joinservice/internal/certcache/amdkds/amdkds_test.go
  joinservice/internal/certcache/amdkds/testdata/BUILD.bazel
  joinservice/internal/certcache/amdkds/testdata/certchain.pem
  joinservice/internal/certcache/amdkds/testdata/testdata.go
  joinservice/internal/certcache/certcache.go
  joinservice/internal/certcache/certcache_test.go
  joinservice/internal/certcache/testdata/BUILD.bazel
  joinservice/internal/certcache/testdata/ark.pem
  joinservice/internal/certcache/testdata/ask.pem
  joinservice/internal/certcache/testdata/testdata.go
  joinservice/internal/kubernetes/BUILD.bazel
  joinservice/internal/kubernetes/kubernetes.go
  joinservice/internal/server/BUILD.bazel
  joinservice/internal/server/server.go
  joinservice/internal/watcher/validator.go
  joinservice/internal/watcher/validator_test.go
Labels: feature

#2396 deps: update golang.org/x/tools
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
Labels: no changelog
