Repository edgelesssys/constellation, pull requests merged in 2023-04, with the labels that each got.

#1564 internal: semver support for pseudoversions
  internal/semver/semver.go
  internal/semver/semver_test.go
Labels: no changelog

#1573 terraform: add missing permission to AWS iam
  cli/internal/terraform/terraform/iam/aws/main.tf
  docs/docs/getting-started/install.md
Labels: no changelog

#1585 ci: fix grouping of renovate groups
  renovate.json
Labels: no changelog

#1584 ci: do not skip e2e-weekly if trigger is successful
  .github/workflows/e2e-test-release.yml
Labels: no changelog

#1583 ci: purge images on main
  .github/workflows/purge-main.yml
Labels: no changelog

#1553 bootstrapper: fix journald ram usage
  bootstrapper/internal/journald/BUILD.bazel
  bootstrapper/internal/journald/journald.go
  bootstrapper/internal/journald/journald_test.go
Labels: bug fix, no changelog

#1394 cli: show available cli upgrades on upgrade check command
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  hack/clidocgen/BUILD.bazel
  internal/versionsapi/cliinfo.go
Labels: feature

#1346 bootstrapper: make Azure auth method configurable on cluster init
  bootstrapper/internal/kubernetes/BUILD.bazel
  bootstrapper/internal/kubernetes/kubernetes.go
  cli/internal/cmd/init.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/templates/azure-deployment.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/templates/azure-secret.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/values.schema.json
  cli/internal/helm/testdata/Azure/constellation-services/charts/autoscaler/templates/azure-deployment.yaml
  internal/cloud/azure/azure.go
  internal/cloud/azure/azure_test.go
  internal/cloud/azureshared/BUILD.bazel
  internal/cloud/azureshared/appcredentials.go
  internal/cloud/azureshared/appcredentials_test.go
  internal/cloud/azureshared/authmethod_string.go
Labels: no changelog

#1595 ci: do not run most release tests on macOS
  .github/workflows/e2e-test-release.yml
Labels: no changelog

#1575 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1602 license: remove check for Azure.ConfidentialVM
  internal/license/checker_enterprise.go
Labels: bug fix, no changelog, needs backport

#1603 license: remove check for Azure.ConfidentialVM (#1602)
  internal/license/checker_enterprise.go
Labels: backport

#1606 ci: run //:check and //:generate concurrently
  bazel/ci/BUILD.bazel
Labels: no changelog, needs backport

#1604 ci: fix empty image input of verify e2e on release
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-release.yml
Labels: no changelog, needs backport

#1607 ci: run //:check and //:generate concurrently (#1606)
  bazel/ci/BUILD.bazel
Labels: no changelog, backport

#1608 ci: fix empty image input of verify e2e on release (#1604)
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-release.yml
Labels: no changelog, backport

#1611 ci: always release cli on release-cli workflow
  .github/workflows/release-cli.yml
Labels: no changelog, needs backport

#1592 docs: add release v2.7.0
  docs/versioned_docs/version-2.7/_media/SLSA-Badge-full-level3.svg
  docs/versioned_docs/version-2.7/_media/benchmark_api_dpl.png
  docs/versioned_docs/version-2.7/_media/benchmark_api_pods.png
  docs/versioned_docs/version-2.7/_media/benchmark_api_svc.png
  docs/versioned_docs/version-2.7/_media/benchmark_io.png
  docs/versioned_docs/version-2.7/_media/benchmark_net.png
  docs/versioned_docs/version-2.7/_media/concept-constellation.svg
  docs/versioned_docs/version-2.7/_media/concept-managed.svg
  docs/versioned_docs/version-2.7/_media/constellation_oneline.svg
  docs/versioned_docs/version-2.7/_media/example-emojivoto.jpg
  docs/versioned_docs/version-2.7/_media/example-online-boutique.jpg
  docs/versioned_docs/version-2.7/_media/product-overview-dark.png
  docs/versioned_docs/version-2.7/_media/product-overview.png
  docs/versioned_docs/version-2.7/_media/recovery-gcp-serial-console-link.png
  docs/versioned_docs/version-2.7/_media/tcb.svg
  docs/versioned_docs/version-2.7/architecture/attestation.md
  docs/versioned_docs/version-2.7/architecture/encrypted-storage.md
  docs/versioned_docs/version-2.7/architecture/images.md
  docs/versioned_docs/version-2.7/architecture/keys.md
  docs/versioned_docs/version-2.7/architecture/microservices.md
  docs/versioned_docs/version-2.7/architecture/networking.md
  docs/versioned_docs/version-2.7/architecture/orchestration.md
  docs/versioned_docs/version-2.7/architecture/overview.md
  docs/versioned_docs/version-2.7/architecture/versions.md
  docs/versioned_docs/version-2.7/getting-started/examples.md
  docs/versioned_docs/version-2.7/getting-started/examples/emojivoto.md
  docs/versioned_docs/version-2.7/getting-started/examples/horizontal-scaling.md
  docs/versioned_docs/version-2.7/getting-started/examples/online-boutique.md
  docs/versioned_docs/version-2.7/getting-started/first-steps-local.md
  docs/versioned_docs/version-2.7/getting-started/first-steps.md
  docs/versioned_docs/version-2.7/getting-started/install.md
  docs/versioned_docs/version-2.7/intro.md
  docs/versioned_docs/version-2.7/overview/clouds.md
  docs/versioned_docs/version-2.7/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.7/overview/license.md
  docs/versioned_docs/version-2.7/overview/performance.md
  docs/versioned_docs/version-2.7/overview/product.md
  docs/versioned_docs/version-2.7/overview/security-benefits.md
  docs/versioned_docs/version-2.7/reference/cli.md
  docs/versioned_docs/version-2.7/reference/config-migration.md
  docs/versioned_docs/version-2.7/reference/slsa.md
  docs/versioned_docs/version-2.7/reference/terraform.md
  docs/versioned_docs/version-2.7/workflows/cert-manager.md
  docs/versioned_docs/version-2.7/workflows/config.md
  docs/versioned_docs/version-2.7/workflows/create.md
  docs/versioned_docs/version-2.7/workflows/lb.md
  docs/versioned_docs/version-2.7/workflows/recovery.md
  docs/versioned_docs/version-2.7/workflows/sbom.md
  docs/versioned_docs/version-2.7/workflows/scale.md
  docs/versioned_docs/version-2.7/workflows/storage.md
  docs/versioned_docs/version-2.7/workflows/terminate.md
  docs/versioned_docs/version-2.7/workflows/troubleshooting.md
  docs/versioned_docs/version-2.7/workflows/trusted-launch.md
  docs/versioned_docs/version-2.7/workflows/upgrade.md
  docs/versioned_docs/version-2.7/workflows/verify-cli.md
  docs/versioned_docs/version-2.7/workflows/verify-cluster.md
  docs/versioned_sidebars/version-2.7-sidebars.json
  docs/versions.json
Labels: no changelog

#1613 Update release.md
  dev-docs/workflows/release.md
Labels: no changelog

#1561 internal: use config to create attestation validators
  cli/internal/cloudcmd/validators.go
  cli/internal/cloudcmd/validators_test.go
  cli/internal/cmd/create.go
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/values.schema.json
  cli/internal/helm/client.go
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/configmap.yaml
  internal/attestation/aws/BUILD.bazel
  internal/attestation/aws/validator.go
  internal/attestation/azure/snp/BUILD.bazel
  internal/attestation/azure/snp/errors.go
  internal/attestation/azure/snp/validator.go
  internal/attestation/azure/snp/validator_test.go
  internal/attestation/azure/trustedlaunch/BUILD.bazel
  internal/attestation/azure/trustedlaunch/trustedlaunch_test.go
  internal/attestation/azure/trustedlaunch/validator.go
  internal/attestation/choose/BUILD.bazel
  internal/attestation/choose/choose.go
  internal/attestation/choose/choose_test.go
  internal/attestation/gcp/BUILD.bazel
  internal/attestation/gcp/validator.go
  internal/attestation/idkeydigest/BUILD.bazel
  internal/attestation/idkeydigest/enforceidkeydigest_string.go
  internal/attestation/idkeydigest/enforcement_string.go
  internal/attestation/idkeydigest/idkeydigest.go
  internal/attestation/idkeydigest/idkeydigest_test.go
  internal/attestation/qemu/BUILD.bazel
  internal/attestation/qemu/validator.go
  internal/config/BUILD.bazel
  internal/config/attestation.go
  internal/config/attestation_test.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/watcher/BUILD.bazel
  internal/watcher/validator.go
  internal/watcher/validator_test.go
Labels: no changelog

#1555 ci: separate e2e permissions
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_iam_destroy/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#1634 deps: update go to 1.20.3 (#1622)
  .github/actions/build_ko/action.yml
  .github/actions/versionsapi/Dockerfile
  .github/workflows/azure-snp-reporter.yml
  .github/workflows/build-constellation-node-operator.yml
  .github/workflows/build-joinservice-image.yml
  .github/workflows/build-keyservice-image.yml
  .github/workflows/build-operator-manual.yml
  .github/workflows/build-os-image.yml
  .github/workflows/build-qemu-metadata-image.yml
  .github/workflows/build-verification-service.yml
  .github/workflows/build-versionsapi-ci-image.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/on-release.yml
  .github/workflows/release.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-operator-codegen.yml
  .github/workflows/test-tidy.yml
  .github/workflows/test-unittest.yml
  3rdparty/gcp-guest-agent/Dockerfile
  Dockerfile.build
  WORKSPACE.bazel
  hack/qemu-metadata-api/Dockerfile
  joinservice/Dockerfile
  keyservice/Dockerfile
  operators/constellation-node-operator/Dockerfile
  verify/Dockerfile
Labels: no changelog, backport

#1629 bazel: download pseudo-version tool instead of "go build"
  bazel/ci/BUILD.bazel
  hack/pseudo-version/BUILD.bazel
  hack/pseudo-version/pseudo_version_tool_freshness.sh.in
  tools/pseudo_version_darwin_amd64.sha256
  tools/pseudo_version_darwin_arm64.sha256
  tools/pseudo_version_linux_amd64.sha256
  tools/pseudo_version_linux_arm64.sha256
  tools/update-pseudo-version-tool.sh
  tools/workspace_status.sh
Labels: no changelog

#1645 bazel: update pseudo-version tool hashes
  tools/pseudo_version_darwin_amd64.sha256
  tools/pseudo_version_darwin_arm64.sha256
  tools/pseudo_version_linux_amd64.sha256
  tools/pseudo_version_linux_arm64.sha256
Labels: no changelog

#1630 cli: fix misleading error while applying kubernetes-only upgrade
  .github/workflows/e2e-upgrade.yml
  cli/internal/kubernetes/upgrade.go
  cli/internal/kubernetes/upgrade_test.go
  e2e/internal/upgrade/BUILD.bazel
  e2e/internal/upgrade/image.go
  e2e/internal/upgrade/upgrade_test.go
Labels: bug fix, needs backport

#1648 cli: fix misleading error while applying kubernetes-only upgrade (#1630)
  .github/workflows/e2e-upgrade.yml
  cli/internal/kubernetes/upgrade.go
  cli/internal/kubernetes/upgrade_test.go
  e2e/internal/upgrade/BUILD.bazel
  e2e/internal/upgrade/image.go
  e2e/internal/upgrade/upgrade_test.go
Labels: backport

#1656 ci: improve e2e failure reporting and checklist
  .github/actions/notify_failure/action.yml
  .github/failure_project_template.md
Labels: no changelog

#1620 cli: add Terraform log support
  .gitignore
  cli/cmd/root.go
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cloudcmd/iam.go
  cli/internal/cloudcmd/iam_test.go
  cli/internal/cloudcmd/rollback.go
  cli/internal/cloudcmd/rollback_test.go
  cli/internal/cloudcmd/terminate.go
  cli/internal/cloudcmd/terminate_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/cloud.go
  cli/internal/cmd/cloud_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/iamcreate_test.go
  cli/internal/cmd/iamdestroy.go
  cli/internal/cmd/iamdestroy_test.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/terminate.go
  cli/internal/cmd/terminate_test.go
  cli/internal/terraform/BUILD.bazel
  cli/internal/terraform/logging.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform_test.go
  docs/docs/reference/cli.md
  internal/constants/constants.go
Labels: feature

#1658 ci: fix version publishing on release
  .github/workflows/on-release.yml
Labels: bug fix, no changelog, needs backport

#1660 ci: fix version publishing on release (#1658)
  .github/workflows/on-release.yml
Labels: no changelog, backport

#1593 ci: reduce number of steps with continue-on-error
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_destroy/action.yml
  .github/workflows/build-os-image.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#1662 ci: fix naming issues
  .github/actions/e2e_sonobuoy/action.yml
  .github/actions/e2e_test/action.yml
Labels: no changelog

#1655 terraform: use nat gateway on azure
  cli/internal/terraform/terraform/azure/main.tf
  docs/docs/getting-started/install.md
Labels: no changelog

#1670 ci: don't set IAM env for Azure
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#1651 operator: isolate integration tests
  operators/constellation-node-operator/controllers/autoscalingstrategy_controller_env_test.go
  operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go
  operators/constellation-node-operator/controllers/nodeversion_controller_test.go
  operators/constellation-node-operator/controllers/pendingnode_controller_env_test.go
  operators/constellation-node-operator/controllers/scalinggroup_controller_env_test.go
  operators/constellation-node-operator/controllers/scalinggroup_controller_test.go
  operators/constellation-node-operator/controllers/suite_test.go
Labels: no changelog

#1673 ci: fix notification trigger
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#1627 docs: add docs on Terraform debugging
  docs/docs/reference/terraform.md
Labels: documentation, no changelog

#1657 kubernetes: update CSI driver versions to v1.2.0
  cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/Chart.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/values.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/Chart.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/controller.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/storageclass_default.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/values.yaml
  cli/internal/helm/loader_test.go
  cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/controller.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/storageclass_default.yaml
  cli/internal/helm/update-csi-charts.sh
Labels: dependencies

#1676 ci: login to container registry before pushing containers
  .github/actions/e2e_test/action.yml
Labels: no changelog

#1679 ci: add missing permissions for e2e-upgrade job
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#1674 ci: limit prefix length of AWS IAM resources
  cli/internal/cmd/iamcreate.go
Labels: no changelog

#1684 image: upgrade mkosi to support repart
  .github/actions/setup_mkosi/action.yaml
  .github/workflows/build-os-image.yml
  image/Makefile
  image/README.md
  image/mkosi.conf.d/mkosi.aws.conf
  image/mkosi.conf.d/mkosi.azure.conf
  image/mkosi.conf.d/mkosi.conf
  image/mkosi.conf.d/mkosi.gcp.conf
  image/mkosi.conf.d/mkosi.openstack.conf
  image/mkosi.conf.d/mkosi.qemu.conf
  image/mkosi.conf.d/selinux.conf
  image/mkosi.repart/00-esp.conf
  image/mkosi.repart/10-root.conf
  image/mkosi.repart/20-root-verity.conf
  image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/module-setup.sh
  image/mkosi.skeleton/usr/lib/systemd/resolved.conf.d/fallback_dns.conf
  image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset
Labels: no changelog

#1680 bazel: fix MacOS builds
  tools/workspace_status.sh
Labels: bug fix, no changelog

#1681 misc: replace sha256sum with shasum -a 256
  .github/actions/install_operator_sdk/action.yml
  .github/workflows/build-os-image.yml
  .github/workflows/release-cli.yml
  .github/workflows/test-tidy.yml
  e2e/miniconstellation/test-remote.sh
  hack/docgen-builder/build-and-upload.sh
  hack/pseudo-version/pseudo_version_tool_freshness.sh.in
  image/measured-boot/precalculate_pcr_12.sh
  image/measured-boot/precalculate_pcr_9.sh
  tools/update-pseudo-version-tool.sh
Labels: no changelog

#1686 cli: configurable state disk type on OpenStack
  cli/internal/cloudcmd/create.go
  cli/internal/terraform/terraform/openstack/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/openstack/variables.tf
  cli/internal/terraform/variables.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
Labels: no changelog

#1696 cli: force-delete Azure resource group (#1667)
  cli/internal/cmd/iamdestroy.go
  cli/internal/terraform/terraform/azure/main.tf
  cli/internal/terraform/terraform/iam/azure/main.tf
  docs/docs/workflows/config.md
Labels: backport

#1672 ci: update measurements and image version on main
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/build-os-image.yml
  .github/workflows/release.yml
  internal/config/BUILD.bazel
  internal/config/image.go
  internal/config/images_enterprise.go
Labels: no changelog

#1697 ci: prevent google auth warnings when reauthenticating
  .github/actions/login_gcp/action.yml
Labels: no changelog

#1693 bazel: allow custom container_prefix
  .bazelrc
  BUILD.bazel
  bazel/oci/containers.bzl
  bazel/oci/pin.bzl
  bazel/release/BUILD.bazel
  bazel/settings/BUILD.bazel
  bazel/toolchains/oci_deps.bzl
  cli/internal/helm/imageversion/BUILD.bazel
  dev-docs/workflows/build-test-run.md
  hack/oci-pin/codegen.go
  hack/oci-pin/oci-pin.go
  hack/oci-pin/sum.go
  internal/config/imageversion/BUILD.bazel
Labels: no changelog

#1683 terraform: fix aws worker node permission
  cli/internal/terraform/terraform/iam/aws/main.tf
Labels: no changelog

#1698 docs: align container_prefix suggestion
  dev-docs/workflows/build-test-run.md
Labels: no changelog

#1665 ci: add Terraform logging
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_destroy/action.yml
  .github/actions/constellation_iam_create/action.yml
  .github/actions/constellation_iam_destroy/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/upload_terraform_logs/action.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#1700 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image.go
Labels: no changelog

#1701 ci: rename all usages of bazel push target from //:push to //bazel/release:push
  .github/actions/e2e_test/action.yml
  .github/workflows/release-cli.yml
Labels: no changelog

#1703 ci: fix os image build schedule
  .github/workflows/build-os-image-scheduled.yml
Labels: no changelog
