Repository edgelesssys/constellation, pull requests merged in 2023-12, with the labels that each got.

#2666 rfc: fix path of trusted images RFC
  rfc/015-trusted-kubernetes-images.md
Labels: no changelog

#2659 license: refactor license check to be agnostic of input
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/license_enterprise.go
  cli/internal/cmd/license_oss.go
  cli/internal/cmd/upgradeapply_test.go
  internal/constellation/BUILD.bazel
  internal/constellation/apply.go
  internal/license/BUILD.bazel
  internal/license/checker_enterprise.go
  internal/license/checker_oss.go
  internal/license/file.go
  internal/license/file_test.go
Labels: no changelog

#2668 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2669 ref: decouple helm from config
  cli/internal/cmd/applyhelm.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/upgradeapply_test.go
  internal/helm/BUILD.bazel
  internal/helm/helm.go
  internal/helm/helm_test.go
  internal/helm/loader.go
  internal/helm/loader_test.go
  internal/helm/overrides.go
Labels: no changelog

#2660 Make Kubernetes serviceCIDR configurable in config
  bootstrapper/cmd/bootstrapper/test.go
  bootstrapper/initproto/init.pb.go
  bootstrapper/initproto/init.proto
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/initserver/initserver_test.go
  bootstrapper/internal/kubernetes/k8sapi/kubeadm_config.go
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  cli/internal/cmd/applyinit.go
  internal/config/config.go
  internal/config/config_doc.go
  terraform/constellation-cluster/main.tf
  terraform/constellation-cluster/variables.tf
Labels: feature

#2676 cli: fix helm-timeout flags for deprecated commands
  cli/internal/cmd/create.go
  cli/internal/cmd/init.go
  cli/internal/cmd/upgradeapply.go
Labels: no changelog

#2675 ci: fix constellation cli path
  .github/actions/build_cli/action.yml
  .github/actions/self_managed_create/action.yml
Labels: no changelog

#2665 constellation-lib: refactor init RPC to be shared
  cli/internal/cloudcmd/validators.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/applyinit.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  internal/constellation/BUILD.bazel
  internal/constellation/apply.go
  internal/constellation/apply_test.go
  internal/constellation/applyinit.go
  internal/constellation/applyinit_test.go
Labels: no changelog

#2664 helm: deprioritize Cilium tc filters
  internal/helm/values.go
Labels: no changelog

#2661 docs: add Kubernetes version support list
  CODEOWNERS
  bazel/ci/BUILD.bazel
  bazel/ci/version_info_gen.sh.in
  docs/docs/architecture/versions.md
  hack/versioninfogen/BUILD.bazel
  hack/versioninfogen/main.go
Labels: documentation

#2678 terraform-provider: data skeleton for cluster resource
  dev-docs/workflows/terraform-provider.md
  internal/attestation/idkeydigest/idkeydigest.go
  rfc/014-terraform-provider.md
  terraform-provider-constellation/docs/data-sources/attestation.md
  terraform-provider-constellation/docs/data-sources/image.md
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/docs/resources/example.md
  terraform-provider-constellation/go.mod
  terraform-provider-constellation/go.sum
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/attestation_data_source.go
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/cluster_resource_test.go
  terraform-provider-constellation/internal/provider/convert.go
  terraform-provider-constellation/internal/provider/convert_test.go
  terraform-provider-constellation/internal/provider/example_resource.go
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/provider.go
  terraform-provider-constellation/internal/provider/shared_attributes.go
Labels: no changelog

#2689 deps: bump Go to 1.21.5
  .github/actions/versionsapi/Dockerfile
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  bazel/go/go.nix
  go.work
  terraform-provider-constellation/go.mod
Labels: no changelog

#2683 terraform-provider: sync provider docs to Terraform provider repository
  .github/workflows/sync-terraform-docs.yml
Labels: no changelog

#2688 bazel: migrate all integration tests (and retire CMakeLists.txt)
  .github/workflows/test-integration.yml
  CMakeLists.txt
  WORKSPACE.bazel
  csi/test/BUILD.bazel
  csi/test/mount_integration_test.go
  disk-mapper/internal/test/BUILD.bazel
  disk-mapper/internal/test/integration_test.go
Labels: no changelog

#2690 docs: replace reference to CMakeList on main branch with versioned link or Bazel
  docs/docs/reference/slsa.md
  docs/styles/Vocab/constellation/accept.txt
  docs/versioned_docs/version-2.10/reference/slsa.md
  docs/versioned_docs/version-2.11/reference/slsa.md
  docs/versioned_docs/version-2.12/reference/slsa.md
  docs/versioned_docs/version-2.13/reference/slsa.md
  docs/versioned_docs/version-2.3/reference/slsa.md
  docs/versioned_docs/version-2.4/reference/slsa.md
  docs/versioned_docs/version-2.5/reference/slsa.md
  docs/versioned_docs/version-2.6/reference/slsa.md
  docs/versioned_docs/version-2.7/reference/slsa.md
  docs/versioned_docs/version-2.8/reference/slsa.md
  docs/versioned_docs/version-2.9/reference/slsa.md
Labels: no changelog

#2682 constellation-lib: move state and featureset packages
  CODEOWNERS
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/apply.go
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/applyhelm.go
  cli/internal/cmd/applyinit.go
  cli/internal/cmd/applyterraform.go
  cli/internal/cmd/cloud.go
  cli/internal/cmd/cloud_test.go
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/minidown.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/terminate_test.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  cli/internal/terraform/BUILD.bazel
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform_test.go
  hack/gocoverage/main_test.go
  internal/constellation/BUILD.bazel
  internal/constellation/applyinit.go
  internal/constellation/applyinit_test.go
  internal/constellation/featureset/BUILD.bazel
  internal/constellation/featureset/featureset.go
  internal/constellation/featureset/featureset_enterprise.go
  internal/constellation/featureset/featureset_oss.go
  internal/constellation/helm.go
  internal/constellation/helm/BUILD.bazel
  internal/constellation/helm/helm.go
  internal/constellation/helm/helm_test.go
  internal/constellation/helm/loader.go
  internal/constellation/helm/loader_test.go
  internal/constellation/helm/overrides.go
  internal/constellation/state/BUILD.bazel
  internal/constellation/state/state.go
  internal/constellation/state/state_doc.go
  internal/constellation/state/state_test.go
  internal/constellation/state/validation_test.go
Labels: no changelog

#2693 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2692 terraform: fix Azure marketplace image defaults
  cli/internal/cloudcmd/tfvars.go
  cli/internal/terraform/variables.go
  cli/internal/terraform/variables_test.go
  internal/config/config.go
Labels: no changelog

#2699 ci: disable curses support
  bazel/bazelrc/ci.bazelrc
Labels: no changelog

#2696 installer: make hash checking optional
  internal/installer/installer.go
  internal/installer/installer_test.go
Labels: no changelog

#2686 terraform-provider: create release in provider repo on Constellation release
  .github/actions/download_release_binaries/action.yml
  .github/workflows/build-binaries.yml
  .github/workflows/draft-release.yml
  .github/workflows/release-tf-provider.yml
  .github/workflows/release.yml
  dev-docs/workflows/release.md
Labels: no changelog

#2691 terraform-provider: implement `constellation_cluster` resource
  .github/actions/upload_terraform_module/action.yml
  .github/workflows/e2e-test-tf-module.yml
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/serviceaccount.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/applyinit.go
  cli/internal/cmd/init_test.go
  docs/docs/workflows/terraform-module.md
  internal/constellation/BUILD.bazel
  internal/constellation/applyinit.go
  internal/constellation/applyinit_test.go
  internal/constellation/serviceaccount.go
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/examples/resources/constellation_cluster/resource.tf
  terraform-provider-constellation/examples/resources/scaffolding_example/resource.tf
  terraform-provider-constellation/go.mod
  terraform-provider-constellation/go.sum
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/cluster_resource_test.go
  terraform-provider-constellation/internal/provider/convert.go
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/image_data_source_test.go
  terraform/legacy-module/aws-constellation/main.tf
  terraform/legacy-module/aws-constellation/variables.tf
  terraform/legacy-module/azure-constellation/main.tf
  terraform/legacy-module/azure-constellation/variables.tf
  terraform/legacy-module/common/fetch-image/.terraform.lock.hcl
  terraform/legacy-module/common/fetch-image/main.tf
  terraform/legacy-module/common/fetch-image/output.tf
  terraform/legacy-module/common/fetch-image/variables.tf
  terraform/legacy-module/common/install-yq.sh
  terraform/legacy-module/constellation-cluster/.terraform.lock.hcl
  terraform/legacy-module/constellation-cluster/install-constellation.sh
  terraform/legacy-module/constellation-cluster/main.tf
  terraform/legacy-module/constellation-cluster/variables.tf
  terraform/legacy-module/gcp-constellation/main.tf
  terraform/legacy-module/gcp-constellation/variables.tf
Labels: feature

#2697 upgrade-agent: set explicit k8s version for kubeadm
  upgrade-agent/internal/server/server.go
Labels: no changelog

#2706 ci: use `sed` from GNU Coreutils
  WORKSPACE.bazel
  bazel/devbuild/BUILD.bazel
  bazel/devbuild/prepare_developer_workspace.sh.in
Labels: no changelog

#2705 ci: add v prefix to packaged Terraform provider binary
  .github/workflows/draft-release.yml
Labels: no changelog

#2708 constellation-lib: fix incorrect encoding and ordering of Init response
  internal/constellation/applyinit.go
Labels: no changelog

#2702 terraform-provider: support importing Constellation clusters
  bazel/ci/shellcheck.sh.in
  bazel/ci/shfmt.sh.in
  bazel/ci/terraform.sh.in
  dev-docs/workflows/terraform-provider.md
  internal/constants/constants.go
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/examples/resources/constellation_cluster/import.sh
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/cluster_resource_test.go
Labels: feature

#2710 deps: tidy terraform-provider
  terraform-provider-constellation/go.mod
  terraform-provider-constellation/go.sum
Labels: no changelog

#2709 Revert "helm: deprioritize Cilium tc filters"
  internal/constellation/helm/values.go
Labels: no changelog

#2711 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2698 installer: add support for data URLs
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  internal/installer/BUILD.bazel
  internal/installer/installer.go
  internal/installer/installer_test.go
Labels: no changelog

#2714 bazel: place Terraform provider binaries in local registry path on devbuild
  bazel/devbuild/BUILD.bazel
  bazel/devbuild/prepare_developer_workspace.sh.in
  dev-docs/workflows/terraform-provider.md
Labels: no changelog

#2685 terraform-provider: cleanup and improve docs
  .github/actions/upload_terraform_module/action.yml
  .github/workflows/draft-release.yml
  .github/workflows/e2e-test-tf-module.yml
  .github/workflows/e2e-test-weekly.yml
  docs/docs/workflows/create.md
  docs/docs/workflows/terraform-module.md
  docs/docs/workflows/terraform-provider.md
  docs/sidebars.js
  terraform-provider-constellation/BUILD.bazel
  terraform-provider-constellation/docs/data-sources/attestation.md
  terraform-provider-constellation/docs/data-sources/image.md
  terraform-provider-constellation/docs/index.md
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/internal/data/providerdata.go
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/attestation_data_source.go
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/image_data_source_test.go
  terraform-provider-constellation/internal/provider/provider.go
  terraform-provider-constellation/internal/provider/provider_test.go
  terraform-provider-constellation/internal/provider/shared_attributes.go
  terraform-provider-constellation/main.go
  terraform/legacy-module/common/fetch-image/.terraform.lock.hcl
  terraform/legacy-module/constellation-cluster/.terraform.lock.hcl
Labels: no changelog

#2720 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2722 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2718 cli: fix upgrades when using outdated Kubernetes patch version
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  internal/versions/components/BUILD.bazel
  internal/versions/components/components.go
  internal/versions/components/components_test.go
Labels: no changelog

#2700 deps: Update cert manager to 1.12.6
  internal/constellation/helm/BUILD.bazel
  internal/constellation/helm/actionfactory.go
  internal/constellation/helm/charts/cert-manager/Chart.yaml
  internal/constellation/helm/charts/cert-manager/templates/cainjector-deployment.yaml
  internal/constellation/helm/charts/cert-manager/templates/cainjector-poddisruptionbudget.yaml
  internal/constellation/helm/charts/cert-manager/templates/cainjector-rbac.yaml
  internal/constellation/helm/charts/cert-manager/templates/controller-config.yaml
  internal/constellation/helm/charts/cert-manager/templates/crds.yaml
  internal/constellation/helm/charts/cert-manager/templates/deployment.yaml
  internal/constellation/helm/charts/cert-manager/templates/poddisruptionbudget.yaml
  internal/constellation/helm/charts/cert-manager/templates/rbac.yaml
  internal/constellation/helm/charts/cert-manager/templates/startupapicheck-job.yaml
  internal/constellation/helm/charts/cert-manager/templates/webhook-config.yaml
  internal/constellation/helm/charts/cert-manager/templates/webhook-deployment.yaml
  internal/constellation/helm/charts/cert-manager/templates/webhook-poddisruptionbudget.yaml
  internal/constellation/helm/charts/cert-manager/templates/webhook-psp-clusterrole.yaml
  internal/constellation/helm/charts/cert-manager/values.yaml
  internal/constellation/helm/generateCertManager.sh
  internal/constellation/helm/helm_test.go
  internal/constellation/helm/loader.go
Labels: feature

#2725 terraform-provider: unify image in-/output
  .github/actions/terraform_apply/action.yml
  terraform-provider-constellation/docs/data-sources/attestation.md
  terraform-provider-constellation/docs/data-sources/image.md
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/examples/full/aws_cluster.tf
  terraform-provider-constellation/examples/full/azure_cluster.tf
  terraform-provider-constellation/examples/full/gcp_cluster.tf
  terraform-provider-constellation/examples/resources/constellation_cluster/resource.tf
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/attestation_data_source.go
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/convert.go
  terraform-provider-constellation/internal/provider/convert_test.go
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/image_data_source_test.go
  terraform-provider-constellation/internal/provider/shared_attributes.go
Labels: no changelog

#2723 cilium: enable bpf masquerading
  internal/constellation/helm/overrides.go
  internal/constellation/helm/values.go
Labels: no changelog

#2721 feat: pin cert-manager image to sha256 checksum
  internal/constellation/helm/charts/cert-manager/values.yaml
  internal/constellation/helm/generateCertManager.sh
Labels: no changelog

#2728 terraform-provider: ignore invalid upgrades
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/cluster_resource.go
Labels: no changelog

#2713 terraform-provider: add usage examples
  .github/actions/terraform_apply/action.yml
  dev-docs/workflows/terraform-provider.md
  docs/docs/workflows/create.md
  docs/docs/workflows/terraform-provider.md
  internal/constellation/helm/actionfactory.go
  terraform-provider-constellation/docs/data-sources/attestation.md
  terraform-provider-constellation/docs/data-sources/image.md
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/examples/full/aws_cluster.tf
  terraform-provider-constellation/examples/full/azure_cluster.tf
  terraform-provider-constellation/examples/full/gcp_cluster.tf
  terraform-provider-constellation/examples/resources/constellation_cluster/resource.tf
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/attestation_data_source.go
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/convert.go
  terraform-provider-constellation/internal/provider/convert_test.go
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/image_data_source_test.go
  terraform-provider-constellation/internal/provider/shared_attributes.go
Labels: no changelog

#2726 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2733 terraform-provider: lock-step microservice version
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/examples/full/aws_cluster.tf
  terraform-provider-constellation/examples/full/azure_cluster.tf
  terraform-provider-constellation/examples/full/gcp_cluster.tf
  terraform-provider-constellation/examples/resources/constellation_cluster/resource.tf
  terraform-provider-constellation/internal/data/BUILD.bazel
  terraform-provider-constellation/internal/data/providerdata.go
  terraform-provider-constellation/internal/provider/attestation_data_source.go
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/provider.go
Labels: no changelog

#2729 deps: update rules_oci to a pre-release version to fix memory leak
  bazel/release/BUILD.bazel
  bazel/toolchains/oci_deps.bzl
  e2e/malicious-join/BUILD.bazel
Labels: dependencies

#2731 ci: add burgerdev to e2e failure assignees
  .github/actions/pick_assignee/action.yml
Labels: no changelog

#2732 ci: don't run unit tests in integration test workflow
  .github/workflows/test-integration.yml
Labels: no changelog

#2738 operators: fix flaky env test
  operators/constellation-node-operator/controllers/pendingnode_controller_env_test.go
Labels: no changelog

#2741 ci: repair on-release workflow
  .github/workflows/on-release.yml
Labels: no changelog

#2742 ci: start v2.15-pre window
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  version.txt
Labels: no changelog

#2747 docs: update release process
  dev-docs/workflows/release.md
Labels: no changelog

#2567 ci: encrypt artifacts
  .github/actions/artifact_download/action.yml
  .github/actions/artifact_upload/action.yml
  .github/actions/constellation_create/action.yml
  .github/actions/download_release_binaries/action.yml
  .github/actions/e2e_benchmark/action.yml
  .github/actions/e2e_sonobuoy/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/upload_terraform_module/action.yml
  .github/workflows/build-os-image.yml
  .github/workflows/draft-release.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/e2e-windows.yml
  .github/workflows/reproducible-builds.yml
  .github/workflows/scorecard.yml
Labels: no changelog

#2744 terraform-provider: add input validation
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/internal/provider/attestation_data_source.go
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/cluster_resource_test.go
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/image_data_source_test.go
Labels: no changelog

#2759 ci: fix artifacts download/upload for release draft workflow
  .github/actions/artifact_download/action.yml
  .github/actions/artifact_upload/action.yml
  .github/actions/download_release_binaries/action.yml
  .github/workflows/draft-release.yml
Labels: no changelog

#2764 versions: generate k8s image patches (incl etcd)
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  internal/versions/hash-generator/BUILD.bazel
  internal/versions/hash-generator/generate.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  terraform-provider-constellation/go.mod
  terraform-provider-constellation/go.sum
Labels: no changelog

#2770 terraform-provider: only build as enterprise user
  bazel/devbuild/BUILD.bazel
  bazel/devbuild/prepare_developer_workspace.sh.in
Labels: no changelog

#2766 terraform-provider: validate image and microservice version
  internal/config/config.go
  internal/config/validation.go
  internal/config/validation_test.go
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/cluster_resource_test.go
Labels: feature

#2771 ci: don't use disallowed action when uploading scorecard
  .github/workflows/scorecard.yml
Labels: no changelog

#2772 ci: selectively remove artifact encryption
  .github/workflows/build-os-image.yml
  .github/workflows/reproducible-builds.yml
Labels: no changelog

#2773 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2758 terraform-provider: fix parsing `api_server_cert_sans`
  terraform-provider-constellation/examples/full/aws_cluster.tf
  terraform-provider-constellation/examples/full/azure_cluster.tf
  terraform-provider-constellation/examples/full/gcp_cluster.tf
  terraform-provider-constellation/internal/provider/cluster_resource.go
Labels: bug fix

#2778 ci: fix provider release through correct zipping
  .github/workflows/draft-release.yml
Labels: no changelog

#2776 ci: remove artifact encryption for public artifacts
  .github/actions/upload_terraform_module/action.yml
  .github/workflows/build-os-image.yml
  .github/workflows/draft-release.yml
  .github/workflows/e2e-windows.yml
  bazel/ci/unused_gh_actions.sh.in
Labels: bug fix, no changelog

#2746 docs: mention TF provider more prominently
  README.md
  docs/docs/getting-started/install.md
  docs/docs/overview/product.md
  docs/docs/workflows/terraform-provider.md
  docs/versioned_docs/version-2.14/getting-started/install.md
  docs/versioned_docs/version-2.14/overview/product.md
  docs/versioned_docs/version-2.14/workflows/terraform-provider.md
Labels: no changelog

#2784 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies
