Repository edgelesssys/constellation, pull requests merged in 2023-08, with the labels that each got.

#2143 ci: clone constellation repo into separate dir
  .github/workflows/aws-snp-launchmeasurement.yml
Labels: no changelog

#2142 api: add functions to transparently handle signatures upon API interaction
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/cmd/verifier_test.go
  cli/internal/kubernetes/upgrade.go
  image/upload/internal/cmd/measurementsenvelope.go
  image/upload/internal/cmd/upload.go
  internal/api/attestationconfigapi/fetcher.go
  internal/api/attestationconfigapi/fetcher_test.go
  internal/api/client/BUILD.bazel
  internal/api/client/client.go
  internal/api/fetcher/BUILD.bazel
  internal/api/fetcher/fetcher.go
  internal/api/versionsapi/cli/add.go
  internal/api/versionsapi/cli/list.go
  internal/api/versionsapi/cli/rm.go
  internal/api/versionsapi/client.go
  internal/api/versionsapi/list.go
  internal/api/versionsapi/list_test.go
  internal/api/versionsapi/version.go
  internal/api/versionsapi/version_test.go
  internal/attestation/measurements/BUILD.bazel
  internal/attestation/measurements/measurement-generator/BUILD.bazel
  internal/attestation/measurements/measurement-generator/generate.go
  internal/attestation/measurements/measurements.go
  internal/attestation/measurements/measurements_test.go
  internal/config/config.go
  internal/config/validation.go
  internal/imagefetcher/imagefetcher.go
  internal/osimage/archive/archive.go
  internal/osimage/aws/awsupload.go
  internal/osimage/azure/azureupload.go
  internal/osimage/gcp/gcpupload.go
  internal/osimage/imageinfo/imageinfo.go
  internal/osimage/measurementsuploader/measurementsuploader.go
  internal/sigstore/BUILD.bazel
  internal/sigstore/keyselect/BUILD.bazel
  internal/sigstore/keyselect/keyselect.go
  internal/sigstore/rekor.go
  internal/sigstore/sign_test.go
  internal/sigstore/verify.go
  internal/sigstore/verify_test.go
Labels: no changelog

#2151 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2154 config: reorder values
  internal/config/config.go
  internal/config/config_doc.go
Labels: no changelog

#2156 deps: bump go version
  .github/actions/versionsapi/Dockerfile
  .github/workflows/azure-snp-reporter.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/build-os-image.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  WORKSPACE.bazel
Labels: dependencies

#2155 terraform: fix uami parsing
  cli/internal/terraform/terraform/azure/main.tf
Labels: no changelog

#2153 cli: unify chart value setup
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/init.go
  cli/internal/helm/install.go
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  cli/internal/helm/overrides.go
  cli/internal/helm/release.go
  cli/internal/terraform/terraform.go
Labels: no changelog

#2160 Update codeowners and remove old tools
  CODEOWNERS
  hack/azure-jump-host/README.md
  hack/azure-jump-host/jump-host-create
  hack/azure-jump-host/parameters.json
  hack/azure-jump-host/template.json
  hack/docgen-builder/build-and-upload.sh
  hack/importAzure.sh
Labels: no changelog

#2158 cli: refactor terraform output parsing
  cli/internal/terraform/terraform.go
Labels: no changelog

#2157 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2109 ci: keep embedded measurements if stable image is used
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  cli/internal/cmd/configfetchmeasurements.go
Labels: hold, no changelog

#2163 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2159 cli: fix missing init parameters in mini up
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
Labels: no changelog

#2148 cli: add `--workspace` flag to set base directory for Constellation workspace
  cli/cmd/BUILD.bazel
  cli/cmd/root.go
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cloudcmd/iam.go
  cli/internal/cloudcmd/iam_test.go
  cli/internal/cloudcmd/terminate.go
  cli/internal/cloudcmd/terminate_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/cloud.go
  cli/internal/cmd/cloud_test.go
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/configmigrate.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/iamcreate_test.go
  cli/internal/cmd/iamdestroy.go
  cli/internal/cmd/iamdestroy_test.go
  cli/internal/cmd/iamupgradeapply.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/minidown.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/recover_test.go
  cli/internal/cmd/status.go
  cli/internal/cmd/terminate.go
  cli/internal/cmd/terminate_test.go
  cli/internal/cmd/tfmigrationclient.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  cli/internal/cmd/workspace.go
  cli/internal/helm/backup.go
  cli/internal/helm/init.go
  cli/internal/helm/install.go
  cli/internal/helm/upgrade.go
  cli/internal/kubernetes/upgrade.go
  cli/internal/terraform/loader_test.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform_test.go
  cli/internal/upgrade/iammigrate.go
  cli/internal/upgrade/iammigrate_test.go
  cli/internal/upgrade/terraform.go
  cli/internal/upgrade/terraform_test.go
  debugd/internal/cdbg/cmd/deploy.go
  docs/docs/reference/cli.md
  e2e/internal/upgrade/upgrade_test.go
  internal/constants/constants.go
Labels: feature

#2166 cli: update config migration to migrate v3 -> v4
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/configmigrate.go
  internal/config/migration/BUILD.bazel
  internal/config/migration/migration.go
Labels: no changelog

#2171 config: fix aws instance type validation
  internal/config/validation.go
Labels: no changelog

#2164 kubernetes: document total log size
  bootstrapper/internal/kubernetes/k8sapi/kubeadm_config.go
Labels: no changelog

#2176 cli: fix upgrade test by only setting nodeGroup for >v2.9
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_test/action.yml
Labels: no changelog

#2170 cdbg: implement workspace / "-C" flag and "--bindir"
  debugd/internal/cdbg/cmd/deploy.go
  debugd/internal/cdbg/cmd/root.go
Labels: no changelog

#2172 cli: add maa token to the output of `verify` command
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
Labels: feature

#2167 cli: declare mastersecret as immutable and print attestationCfg diff in warning
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/status.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/helm/charts/edgeless/constellation-services/charts/key-service/templates/mastersecret.yaml
  cli/internal/helm/testdata/AWS/constellation-services/charts/key-service/templates/mastersecret.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/key-service/templates/mastersecret.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/key-service/templates/mastersecret.yaml
  cli/internal/helm/testdata/OpenStack/constellation-services/charts/key-service/templates/mastersecret.yaml
  cli/internal/helm/testdata/QEMU/constellation-services/charts/key-service/templates/mastersecret.yaml
  cli/internal/kubernetes/kubernetes.go
  cli/internal/kubernetes/upgrade.go
  cli/internal/kubernetes/upgrade_test.go
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  operators/constellation-node-operator/go.sum
Labels: no changelog

#2175 docs: document node groups and migration from old config fields
  docs/docs/reference/migration.md
  docs/docs/workflows/config.md
Labels: no changelog

#2183 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2180 cli: strict input validation on attestation version numbers
  internal/config/attestationversion.go
  internal/config/attestationversion_test.go
Labels: no changelog

#2184 e2e: remove existingConfig field
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_iam_create/action.yml
  .github/actions/e2e_test/action.yml
Labels: bug fix, no changelog

#2187 internal: fix unmarshalling attestation version numbers from JSON
  cli/internal/cmd/upgradeapply_test.go
  internal/config/attestationversion.go
  internal/config/attestationversion_test.go
Labels: no changelog

#2162 ci: fix recover test
  .github/actions/e2e_recover/action.yml
Labels: no changelog

#2189 e2e: cleanup test inputs
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_test/action.yml
Labels: no changelog

#2203 deps: update bazel, rules_go and gazelle
  .bazelversion
  bazel/container/Containerfile
  bazel/container/container.sh
  bazel/toolchains/go_rules_deps.bzl
Labels: no changelog

#2202 bazel: remove stale build rules
  cli/internal/cmd/pathprefix/BUILD.bazel
  disk-mapper/internal/diskencryption/BUILD.bazel
  internal/sigstore/keyselect/BUILD.bazel
Labels: no changelog

#2205 ci: allow setting region/zone for e2e tests
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#2206 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2210 cloud: use instanceid as name in aws
  internal/cloud/aws/aws.go
  internal/cloud/aws/aws_test.go
Labels: no changelog

#2215 e2e: use Kubernetes 1.26 in daily test
  .github/workflows/e2e-test-daily.yml
Labels: no changelog

#2216 cli: don't refer to a message below, as it was printed above
  cli/internal/cmd/tfmigrationclient.go
Labels: no changelog

#2212 internal: move `watcher` package from `internal` to `joinservice`
  CODEOWNERS
  joinservice/cmd/BUILD.bazel
  joinservice/cmd/main.go
  joinservice/internal/watcher/BUILD.bazel
  joinservice/internal/watcher/validator.go
  joinservice/internal/watcher/validator_test.go
  joinservice/internal/watcher/watcher.go
  joinservice/internal/watcher/watcher_test.go
Labels: no changelog

#2177 cli: upgrade uses same helm releases as init
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/serviceaccount.go
  cli/internal/clusterid/id.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/init.go
  cli/internal/cmd/status.go
  cli/internal/cmd/status_test.go
  cli/internal/cmd/upgrade.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  cli/internal/helm/upgrade.go
  cli/internal/helm/upgrade_test.go
  cli/internal/kubernetes/BUILD.bazel
  cli/internal/kubernetes/kubernetes.go
  cli/internal/kubernetes/upgrade.go
  cli/internal/kubernetes/upgrade_test.go
  cli/internal/upgrade/BUILD.bazel
  cli/internal/upgrade/terraform.go
  docs/docs/reference/cli.md
  docs/docs/workflows/troubleshooting.md
Labels: no changelog

#2217 ci: add e2e-mini to daily test
  .github/workflows/e2e-test-daily.yml
Labels: no changelog

#2219 cli: fix configmap backup during upgrade
  cli/internal/kubernetes/upgrade.go
Labels: no changelog

#2221 ci: fix notify trigger in e2e upgrade workflow
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#2130 cli: add role to aws instance name
  cli/internal/terraform/terraform/aws/main.tf
Labels: no changelog

#2223 ci: set bazel build event stream timeout to 600s
  .github/actions/setup_bazel/action.yml
Labels: no changelog

#2224 cli: only allow chart upgrades with greater version
  cli/internal/helm/upgrade.go
Labels: no changelog

#2211 upgrade: don't pass vm image
  cli/internal/cloudcmd/terraform.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
Labels: no changelog

#2227 ci: set bazlrc options for "common" instead of "build" if they are common
  .github/actions/setup_bazel/action.yml
Labels: no changelog

#2229 cli: update join-config manually during upgrade
  cli/internal/cmd/upgradeapply.go
  cli/internal/kubernetes/upgrade.go
Labels: no changelog

#2236 bazel: use -C flag in govulncheck ci
  bazel/ci/govulncheck.sh.in
Labels: no changelog

#2238 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2222 cli: move helm and terraform out of kubernetes package
  cli/internal/cmd/iamupgradeapply.go
  cli/internal/cmd/upgrade.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/kubernetes/BUILD.bazel
  cli/internal/kubernetes/upgrade.go
  cli/internal/upgrade/terraform.go
  cli/internal/upgrade/terraform_test.go
Labels: no changelog

#2228 image: use longterm release of the Linux kernel
  image/Makefile
  image/README.md
  image/mkosi.conf.d/mkosi.aws.conf
  image/mkosi.conf.d/mkosi.azure.conf
  image/mkosi.conf.d/mkosi.conf
  image/mkosi.conf.d/mkosi.gcp.conf
  image/mkosi.conf.d/mkosi.openstack.conf
  image/mkosi.conf.d/mkosi.qemu.conf
Labels: no changelog

#2240 bazel: set most options to "common" in bazelrc
  .bazelrc
Labels: no changelog

#2243 docs: update screencasts to demo node groups
  docs/screencasts/README.md
  docs/static/assets/check-sbom.cast
  docs/static/assets/configure-cluster.cast
  docs/static/assets/create-cluster.cast
  docs/static/assets/terminate-cluster.cast
  docs/static/assets/verify-cli.cast
  docs/static/img/shell-windowframe.svg
Labels: no changelog

#2249 cli: fix incorrect file path for master secret during upgrades when using workspace flag
  cli/internal/cloudcmd/serviceaccount.go
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/create.go
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/iamdestroy.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/pathprefix/pathprefix.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/terminate.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/verify.go
Labels: bug fix, needs backport

#2250 cli: fix upgrade by passing placeholder values for images
  cli/internal/cloudcmd/terraform.go
Labels: bug fix, needs backport

#2247 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2257 ci: fix recover wait condition
  .github/actions/e2e_recover/action.yml
Labels: no changelog

#2242 deps: support Kubernetes 1.28
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  docs/docs/reference/cli.md
  internal/config/validation.go
  internal/versions/versions.go
Labels: feature

#2258 ci: add aspect workflows
  .aspect/workflows/config.yaml
  .github/actionlint.yaml
  .github/workflows/.aspect-workflows-reusable.yaml
  .github/workflows/aspect-workflows-warming.yaml
  .github/workflows/aspect-workflows.yaml
Labels: no changelog

#2260 ci: fine tune aspect workflows settings
  .aspect/workflows/config.yaml
Labels: no changelog

#2256 cli: clean up terraform package
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/iam.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform_test.go
  cli/internal/upgrade/iammigrate.go
  cli/internal/upgrade/iammigrate_test.go
  cli/internal/upgrade/terraform.go
  cli/internal/upgrade/terraform_test.go
Labels: no changelog

#2264 bazel: use yq from runfiles in devbuild
  bazel/devbuild/BUILD.bazel
Labels: no changelog

#2262 bazel: correctly set buildbuddy api key
  .github/actions/setup_bazel/action.yml
Labels: no changelog

#2267 bazel: fix ordering of injects
  bazel/devbuild/prepare_developer_workspace.sh.in
Labels: no changelog

#2265 cli: fix incorrect actual values for constellation verify on AWS
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/verify.go
Labels: bug fix

#2255 ci: fix Windows e2e test
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-windows.yml
Labels: no changelog

#2232 cli: refactor kubernetes package
  CODEOWNERS
  bootstrapper/cmd/bootstrapper/main.go
  bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/status.go
  cli/internal/cmd/status_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/helm/backup.go
  cli/internal/helm/backup_test.go
  cli/internal/helm/upgrade.go
  cli/internal/kubecmd/BUILD.bazel
  cli/internal/kubecmd/kubecmd.go
  cli/internal/kubecmd/kubecmd_test.go
  cli/internal/kubecmd/status.go
  cli/internal/kubernetes/kubernetes.go
  cli/internal/kubernetes/status.go
  cli/internal/kubernetes/upgrade.go
  internal/kubernetes/kubectl/BUILD.bazel
  internal/kubernetes/kubectl/kubectl.go
Labels: no changelog

#2185 docs: add note on how we handle deprecations
  dev-docs/workflows/deprecations.md
Labels: no changelog

#2226 docs: update release docs
  dev-docs/workflows/release.md
Labels: no changelog

#2251 cli: remove helm management from join-config
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/configmap.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/values.schema.json
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/values.yaml
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  cli/internal/helm/overrides.go
  cli/internal/helm/testdata/AWS/constellation-services/charts/join-service/templates/configmap.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/configmap.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/join-service/templates/configmap.yaml
  cli/internal/helm/testdata/OpenStack/constellation-services/charts/join-service/templates/configmap.yaml
  cli/internal/helm/testdata/QEMU/constellation-services/charts/join-service/templates/configmap.yaml
  cli/internal/kubecmd/BUILD.bazel
  cli/internal/kubecmd/kubecmd.go
  cli/internal/kubecmd/kubecmd_test.go
  docs/docs/workflows/troubleshooting.md
Labels: no changelog

#2274 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2235 cli: parse image and k8s versions as semver
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  internal/semver/semver.go
Labels: no changelog

#2277 ci: fix ccm build when no new version are found
  .github/actions/gcpccm_vers_to_build/findvers.sh
  .github/workflows/build-ccm-gcp.yml
Labels: no changelog

#2275 docs: document upgrade backup files
  docs/docs/workflows/upgrade.md
Labels: documentation

#2279 ci: upgrade test from v2.10.1
  .github/workflows/e2e-test-release.yml
  dev-docs/workflows/release.md
Labels: no changelog

#2282 cli: cleanup terraform files when create fails
  cli/internal/cloudcmd/rollback.go
  cli/internal/cloudcmd/rollback_test.go
Labels: no changelog

#2284 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2285 docs: document constellation-cluster.log file
  cli/internal/cmd/init.go
  docs/docs/workflows/create.md
Labels: no changelog

#2289 ci: collect Terraform logs on `iam create`
  .github/actions/constellation_iam_create/action.yml
Labels: no changelog

#2278 ci: idempotent release pipeline
  .github/workflows/on-release.yml
  .github/workflows/release.yml
  dev-docs/workflows/release.md
Labels: no changelog

#2288 docs: publish fixes in performance section to 2.10
  docs/versioned_docs/version-2.10/overview/performance/application.md
  docs/versioned_docs/version-2.10/overview/performance/io.md
  docs/versioned_docs/version-2.10/overview/performance/performance.md
Labels: no changelog

#2283 ci: comment Go coverage report on PR
  .github/workflows/test-unittest.yml
  CODEOWNERS
  bazel/ci/BUILD.bazel
  bazel/ci/gocoverage_diff.sh.in
  bazel/ci/golangci_lint.sh.in
  hack/gocoverage/BUILD.bazel
  hack/gocoverage/main.go
  hack/gocoverage/main_test.go
Labels: no changelog

#2286 deps: update grpc-middleware to v2
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  internal/logger/BUILD.bazel
  internal/logger/grpclogger.go
  internal/logger/log.go
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
Labels: dependencies, no changelog

#2294 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog
