Repository edgelesssys/constellation, pull requests merged in 2023-11, with the labels that each got.

#2552 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2546 cli: fix invalid upper case name on AWS
  cli/internal/terraform/terraform/aws/variables.tf
  internal/config/config.go
  internal/config/config_test.go
  internal/config/validation.go
Labels: no changelog

#2523 cli: state file validation
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/recover_test.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  cli/internal/state/BUILD.bazel
  cli/internal/state/state.go
  cli/internal/state/state_test.go
  cli/internal/state/validation_test.go
  internal/validation/BUILD.bazel
  internal/validation/constraints.go
  internal/validation/constraints_test.go
  internal/validation/errors.go
  internal/validation/errors_test.go
  internal/validation/validation.go
  internal/validation/validation_test.go
Labels: feature

#2550 ci: share e2e workflow
  .github/workflows/e2e-test-internal-lb.yml
  .github/workflows/e2e-test-manual-internal.yml
  .github/workflows/e2e-test-self-managed.yml
  .github/workflows/e2e-test.yml
Labels: no changelog

#2556 cli: don't validate unused ownerID field
  cli/internal/state/state.go
Labels: no changelog

#2558 image: use dissect from nix
  image/measured-boot/cmd/BUILD.bazel
  image/measured-boot/cmd/main.go
Labels: no changelog

#2557 ci: use structured logging for all parts of the malicious-join test
  .github/actions/e2e_malicious_join/action.yml
  e2e/malicious-join/BUILD.bazel
  e2e/malicious-join/job.yaml
  e2e/malicious-join/job_template.sh.in
  e2e/malicious-join/malicious-join.go
Labels: no changelog

#2562 [Windows] cli: fix incorrect filepath separator causing upgrades to fail
  internal/file/file.go
Labels: bug fix

#2561 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2563 attestation: clear certificate cache in azure snp unittest
  internal/attestation/azure/snp/BUILD.bazel
  internal/attestation/azure/snp/validator_test.go
Labels: no changelog

#2564 validation: use regex instead of dns lookup for DNSName validation
  internal/validation/constraints.go
Labels: no changelog

#2565 ci: fix failure issue creation for Windows e2e test
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/e2e-windows.yml
Labels: no changelog

#2569 deps: bump Go to 1.21.4
  .bazelversion
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  WORKSPACE.bazel
  bazel/container/Containerfile
  bazel/container/container.sh
  bazel/go/go.nix
  dev-docs/workflows/bump-go-version.md
  flake.lock
  flake.nix
  go.work
Labels: no changelog

#2553 terraform: Terraform module for GCP
  .github/actions/upload_terraform_module/action.yml
  .github/workflows/e2e-test-tf-module.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/release-cli.yml
  terraform/aws-constellation/fetch-ami/main.tf
  terraform/aws-constellation/fetch-ami/output.tf
  terraform/aws-constellation/fetch-ami/variables.tf
  terraform/aws-constellation/main.tf
  terraform/constellation-cluster/install-yq.sh
  terraform/constellation-cluster/main.tf
  terraform/constellation-cluster/variables.tf
  terraform/fetch-image/.terraform.lock.hcl
  terraform/fetch-image/main.tf
  terraform/fetch-image/output.tf
  terraform/fetch-image/variables.tf
  terraform/gcp-constellation/.terraform.lock.hcl
  terraform/gcp-constellation/main.tf
  terraform/gcp-constellation/variables.tf
Labels: feature

#2555 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2575 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2571 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2574 ci: fix path in self managed create test
  .github/actions/self_managed_create/action.yml
  terraform/infrastructure/iam/gcp/README.md
Labels: no changelog

#2582 deps: update linux kernel to 6.1.62
  bazel/toolchains/linux_kernel.bzl
Labels: no changelog

#2566 terraform: add Terraform module for Azure
  .github/actions/find_latest_image/action.yml
  .github/actions/self_managed_create/action.yml
  .github/actions/upload_terraform_module/action.yml
  .github/workflows/e2e-test-tf-module.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-test.yml
  .github/workflows/release-cli.yml
  cli/cmd/root.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/maapatch.go
  cli/internal/cmd/maapatch_test.go
  dev-docs/workflows/release.md
  docs/docs/workflows/create.md
  hack/clidocgen/main.go
  hack/maa-patch/BUILD.bazel
  hack/maa-patch/main.go
  hack/maa-patch/main_test.go
  terraform/aws-constellation/main.tf
  terraform/aws-constellation/variables.tf
  terraform/azure-constellation/.terraform.lock.hcl
  terraform/azure-constellation/main.tf
  terraform/azure-constellation/variables.tf
  terraform/common/fetch-image/.terraform.lock.hcl
  terraform/common/fetch-image/main.tf
  terraform/common/fetch-image/output.tf
  terraform/common/fetch-image/variables.tf
  terraform/common/install-yq.sh
  terraform/constellation-cluster/install-constellation.sh
  terraform/constellation-cluster/install-yq.sh
  terraform/constellation-cluster/main.tf
  terraform/constellation-cluster/variables.tf
  terraform/gcp-constellation/main.tf
  terraform/gcp-constellation/variables.tf
  terraform/infrastructure/iam/azure/outputs.tf
Labels: feature

#2595 terraform: allow image to be empty
  .github/actions/upload_terraform_module/action.yml
  terraform/aws-constellation/variables.tf
  terraform/azure-constellation/variables.tf
  terraform/constellation-cluster/variables.tf
  terraform/gcp-constellation/variables.tf
Labels: no changelog

#2596 Revert "operator: always delete terminated pending nodes (#2545)"
  operators/constellation-node-operator/controllers/pendingnode_controller.go
Labels: no changelog

#2580 state: add migration for `IPCidrNode` and `InClusterEndpoint`
  cli/internal/cmd/apply.go
  cli/internal/state/BUILD.bazel
  cli/internal/state/state.go
Labels: no changelog

#2598 ci: checkout before selecting image
  .github/workflows/e2e-test.yml
Labels: no changelog

#2600 ci: refactor teams notification action
  .github/actions/notify_e2e_failure/action.yml
  .github/actions/notify_teams/action.yml
  .github/teams_payload_template.json
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/e2e-windows.yml
Labels: no changelog

#2602 ci: add missing `runner` value to s3proxy test
  .github/workflows/e2e-test-release.yml
Labels: no changelog

#2603 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2604 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2560 docs: add Terraform module
  docs/docs/workflows/create.md
  docs/docs/workflows/terraform-module.md
  docs/sidebars.js
Labels: no changelog

#2611 dev-docs: fix instructions in release docs
  dev-docs/howto/longhorn.md
  dev-docs/workflows/release.md
Labels: no changelog

#2612 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2549 cli: enable `constellation apply` to create new clusters
  .github/actions/constellation_create/action.yml
  cli/internal/cloudcmd/apply.go
  cli/internal/cloudcmd/tfplan.go
  cli/internal/cloudcmd/tfplan_test.go
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/applyterraform.go
  cli/internal/cmd/cloud.go
  cli/internal/cmd/cloud_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/recover_test.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/verify_test.go
  cli/internal/state/BUILD.bazel
  cli/internal/state/state.go
  docs/docs/architecture/attestation.md
  docs/docs/architecture/orchestration.md
  docs/docs/getting-started/first-steps-local.md
  docs/docs/getting-started/first-steps.md
  docs/docs/getting-started/install.md
  docs/docs/reference/terraform.md
  docs/docs/workflows/create.md
  docs/docs/workflows/lb.md
  docs/docs/workflows/terminate.md
  docs/docs/workflows/troubleshooting.md
  docs/docs/workflows/trusted-launch.md
Labels: feature

#2551 cli: use apply command to start mini cluster
  cli/internal/cmd/minidown.go
  cli/internal/cmd/miniup.go
  cli/internal/libvirt/libvirt.go
  internal/constants/constants.go
Labels: no changelog

#2616 deps: update rules_oci to 1.4.2
  bazel/release/BUILD.bazel
  bazel/toolchains/oci_deps.bzl
  e2e/malicious-join/BUILD.bazel
Labels: no changelog

#2614 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2617 ci: remove dash from create action
  .github/actions/constellation_create/action.yml
Labels: no changelog

#2627 ci: fix unsupported qemu in tests on mac
  cli/internal/cloudcmd/apply_test.go
Labels: no changelog

#2625 cli: fix panic in status cmd without conf file
  cli/internal/cmd/status.go
  cli/internal/cmd/status_test.go
  internal/config/config_test.go
Labels: bug fix

#2626 deps: update module github.com/hashicorp/*
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
Labels: no changelog

#2577 docs: add Helm chart for VPN connectivity
  dev-docs/howto/vpn/.helmignore
  dev-docs/howto/vpn/Chart.yaml
  dev-docs/howto/vpn/README.md
  dev-docs/howto/vpn/files/strongswan/charon-logging.conf
  dev-docs/howto/vpn/files/strongswan/entrypoint.sh
  dev-docs/howto/vpn/files/tproxy-setup.sh
  dev-docs/howto/vpn/files/wireguard-setup.sh
  dev-docs/howto/vpn/templates/_helpers.tpl
  dev-docs/howto/vpn/templates/configmaps.yaml
  dev-docs/howto/vpn/templates/secrets.yaml
  dev-docs/howto/vpn/templates/service.yaml
  dev-docs/howto/vpn/templates/strongswan-secret.tpl
  dev-docs/howto/vpn/templates/strongswan-statefulset.yaml
  dev-docs/howto/vpn/templates/wireguard-secret.tpl
  dev-docs/howto/vpn/templates/wireguard-statefulset.yaml
  dev-docs/howto/vpn/values.yaml
Labels: feature

#2637 ci: correctly clean up resource in self-managed infra tests
  .github/workflows/e2e-test.yml
Labels: no changelog

#2635 api: respect `HTTP(S)_PROXY` environment variable
  internal/api/fetcher/fetcher.go
Labels: bug fix

#2619 dev-docs: add on-prem terraform to vpn setup
  dev-docs/howto/vpn/helm/.helmignore
  dev-docs/howto/vpn/helm/Chart.yaml
  dev-docs/howto/vpn/helm/README.md
  dev-docs/howto/vpn/helm/files/strongswan/charon-logging.conf
  dev-docs/howto/vpn/helm/files/strongswan/entrypoint.sh
  dev-docs/howto/vpn/helm/files/tproxy-setup.sh
  dev-docs/howto/vpn/helm/files/wireguard-setup.sh
  dev-docs/howto/vpn/helm/templates/_helpers.tpl
  dev-docs/howto/vpn/helm/templates/configmaps.yaml
  dev-docs/howto/vpn/helm/templates/secrets.yaml
  dev-docs/howto/vpn/helm/templates/service.yaml
  dev-docs/howto/vpn/helm/templates/strongswan-secret.tpl
  dev-docs/howto/vpn/helm/templates/strongswan-statefulset.yaml
  dev-docs/howto/vpn/helm/templates/wireguard-secret.tpl
  dev-docs/howto/vpn/helm/templates/wireguard-statefulset.yaml
  dev-docs/howto/vpn/helm/values.yaml
  dev-docs/howto/vpn/on-prem-terraform/.terraform.lock.hcl
  dev-docs/howto/vpn/on-prem-terraform/main.tf
  dev-docs/howto/vpn/on-prem-terraform/output.tf
  dev-docs/howto/vpn/on-prem-terraform/variables.tf
Labels: no changelog

#2638 rfc: add numeric ids to existing RFCs
  rfc/001-key-derivation.md
  rfc/002-proof-of-ownership.md
  rfc/003-secure-software-distribution.md
  rfc/004-updates.md
  rfc/005-external-kms.md
  rfc/006-reproducible-builds.md
  rfc/007-version-api.md
  rfc/008-apis.md
  rfc/009-image-api.md
  rfc/010-cli-api.md
  rfc/011-attestation-config.md
  rfc/012-canonical-endpoint-dns.md
  rfc/013-state-file.md
  rfc/014-terraform-provider.md
Labels: no changelog

#2639 docs: fix deploy preview and some links
  docs/docusaurus.config.js
  docs/static/_redirects
Labels: no changelog

#2643 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2633 Fix Konnectivity migration
  internal/helm/actionfactory.go
  internal/helm/helm_test.go
  internal/kubecmd/BUILD.bazel
  internal/kubecmd/kubecmd.go
  internal/kubecmd/kubecmd_test.go
Labels: no changelog

#2632 terraform-provider: init provider scaffolding
  WORKSPACE.bazel
  bazel/ci/BUILD.bazel
  bazel/ci/terraform.sh.in
  bazel/ci/terraform_docgen.sh.in
  bazel/devbuild/BUILD.bazel
  bazel/devbuild/prepare_developer_workspace.sh.in
  bazel/settings/BUILD.bazel
  bazel/toolchains/aspect_bazel_lib.bzl
  bazel/toolchains/go_module_deps.bzl
  dev-docs/workflows/terraform-provider.md
  go.mod
  go.sum
  go.work
  terraform-provider-constellation/BUILD.bazel
  terraform-provider-constellation/config.tfrc.tpl
  terraform-provider-constellation/docs/data-sources/example.md
  terraform-provider-constellation/docs/index.md
  terraform-provider-constellation/docs/resources/example.md
  terraform-provider-constellation/examples/data-sources/scaffolding_example/data-source.tf
  terraform-provider-constellation/examples/provider/provider.tf
  terraform-provider-constellation/examples/resources/scaffolding_example/resource.tf
  terraform-provider-constellation/go.mod
  terraform-provider-constellation/go.sum
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/example_data_source.go
  terraform-provider-constellation/internal/provider/example_data_source_test.go
  terraform-provider-constellation/internal/provider/example_resource.go
  terraform-provider-constellation/internal/provider/example_resource_test.go
  terraform-provider-constellation/internal/provider/provider.go
  terraform-provider-constellation/internal/provider/provider_test.go
  terraform-provider-constellation/main.go
Labels: feature

#2644 state: fix whitespace issue in generated docs
  internal/state/state.go
  internal/state/state_doc.go
Labels: no changelog

#2642 terraform-provider: add image datasource
  bazel/ci/BUILD.bazel
  bazel/ci/terraform.sh.in
  bazel/ci/terraform_docgen.sh.in
  bazel/devbuild/prepare_developer_workspace.sh.in
  bazel/toolchains/go_module_deps.bzl
  dev-docs/workflows/terraform-provider.md
  terraform-provider-constellation/BUILD.bazel
  terraform-provider-constellation/docs/data-sources/example.md
  terraform-provider-constellation/docs/data-sources/image.md
  terraform-provider-constellation/docs/index.md
  terraform-provider-constellation/examples/data-sources/constellation_image/data-source.tf
  terraform-provider-constellation/examples/data-sources/scaffolding_example/data-source.tf
  terraform-provider-constellation/examples/provider/provider.tf
  terraform-provider-constellation/go.mod
  terraform-provider-constellation/go.sum
  terraform-provider-constellation/internal/data/BUILD.bazel
  terraform-provider-constellation/internal/data/data.go
  terraform-provider-constellation/internal/data/providerdata.go
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/example_data_source.go
  terraform-provider-constellation/internal/provider/example_data_source_test.go
  terraform-provider-constellation/internal/provider/example_resource_test.go
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/image_data_source_test.go
  terraform-provider-constellation/internal/provider/provider.go
  terraform-provider-constellation/internal/provider/provider_test.go
Labels: feature

#2645 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2636 ci: only generate lock files where provider is used
  bazel/ci/terraform.sh.in
  dev-docs/workflows/terraform.md
  terraform/aws-constellation/.terraform.lock.hcl
  terraform/azure-constellation/.terraform.lock.hcl
  terraform/gcp-constellation/.terraform.lock.hcl
Labels: no changelog

#2646 ci: add missing shell in notify action
  .github/actions/gh_create_issue/action.yml
  .github/actions/notify_e2e_failure/action.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/e2e-windows.yml
Labels: no changelog

#2652 ci: fix serivce accounts introduced by merge
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-tf-module.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#2653 ci: add notify hook to Terraform module test
  .github/actions/gh_create_issue/create_issue.sh
  .github/workflows/e2e-test-tf-module.yml
Labels: no changelog

#2654 config: remove AWS SNP warning
  cli/internal/cmd/apply.go
  docs/docs/workflows/config.md
  internal/config/config.go
  internal/config/config_doc.go
Labels: no changelog

#2649 ci: only run verify with JSON on v2.14 or newer
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_verify/action.yml
Labels: no changelog

#2655 ci: use given image if set
  .github/actions/find_latest_image/action.yml
Labels: no changelog

#2640 terraform-provider: add attestation data source
  bazel/ci/terraform.sh.in
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/verifier_test.go
  internal/api/attestationconfigapi/fetcher.go
  internal/attestation/measurements/BUILD.bazel
  internal/attestation/measurements/fetchmeasurements.go
  internal/attestation/measurements/fetchmeasurements_test.go
  terraform-provider-constellation/docs/data-sources/attestation.md
  terraform-provider-constellation/examples/data-sources/constellation_attestation/data-source.tf
  terraform-provider-constellation/go.mod
  terraform-provider-constellation/go.sum
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/attestation_data_source.go
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/provider.go
Labels: no changelog

#2656 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2658 helm: re-enable timeout flag
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/applyhelm.go
  internal/helm/action.go
  internal/helm/actionfactory.go
  internal/helm/actionfactory_test.go
  internal/helm/helm.go
  internal/helm/loader.go
  internal/helm/loader_test.go
  internal/helm/release.go
  internal/helm/versionlister.go
Labels: no changelog

#2662 cli: fix renamed flag for mini-constellation
  cli/internal/cmd/miniup.go
Labels: no changelog

#2648 rfc: trusted k8s images
  rfc/XXX-trusted-kubernetes-images.md
Labels: no changelog
