Repository edgelesssys/constellation, pull requests merged in 2023-06, with the labels that each got.

#1840 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#1849 ci: do not sign & upload debug image measurements
  .github/workflows/build-os-image.yml
Labels: no changelog

#1830 image: add aws_aws-sev-snp variant
  .github/workflows/build-os-image.yml
  image/Makefile
Labels: no changelog

#1837 todo responsibilities and cleanup
  .github/actions/build_cli/action.yml
  .github/actions/constellation_create/action.yml
  .github/actions/container_sbom/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image.yml
  3rdparty/bazel/com_github_google_go_tpm_tools/ms_tpm_20_ref.need
  bazel/oci/pin.bzl
  bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/rollback.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/helm/client.go
  cli/internal/kubernetes/upgrade.go
  cli/internal/terraform/terraform/openstack/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf
  cli/internal/terraform/variables.go
  debugd/internal/debugd/metadata/cloudprovider/cloudprovider.go
  docs/docs/workflows/sbom.md
  image/mkosi.conf.d/mkosi.conf
  internal/attestation/measurements/measurements.go
  internal/attestation/measurements/measurements_test.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/validation.go
  internal/file/file_test.go
  internal/kubernetes/kubectl/kubectl.go
  internal/sigstore/rekor_integration_test.go
  internal/versions/versions.go
  operators/constellation-node-operator/controllers/pendingnode_controller.go
  operators/constellation-node-operator/internal/cloud/azure/client/nodeimage_test.go
Labels: no changelog

#1836 config: sign Azure versions on upload & verify on fetch
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/recover_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  cli/internal/terraform/terraform/aws/.terraform.lock.hcl
  cli/internal/terraform/terraform/azure/.terraform.lock.hcl
  debugd/internal/cdbg/cmd/BUILD.bazel
  debugd/internal/cdbg/cmd/deploy.go
  e2e/internal/upgrade/BUILD.bazel
  e2e/internal/upgrade/upgrade_test.go
  go.mod
  go.sum
  hack/azure-snp-report-verify/BUILD.bazel
  hack/azure-snp-report-verify/verify.go
  hack/configapi/BUILD.bazel
  hack/configapi/cmd/BUILD.bazel
  hack/configapi/cmd/root.go
  hack/configapi/main.go
  hack/go.mod
  hack/go.sum
  internal/api/configapi/BUILD.bazel
  internal/api/configapi/repo.go
  internal/api/configapi/repo_test.go
  internal/api/fetcher/BUILD.bazel
  internal/api/fetcher/configapi.go
  internal/api/fetcher/configapi_test.go
  internal/api/fetcher/fetcher.go
  internal/api/versionsapi/cli/BUILD.bazel
  internal/api/versionsapi/cli/main.go
  internal/attestation/measurements/measurements.go
  internal/config/BUILD.bazel
  internal/config/azure.go
  internal/config/config.go
  internal/config/config_test.go
  internal/constants/constants.go
  internal/sigstore/BUILD.bazel
  internal/sigstore/sign.go
  internal/sigstore/sign_test.go
  internal/staticupload/BUILD.bazel
  internal/staticupload/get.go
  internal/staticupload/staticupload.go
  internal/staticupload/staticupload_test.go
Labels: feature

#1850 ci: remove setup-go action / disable cache where applicable
  .github/workflows/azure-snp-reporter.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/build-versionsapi-ci-image.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/test-tidy.yml
Labels: no changelog

#1855 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#1821 cli: Terraform upgrades maa patching
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/patch.go
  cli/internal/cloudcmd/patch_test.go
  cli/internal/terraform/terraform/azure/main.tf
  cli/internal/upgrade/BUILD.bazel
  cli/internal/upgrade/terraform.go
  cli/internal/upgrade/terraform_test.go
  e2e/internal/upgrade/BUILD.bazel
  e2e/internal/upgrade/upgrade_test.go
Labels: no changelog

#1839 ci: use aws s3 client that invalidates cloudfront cache
  hack/cli-k8s-compatibility/main.go
  hack/configapi/cmd/root.go
  image/upload/internal/cmd/aws.go
  image/upload/internal/cmd/azure.go
  image/upload/internal/cmd/flags.go
  image/upload/internal/cmd/gcp.go
  image/upload/internal/cmd/image.go
  image/upload/internal/cmd/info.go
  image/upload/internal/cmd/measurementsupload.go
  image/upload/internal/cmd/nop.go
  internal/api/attestationconfig/client/BUILD.bazel
  internal/api/attestationconfig/client/client.go
  internal/api/attestationconfig/client/client_test.go
  internal/api/client/BUILD.bazel
  internal/api/client/client.go
  internal/api/versions/cli/add.go
  internal/api/versions/cli/latest.go
  internal/api/versions/cli/list.go
  internal/api/versions/cli/rm.go
  internal/api/versions/client/client.go
  internal/osimage/archive/BUILD.bazel
  internal/osimage/archive/archive.go
  internal/osimage/imageinfo/BUILD.bazel
  internal/osimage/imageinfo/imageinfo.go
  internal/osimage/measurementsuploader/BUILD.bazel
  internal/osimage/measurementsuploader/measurementsuploader.go
  internal/staticupload/get.go
  internal/staticupload/staticupload.go
  internal/staticupload/staticupload_test.go
Labels: no changelog

#1856 ci: fix versionsapi cli container Dockerfile
  .github/actions/versionsapi/Dockerfile
Labels: no changelog

#1861 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#1862 cli: write target k8s version to config if new version is found on upgrade check
  cli/internal/cmd/upgradecheck.go
Labels: no changelog

#1780 e2e: asynchronously check constellation status
  e2e/internal/upgrade/upgrade_test.go
Labels: no changelog

#1865 docs: refine instructions for upgrade process
  docs/docs/workflows/upgrade.md
Labels: no changelog

#1864 cli: skip k8s upgrade in case of outdated version
  cli/internal/cmd/init.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/helm/client.go
  cli/internal/kubernetes/upgrade.go
  cli/internal/kubernetes/upgrade_test.go
  internal/config/BUILD.bazel
  internal/config/config_test.go
  internal/config/validation.go
  internal/versions/versions.go
Labels: no changelog

#1867 api: use correct error types in versions/cli
  internal/api/versions/cli/BUILD.bazel
  internal/api/versions/cli/add.go
  internal/api/versions/cli/list.go
  internal/api/versions/cli/rm.go
  internal/api/versions/client/BUILD.bazel
  internal/api/versions/client/client.go
Labels: no changelog

#1863 config: Azure SNP tool can delete specific version from attestation API
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/recover_test.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/cmd/verify_test.go
  hack/configapi/cmd/BUILD.bazel
  hack/configapi/cmd/delete.go
  hack/configapi/cmd/delete_test.go
  hack/configapi/cmd/root.go
  internal/api/attestationconfig/azure.go
  internal/api/attestationconfig/client/BUILD.bazel
  internal/api/attestationconfig/client/client.go
  internal/api/attestationconfig/client/client_test.go
  internal/api/attestationconfig/client/test/integration_test.go
  internal/api/attestationconfig/fetcher/fetcher.go
  internal/api/attestationconfig/fetcher/fetcher_test.go
  internal/api/client/client.go
  internal/config/config_test.go
  internal/sigstore/sign.go
  internal/staticupload/staticupload.go
Labels: no changelog

#1874 ci: select correct target version for upgrade e2e test in release pipeline
  .github/workflows/e2e-test-release.yml
  .github/workflows/release.yml
Labels: no changelog

#1873 cli: prevent tf apply drift when patching and re-applying existing tf deployment
  cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
Labels: no changelog

#1878 config: move all config types into file config.go
  internal/config/BUILD.bazel
  internal/config/azure.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/qemu.go
Labels: no changelog

#1870 staticupload: don't request empty invalidation
  internal/staticupload/staticupload.go
  internal/staticupload/staticupload_test.go
Labels: no changelog

#1872 fix: use new UploadAzureSEVSNP impl
  hack/configapi/cmd/root.go
  internal/api/attestationconfig/azure.go
  internal/api/attestationconfig/client/BUILD.bazel
  internal/api/attestationconfig/client/client.go
  internal/api/attestationconfig/fetcher/fetcher.go
  internal/api/attestationconfig/fetcher/fetcher_test.go
  internal/api/client/client.go
Labels: no changelog

#1868 image: choose unique AWS image names based on the attestation variant
  internal/osimage/aws/awsupload.go
Labels: no changelog

#1879 Add --insecure to config fetch-measurement
  .github/actions/e2e_verify/action.yml
  .github/workflows/build-os-image.yml
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/recover_test.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/cmd/verify_test.go
  docs/docs/reference/cli.md
Labels: no changelog

#1882 config: disable user-facing version fetch for Azure SEV SNP
  internal/attestation/azure/snp/validator_test.go
  internal/config/attestationversion.go
  internal/config/attestationversion_test.go
  internal/config/config.go
  internal/config/config_test.go
Labels: no changelog

#1877 ci: fix docker-login on macOS runner
  .github/actions/build_micro_service/action.yml
  .github/actions/container_registry_login/action.yml
  .github/actions/e2e_mini/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-gcp-guest-agent.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/release-cli.yml
Labels: no changelog

#1881 operators: cleanup placeholder nodeversion
  .github/workflows/e2e-upgrade.yml
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cmd/upgradeapply.go
  e2e/internal/upgrade/BUILD.bazel
  e2e/internal/upgrade/upgrade_test.go
  go.mod
  go.sum
  operators/constellation-node-operator/internal/cloud/fake/client/BUILD.bazel
  operators/constellation-node-operator/internal/cloud/fake/client/client.go
  operators/constellation-node-operator/internal/constants/constants.go
  operators/constellation-node-operator/internal/deploy/BUILD.bazel
  operators/constellation-node-operator/internal/deploy/deploy.go
Labels: no changelog

#1880 doc: VS code hint
  dev-docs/conventions.md
Labels: documentation, no changelog

#1895 misc: start v2.9.0-pre
  version.txt
Labels: no changelog

#1894 rfc: specify how to handle launchmeasurements
  rfc/attestation-config.md
Labels: no changelog

#1889 ci: do not manually clear measurements on verify e2e
  .github/actions/e2e_verify/action.yml
Labels: no changelog

#1893 local: fix mac issues in bazel
  3rdparty/bazel/com_github_google_go_tpm_tools/ms_tpm_20_ref.need
  3rdparty/bazel/com_github_google_go_tpm_tools/ms_tpm_20_ref.patch
  3rdparty/bazel/org_openssl/BUILD.bazel
  bazel/go/go_test.bzl
  bootstrapper/internal/diskencryption/BUILD.bazel
  csi/cryptmapper/BUILD.bazel
  disk-mapper/internal/setup/BUILD.bazel
  disk-mapper/internal/setup/interface.go
  disk-mapper/internal/setup/mount_cross.go
  disk-mapper/internal/setup/mount_linux.go
  disk-mapper/internal/setup/setup.go
  disk-mapper/internal/test/benchmark_test.go
  hack/qemu-metadata-api/server/BUILD.bazel
Labels: no changelog

#1891 terraform: update aws to v5.1.0
  cli/internal/terraform/terraform/aws/.terraform.lock.hcl
  cli/internal/terraform/terraform/aws/main.tf
  cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
  cli/internal/terraform/terraform/aws/modules/load_balancer_target/main.tf
  cli/internal/terraform/terraform/aws/modules/public_private_subnet/main.tf
  cli/internal/terraform/terraform/iam/aws/.terraform.lock.hcl
  cli/internal/terraform/terraform/iam/aws/main.tf
Labels: bug fix

#1903 deps: bump go patch version
  .github/actions/versionsapi/Dockerfile
  .github/workflows/azure-snp-reporter.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/build-os-image.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  WORKSPACE.bazel
  tools/pseudo_version_darwin_amd64.sha256
  tools/pseudo_version_darwin_arm64.sha256
  tools/pseudo_version_linux_amd64.sha256
  tools/pseudo_version_linux_arm64.sha256
Labels: dependencies, needs backport

#1905 ci: fix changelog generation
  .github/workflows/release-cli.yml
Labels: no changelog

#1899 config: enable azure snp version fetcher again + minimum age for latest version
  cli/internal/cmd/configfetchmeasurements_test.go
  hack/configapi/cmd/root.go
  internal/api/attestationconfigapi/azure.go
  internal/api/attestationconfigapi/client.go
  internal/api/attestationconfigapi/fetcher.go
  internal/api/attestationconfigapi/fetcher_test.go
  internal/attestation/azure/snp/validator_test.go
  internal/config/attestationversion.go
  internal/config/attestationversion_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/sigstore/verify.go
  rfc/attestation-config.md
Labels: feature

#1904 cli: hide --insecure of config fetch-measurements
  cli/internal/cmd/configfetchmeasurements.go
  docs/docs/reference/cli.md
Labels: no changelog

#1892 ci: migrate e2e lb test to bazel
  .github/actions/e2e_lb/action.yml
  .github/actions/setup_bazel/action.yml
  e2e/internal/lb/BUILD.bazel
  e2e/internal/lb/lb.go
  e2e/internal/lb/lb_test.go
Labels: no changelog

#1883 cdbg: make endpoint deployment failure more transparent
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/init.go
  debugd/internal/cdbg/cmd/BUILD.bazel
  debugd/internal/cdbg/cmd/deploy.go
  internal/grpc/grpclog/BUILD.bazel
  internal/grpc/grpclog/grpclog.go
  internal/grpc/grpclog/grpclog_test.go
  internal/grpc/grpclog/grplog.go
Labels: bug fix, no changelog

#1910 Update go-tpm-tools fork
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
Labels: dependencies, no changelog

#1911 config: fix parse azure version
  hack/configapi/cmd/root.go
  internal/api/attestationconfigapi/client.go
  internal/api/attestationconfigapi/fetcher.go
  internal/api/attestationconfigapi/fetcher_test.go
Labels: bug fix, no changelog

#1853 Correctly deploy the AWS CCM
  bootstrapper/internal/helm/helm.go
  bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  cli/internal/terraform/terraform/aws/main.tf
  cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
  debugd/internal/debugd/constants.go
  debugd/internal/debugd/metadata/scheduler.go
  internal/cloud/aws/aws.go
  internal/cloud/aws/aws_test.go
  internal/cloud/aws/logger.go
  internal/cloud/aws/logger_test.go
  internal/kubernetes/kubectl/kubectl.go
Labels: no changelog

#1927 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#1917 ci: explicitly add CLI signature as release artifact
  .github/workflows/release-cli.yml
  .github/workflows/release.yml
Labels: no changelog, needs backport

#1928 ci: replace katexochen with elchead in assignee list
  .github/actions/pick_assignee/action.yml
Labels: no changelog

#1930 fix: Azure SEV-SNP version always gets overwritten by latest API versions
  internal/config/BUILD.bazel
  internal/config/attestationversion.go
  internal/config/attestationversion_test.go
  internal/config/azure.go
  internal/config/config.go
  internal/config/config_test.go
Labels: bug fix, no changelog

#1931 ci: upgrade fromVersion in e2e-upgrade
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#1932 doc: add context to PR template
  .github/pull_request_template.md
Labels: no changelog

#1909 deps: upgrade to Fedora 38
  .github/workflows/build-os-image.yml
  bazel/container/Containerfile
  debugd/internal/debugd/logcollector/filebeat/Dockerfile
  debugd/internal/debugd/logcollector/logstash/Dockerfile
  image/Makefile
  image/README.md
  image/mkosi.conf.d/mkosi.conf
  image/mkosi.conf.d/mkosi.gcp.conf
  rpm/BUILD.bazel
  rpm/repo.yaml
  rpm/rpms.bzl
  tools/dnf-init.sh
  tools/dnf-tree.sh
Labels: dependencies

#1937 deps: upgrade sonobuoy to v0.56.17
  .github/actions/e2e_sonobuoy/action.yml
Labels: dependencies

#1939 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#1941 terraform: gcp node groups
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cloudcmd/create.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/terraform/BUILD.bazel
  cli/internal/terraform/terraform/gcp/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/gcp/modules/loadbalancer/main.tf
  cli/internal/terraform/terraform/gcp/modules/loadbalancer/variables.tf
  cli/internal/terraform/terraform/gcp/variables.tf
  cli/internal/terraform/terraform_test.go
  cli/internal/terraform/variables.go
  cli/internal/terraform/variables_test.go
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
Labels: no changelog

#1933 cli: improve user warning / information
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/create.go
  internal/config/config.go
  internal/config/config_test.go
Labels: no changelog

#1912 dev-docs: refactor and add information for newbies
  .github/pull_request_template.md
  CONTRIBUTING.md
  debugd/README.md
  dev-docs/README.md
  dev-docs/conventions.md
  dev-docs/howto/longhorn.md
  dev-docs/workflows/bazel.md
  dev-docs/workflows/build-develop-deploy.md
  dev-docs/workflows/build-test-run.md
  dev-docs/workflows/create-debug-cluster.md
  dev-docs/workflows/dev-setup.md
  dev-docs/workflows/pull-request.md
  dev-docs/workflows/testing.md
  dev-docs/workflows/upgrade-kubernetes.md
  dev-docs/workflows/verify-cluster.md
Labels: no changelog

#1942 cli: dry-run Terraform migrations on `upgrade check`
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/upgrade/terraform.go
  cli/internal/upgrade/terraform_test.go
Labels: no changelog

#1943 cloud: fix discovery of GCP nodes across zones
  internal/cloud/gcp/gcp.go
  internal/cloud/gcp/gcp_test.go
  internal/cloud/gcp/interface.go
  internal/cloud/gcp/wrappers.go
Labels: no changelog

#1946 ci: improve pr template
  .github/pull_request_template.md
Labels: no changelog

#1953 ci: run cdbg with debug verbosity
  .github/actions/constellation_create/action.yml
Labels: no changelog

#1859 ci: Windows cli tests
  .github/actions/build_cli/action.yml
  .github/workflows/e2e-windows.yml
Labels: no changelog

#1916 attestation: add SNP-based attestation for aws-sev-snp
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cloudcmd/create.go
  cli/internal/cmd/upgradeapply.go
  docs/docs/reference/cli.md
  go.mod
  go.sum
  internal/attestation/aws/snp/BUILD.bazel
  internal/attestation/aws/snp/errors.go
  internal/attestation/aws/snp/issuer.go
  internal/attestation/aws/snp/issuer_test.go
  internal/attestation/aws/snp/snp.go
  internal/attestation/aws/snp/validator.go
  internal/attestation/aws/snp/validator_test.go
  internal/attestation/variant/variant.go
  internal/attestation/vtpm/BUILD.bazel
  internal/attestation/vtpm/attestation.go
  internal/attestation/vtpm/attestation_test.go
  internal/config/attestation_test.go
  internal/config/azure.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/constants/constants.go
Labels: feature

#1955 terraform: azure node groups
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/create.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/terraform/BUILD.bazel
  cli/internal/terraform/terraform/azure/main.tf
  cli/internal/terraform/terraform/azure/modules/scale_set/main.tf
  cli/internal/terraform/terraform/azure/modules/scale_set/variables.tf
  cli/internal/terraform/terraform/azure/variables.tf
  cli/internal/terraform/variables.go
  cli/internal/terraform/variables_test.go
  internal/role/role.go
Labels: no changelog

#1957 attestation: revert awsevsnp attestation to nitrotpm
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cloudcmd/create.go
  cli/internal/cmd/upgradeapply.go
  docs/docs/reference/cli.md
  go.mod
  go.sum
  internal/attestation/aws/snp/BUILD.bazel
  internal/attestation/aws/snp/errors.go
  internal/attestation/aws/snp/issuer.go
  internal/attestation/aws/snp/issuer_test.go
  internal/attestation/aws/snp/snp.go
  internal/attestation/aws/snp/validator.go
  internal/attestation/aws/snp/validator_test.go
  internal/attestation/variant/variant.go
  internal/attestation/vtpm/BUILD.bazel
  internal/attestation/vtpm/attestation.go
  internal/attestation/vtpm/attestation_test.go
  internal/config/attestation_test.go
  internal/config/azure.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/constants/constants.go
Labels: no changelog

#1960 terraform: always use uniform role names
  cli/internal/cloudcmd/create.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/upgradeapply.go
  cli/internal/terraform/terraform/aws/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/azure/modules/scale_set/main.tf
  cli/internal/terraform/terraform/gcp/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/gcp/variables.tf
  cli/internal/terraform/terraform/openstack/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/variables.tf
  cli/internal/terraform/variables_test.go
Labels: no changelog

#1914 ci: add automated tests for reproducible builds
  .github/actions/setup_bazel/action.yml
  .github/workflows/reproducible-builds.yml
  bazel/toolchains/ci_deps.bzl
Labels: no changelog

#1959 attestation: docs and config changes for SNP attestation
  docs/docs/getting-started/first-steps.md
  docs/docs/workflows/config.md
  internal/config/attestation_test.go
  internal/config/config.go
  internal/config/config_doc.go
Labels: no changelog

#1965 fix: small formating/spelling issues
  cli/internal/cmd/configmigrate.go
  internal/config/config.go
Labels: no changelog

#1968 Use term "attestation variant" consistently
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  docs/docs/workflows/config.md
  internal/api/attestationconfigapi/client.go
  internal/attestation/variant/variant.go
Labels: no changelog

#1963 config: validate instance type for aws SNP based on attestation variant
  cli/internal/cmd/configinstancetypes.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/instancetypes/aws.go
  internal/config/validation.go
Labels: no changelog

#1970 cli: remove Terraform targets
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/terraform/terraform.go
  cli/internal/upgrade/terraform.go
  cli/internal/upgrade/terraform_test.go
Labels: no changelog

#1971 deps: downgrade libvirt to 8.10.0
  rpm/BUILD.bazel
  rpm/rpms.bzl
Labels: no changelog

#1975 config: improve usage and meaning of validate
  cli/internal/cmd/miniup.go
  cli/internal/featureset/featureset.go
  cli/internal/featureset/featureset_enterprise.go
  cli/internal/featureset/featureset_oss.go
  internal/config/config.go
  internal/config/config_test.go
Labels: no changelog

#1961 terraform: QEMU node groups
  cli/internal/cloudcmd/create.go
  cli/internal/terraform/BUILD.bazel
  cli/internal/terraform/terraform/qemu/.terraform.lock.hcl
  cli/internal/terraform/terraform/qemu/main.tf
  cli/internal/terraform/terraform/qemu/modules/instance_group/main.tf
  cli/internal/terraform/terraform/qemu/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/qemu/outputs.tf
  cli/internal/terraform/terraform/qemu/variables.tf
  cli/internal/terraform/terraform_test.go
  cli/internal/terraform/variables.go
  cli/internal/terraform/variables_test.go
Labels: no changelog

#1897 cli: change generate-config flag to update-config flag
  .github/actions/constellation_iam_create/action.yml
  .github/workflows/e2e-windows.yml
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/iamcreate_test.go
  cli/internal/cmd/upgradecheck.go
  docs/docs/getting-started/first-steps.md
  docs/docs/reference/cli.md
  docs/docs/workflows/config.md
  docs/docs/workflows/upgrade.md
  docs/screencasts/docker/configure-cluster.expect
  docs/screencasts/generate-readme-svg.sh
  rfc/updates.md
Labels: breaking change

#1984 ci: conditionally use generate-config flag for old versions of Constellation CLI
  .github/actions/constellation_iam_create/action.yml
Labels: no changelog

#1988 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#1974 docs: document aws encrypted storage
  docs/docs/workflows/storage.md
Labels: no changelog

#1982 ci: add miniconstellation to e2e weekly
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#1989 terraform: instance_count => initial_count
  cli/internal/cloudcmd/create.go
  cli/internal/terraform/terraform/aws/main.tf
  cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
  cli/internal/terraform/terraform/aws/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/aws/variables.tf
  cli/internal/terraform/terraform/azure/main.tf
  cli/internal/terraform/terraform/azure/modules/scale_set/main.tf
  cli/internal/terraform/terraform/azure/modules/scale_set/variables.tf
  cli/internal/terraform/terraform/azure/variables.tf
  cli/internal/terraform/terraform/gcp/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/openstack/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/qemu/main.tf
  cli/internal/terraform/terraform/qemu/variables.tf
  cli/internal/terraform/variables.go
  cli/internal/terraform/variables_test.go
Labels: no changelog

#1990 docs: update "feature status of clouds" regarding current AWS SNP offering
  docs/docs/overview/clouds.md
  docs/versioned_docs/version-2.8/overview/clouds.md
Labels: no changelog

#1977 bootstraper: delete helm chart on installation failure before retrying installation
  bootstrapper/internal/helm/helm.go
  cli/internal/helm/loader.go
  internal/deploy/helm/helm.go
Labels: bug fix

#1992 helm: fix upgrade command skipping all service upgrades
  cli/internal/cmd/upgradeapply.go
  cli/internal/helm/client.go
  cli/internal/helm/client_test.go
  cli/internal/kubernetes/upgrade.go
  cli/internal/kubernetes/upgrade_test.go
  internal/compatibility/compatibility.go
  internal/config/config.go
  internal/config/config_test.go
  internal/staticupload/staticupload.go
  internal/staticupload/staticupload_test.go
Labels: no changelog

#1983 terraform: use single zone loadbalancer frontend on AWS
  cli/internal/terraform/terraform/aws/main.tf
  cli/internal/terraform/terraform/aws/modules/public_private_subnet/main.tf
  internal/cloud/aws/aws.go
Labels: no changelog
