Repository edgelesssys/constellation, pull requests merged in 2023-07, with the labels that each got.

#1995 bootstrapper: install internal-config cm before constellation-services
  bootstrapper/internal/kubernetes/kubernetes.go
Labels: no changelog

#1997 cli: fix duplicate backup creation during `upgrade apply`
  .github/actions/build_cli/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-upgrade.yml
  cli/internal/helm/backup.go
  cli/internal/helm/client.go
  cli/internal/helm/client_test.go
  e2e/internal/upgrade/BUILD.bazel
  e2e/internal/upgrade/image.go
  e2e/internal/upgrade/upgrade_test.go
Labels: no changelog

#1998 deps: upgrade AWS CSI driver to v1.1.1
  cli/internal/helm/charts/edgeless/constellation-services/charts/aws-csi-driver/values.yaml
  cli/internal/helm/update-csi-charts.sh
Labels: no changelog

#1913 config: iam create aws check zone contains availability zone
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/iamcreate_test.go
  docs/docs/workflows/config.md
  internal/config/config.go
  internal/config/config_test.go
  internal/config/validation.go
Labels: no changelog

#2001 bootstrapper: use atomics in nodelock
  bootstrapper/internal/nodelock/BUILD.bazel
  bootstrapper/internal/nodelock/nodelock.go
  bootstrapper/internal/nodelock/nodelock_test.go
Labels: no changelog

#2019 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2012 diskmapper: fix zap.Error without err
  disk-mapper/cmd/main.go
Labels: bug fix, no changelog, needs backport

#2020 bazel: rewrite pseudo-version stamping in bash
  .github/workflows/pseudo-version-freshness.yml
  .gitignore
  bazel/ci/BUILD.bazel
  hack/go.mod
  hack/go.sum
  hack/pseudo-version/BUILD.bazel
  hack/pseudo-version/check/BUILD.bazel
  hack/pseudo-version/check/check.go
  hack/pseudo-version/pseudo_version_tool_freshness.sh.in
  tools/pseudo_version_darwin_amd64.sha256
  tools/pseudo_version_darwin_arm64.sha256
  tools/pseudo_version_linux_amd64.sha256
  tools/pseudo_version_linux_arm64.sha256
  tools/workspace_status.sh
Labels: no changelog

#2021 feat: get notified in Teams on E2E test failure ticket
  .github/actions/notify_failure/action.yml
  .github/teams_payload_template.json
Labels: no changelog

#1994 bazel: fill microservice version on `devbuild` target
  WORKSPACE.bazel
  bazel/devbuild/BUILD.bazel
  bazel/devbuild/prepare_developer_workspace.sh.in
  bazel/sh/def.bzl
Labels: no changelog

#2054 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2044 bazel: mount host's Docker config into builder container
  bazel/container/container.sh
Labels: no changelog

#2055 ci: fix broken e2e notify failure
  .github/actions/notify_failure/action.yml
Labels: no changelog

#2058 ci: build all streams on release
  .github/workflows/release.yml
Labels: no changelog

#2068 deps: ignore updates to CSI containers in renovate
  renovate.json
Labels: no changelog

#1999 docs: how to set up MiniConstellation on Azure
  dev-docs/miniconstellation/README.md
  dev-docs/miniconstellation/azure-terraform/.terraform.lock.hcl
  dev-docs/miniconstellation/azure-terraform/cloud-init.yaml
  dev-docs/miniconstellation/azure-terraform/create-vm.sh
  dev-docs/miniconstellation/azure-terraform/main.tf
  dev-docs/miniconstellation/azure-terraform/output.tf
  dev-docs/miniconstellation/azure-terraform/variables.tf
  dev-docs/miniconstellation/setup-miniconstellation.sh
  docs/docs/getting-started/first-steps-local.md
Labels: no changelog

#2069 docs: suggest changes for first-steps-local
  docs/docs/getting-started/first-steps-local.md
Labels: no changelog

#2056 feat: `status` shows attestation config
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/status.go
  cli/internal/cmd/status_test.go
  cli/internal/helm/loader_test.go
  cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/configmap.yaml
  cli/internal/kubernetes/upgrade.go
  cli/internal/kubernetes/upgrade_test.go
  internal/config/config.go
  internal/config/config_test.go
Labels: feature

#2061 cli: add "--skip-helm-wait" flag
  bootstrapper/internal/helm/helm.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/init.go
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  docs/docs/reference/cli.md
  internal/deploy/helm/helm.go
Labels: no changelog

#2075 ci: add constellation-windows-amd64.exe to release artifacts uploaded to GitHub
  .github/actions/build_cli/action.yml
  .github/workflows/release-cli.yml
Labels: feature

#2076 deps: bump go-secure-stdlib/awsutil
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
Labels: no changelog

#1991 ci: update aws asg resource selector
  .github/actions/constellation_create/aws-logs.sh
Labels: no changelog

#1985 rfc: canonical endpoint / custom dns
  rfc/canonical-endpoint-dns.md
Labels: no changelog

#2079 cli: remove old migrations
  cli/internal/cmd/upgradeapply.go
  cli/internal/helm/client.go
  cli/internal/kubernetes/BUILD.bazel
  cli/internal/kubernetes/upgrade.go
  internal/kubernetes/kubectl/kubectl.go
Labels: no changelog

#2081 cli: fix broken "constellation mini up" due to incompatible terraform json
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cmd/miniup.go
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
Labels: no changelog

#2086 ci: use 2.8 as fromVersion in release upgrade test
  .github/workflows/e2e-test-release.yml
Labels: no changelog

#2093 deps: update to Go v1.20.6
  .github/workflows/azure-snp-reporter.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/build-os-image.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  WORKSPACE.bazel
Labels: dependencies, needs backport

#2091 ci: use us-east-2 for e2e tests
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_test/action.yml
Labels: no changelog

#2094 cli: allow upgrade if desired attestation config == actual config
  cli/internal/cmd/upgradeapply.go
Labels: no changelog

#2095 cli: allow helm upgrades with old k8s patch version
  cli/internal/helm/client.go
  internal/versions/versions.go
Labels: no changelog

#2088 config: make deployCSIDriver backwards compatible
  internal/config/config.go
  internal/config/config_doc.go
Labels: no changelog

#2097 operators: correctly update launch template default version on AWS image upgrade
  operators/constellation-node-operator/internal/cloud/aws/client/scalinggroup.go
Labels: no changelog

#2099 ci: replicate Azure images to Southeast Asia
  internal/osimage/azure/azureupload.go
Labels: no changelog

#2100 ci: separate PCR0 value for aws-sev-snp variant
  .github/workflows/build-os-image.yml
Labels: no changelog

#2101 ci: fix resource selection for serial log downloading
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_create/aws-logs.sh
  .github/actions/constellation_create/az-logs.sh
  .github/actions/constellation_create/gcp-logs.sh
Labels: no changelog

#2096 docs: mention need to delete variants
  dev-docs/workflows/release.md
Labels: no changelog

#2084 ci: combine node count inputs into one
  .github/workflows/e2e-test-manual.yml
Labels: no changelog

#2087 ci: update failure tasks
  .github/failure_project_template.md
Labels: no changelog

#2043 cryptsetup: unify code
  bootstrapper/cmd/bootstrapper/run.go
  bootstrapper/internal/diskencryption/BUILD.bazel
  bootstrapper/internal/diskencryption/diskencryption.go
  bootstrapper/internal/diskencryption/diskencryption_cgo.go
  bootstrapper/internal/diskencryption/diskencryption_cross.go
  bootstrapper/internal/diskencryption/diskencryption_test.go
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/initserver/initserver_test.go
  bootstrapper/internal/joinclient/joinclient.go
  bootstrapper/internal/joinclient/joinclient_test.go
  csi/cryptmapper/BUILD.bazel
  csi/cryptmapper/cryptmapper.go
  csi/cryptmapper/cryptmapper_cgo.go
  csi/cryptmapper/cryptmapper_cross.go
  csi/cryptmapper/cryptmapper_test.go
  csi/test/mount_integration_test.go
  disk-mapper/cmd/BUILD.bazel
  disk-mapper/cmd/main.go
  disk-mapper/internal/diskencryption/BUILD.bazel
  disk-mapper/internal/diskencryption/diskencryption.go
  disk-mapper/internal/mapper/cryptdevice.go
  disk-mapper/internal/mapper/mapper.go
  disk-mapper/internal/mapper/mapper_cgo.go
  disk-mapper/internal/mapper/mapper_cross.go
  disk-mapper/internal/setup/interface.go
  disk-mapper/internal/setup/setup.go
  disk-mapper/internal/setup/setup_test.go
  disk-mapper/internal/test/benchmark_test.go
  disk-mapper/internal/test/integration_test.go
  internal/cryptsetup/BUILD.bazel
  internal/cryptsetup/crypsetup_cross.go
  internal/cryptsetup/cryptsetup.go
  internal/cryptsetup/cryptsetup_cgo.go
  internal/cryptsetup/cryptsetup_cross.go
Labels: no changelog

#2114 cli: remove unused `file.Handler`
  cli/internal/cmd/upgradeapply.go
Labels: no changelog

#2113 cli: set Azure ConfidentialVM option in terraform vars when migrating
  cli/internal/cmd/upgradeapply.go
Labels: bug fix, needs backport

#2112 image: always copy amazon ena driver into initrd
  image/mkosi.skeleton/etc/dracut.conf.d/aws.conf
Labels: no changelog

#2115 image: use AWS linux kernel for AWS images to fix deadlock
  image/Makefile
  image/README.md
  image/mkosi.conf.d/mkosi.aws.conf
Labels: bug fix

#2083 disk-mapper: set LUKS2 token to allow reusing unintialized state disks
  bazel/toolchains/go_module_deps.bzl
  bootstrapper/internal/diskencryption/diskencryption.go
  bootstrapper/internal/diskencryption/diskencryption_test.go
  disk-mapper/cmd/main.go
  disk-mapper/internal/diskencryption/diskencryption.go
  disk-mapper/internal/setup/setup_test.go
  disk-mapper/internal/test/integration_test.go
  go.mod
  go.sum
  internal/cryptsetup/cryptsetup.go
Labels: feature

#2116 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2117 cli: do not recreate LB IP during 2.9 upgrade on Azure
  cli/internal/terraform/terraform/azure/main.tf
Labels: bug fix, needs backport

#2118 image: synchronize time via ntp
  image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset
  image/mkosi.skeleton/usr/lib/systemd/timesyncd.conf.d/constellation.conf
Labels: bug fix, needs backport

#2121 cli: print supported k8s versions on error
  cli/internal/cmd/init.go
  internal/versions/versions.go
Labels: no changelog

#2119 cli: unify terraform variable creation
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cloudcmd/terraform.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/terraform/variables.go
  cli/internal/terraform/variables_test.go
  internal/constants/constants.go
  operators/constellation-node-operator/internal/cloud/aws/client/BUILD.bazel
  operators/constellation-node-operator/internal/cloud/aws/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/aws/client/scalinggroup_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/BUILD.bazel
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/BUILD.bazel
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup_test.go
Labels: no changelog

#2123 upgrade: retry when node image update fails due to conflict error
  cli/internal/kubernetes/BUILD.bazel
  cli/internal/kubernetes/upgrade.go
  cli/internal/kubernetes/upgrade_test.go
  go.mod
Labels: bug fix

#2127 aws: fix get version error
  cli/internal/helm/client.go
Labels: no changelog

#2129 bootstrapper: refactor coredns and cilium setup
  bootstrapper/internal/kubernetes/BUILD.bazel
  bootstrapper/internal/kubernetes/ciliuminstallation.go
  bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  internal/kubernetes/kubectl/kubectl.go
Labels: no changelog

#2131 cli: only install aws-lb and csi charts conditionally
  cli/internal/helm/client.go
Labels: no changelog

#2138 cli: fix add csi chart only conditionally
  cli/internal/helm/client.go
Labels: no changelog

#2137 bazel: fix container versioning
  .github/workflows/build-bazel-container.yml
  bazel/container/container.sh
Labels: no changelog

#2141 api: remove empty files
  internal/api/attestationconfig/BUILD.bazel
  internal/api/attestationconfig/client/BUILD.bazel
Labels: no changelog

#1962 ci: parse ovmf binaries from metadata
  .github/workflows/aws-snp-launchmeasurement.yml
Labels: no changelog

#2128 cli: output CSI driver versions on `status`
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/status.go
  cli/internal/cmd/status_test.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/client.go
  cli/internal/helm/loader.go
  cli/internal/helm/serviceversion.go
Labels: feature

#2136 cli: install helm charts in cli instead of bootstrapper
  bootstrapper/cmd/bootstrapper/main.go
  bootstrapper/cmd/bootstrapper/test.go
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/initserver/initserver_test.go
  bootstrapper/internal/kubernetes/BUILD.bazel
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cloudcmd/iam.go
  cli/internal/cloudcmd/iam_test.go
  cli/internal/cloudcmd/rollback.go
  cli/internal/cloudcmd/terminate.go
  cli/internal/cloudcmd/terminate_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/tfmigrationclient.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/helminstaller.go
  cli/internal/helm/loader.go
  cli/internal/helm/setup.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform/azure/main.tf
  cli/internal/terraform/terraform/azure/outputs.tf
  cli/internal/terraform/terraform/gcp/outputs.tf
  cli/internal/terraform/terraform_test.go
  cli/internal/upgrade/terraform.go
  cli/internal/upgrade/terraform_test.go
  internal/cloud/azure/azure.go
  internal/cloud/azure/azure_test.go
  internal/cloud/azureshared/appcredentials.go
  internal/cloud/azureshared/appcredentials_test.go
  internal/deploy/helm/BUILD.bazel
  internal/deploy/helm/install.go
Labels: no changelog
