Repository edgelesssys/constellation, pull requests merged in 2023-01, with the labels that each got.

#851 bump microservice versions
  internal/versions/versions.go
Labels: no-changelog

#839 upgrade: support Kubernetes components
  bootstrapper/internal/kubernetes/kubernetes.go
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/daemonset.yaml
  cli/internal/helm/charts/edgeless/constellation-services/values.yaml
  cli/internal/helm/charts/edgeless/operators/charts/constellation-operator/crds/joiningnode-crd.yaml
  cli/internal/helm/charts/edgeless/operators/charts/constellation-operator/crds/nodeimage-crd.yaml
  cli/internal/helm/charts/edgeless/operators/charts/constellation-operator/templates/manager-rbac.yaml
  cli/internal/helm/loader.go
  cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/daemonset.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/join-service/templates/daemonset.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  cli/internal/helm/testdata/QEMU/constellation-services/charts/join-service/templates/clusterrole.yaml
  cli/internal/helm/testdata/QEMU/constellation-services/charts/join-service/templates/daemonset.yaml
  internal/constants/constants.go
  joinservice/cmd/main.go
  joinservice/internal/kubernetes/kubernetes.go
  joinservice/internal/server/server.go
  joinservice/internal/server/server_test.go
  operators/constellation-node-operator/PROJECT
  operators/constellation-node-operator/README.md
  operators/constellation-node-operator/api/v1alpha1/joiningnodes_types.go
  operators/constellation-node-operator/api/v1alpha1/nodeversion_types.go
  operators/constellation-node-operator/api/v1alpha1/scalinggroup_types.go
  operators/constellation-node-operator/api/v1alpha1/zz_generated.deepcopy.go
  operators/constellation-node-operator/config/crd/bases/update.edgeless.systems_joiningnodes.yaml
  operators/constellation-node-operator/config/crd/bases/update.edgeless.systems_nodeversions.yaml
  operators/constellation-node-operator/config/crd/bases/update.edgeless.systems_scalinggroups.yaml
  operators/constellation-node-operator/config/crd/kustomization.yaml
  operators/constellation-node-operator/config/crd/patches/cainjection_in_nodeversions.yaml
  operators/constellation-node-operator/config/crd/patches/webhook_in_nodeversions.yaml
  operators/constellation-node-operator/config/manager/kustomization.yaml
  operators/constellation-node-operator/config/manifests/bases/node-operator.clusterserviceversion.yaml
  operators/constellation-node-operator/config/rbac/nodeimage_editor_role.yaml
  operators/constellation-node-operator/config/rbac/nodeimage_viewer_role.yaml
  operators/constellation-node-operator/config/rbac/role.yaml
  operators/constellation-node-operator/config/samples/kustomization.yaml
  operators/constellation-node-operator/config/samples/update_v1alpha1_nodeversion.yaml
  operators/constellation-node-operator/controllers/joiningnode_controller.go
  operators/constellation-node-operator/controllers/joiningnode_controller_env_test.go
  operators/constellation-node-operator/controllers/nodeversion_controller.go
  operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go
  operators/constellation-node-operator/controllers/nodeversion_controller_test.go
  operators/constellation-node-operator/controllers/nodeversion_watches.go
  operators/constellation-node-operator/controllers/nodeversion_watches_test.go
  operators/constellation-node-operator/controllers/scalinggroup_controller.go
  operators/constellation-node-operator/controllers/scalinggroup_controller_env_test.go
  operators/constellation-node-operator/controllers/suite_test.go
  operators/constellation-node-operator/internal/constants/constants.go
  operators/constellation-node-operator/internal/deploy/deploy.go
  operators/constellation-node-operator/internal/deploy/deploy_test.go
  operators/constellation-node-operator/main.go
  rfc/updates.md
Labels: no-changelog

#831 deps: update AWS cloud controller manager
  internal/versions/versions.go
Labels: dependencies

#850 Fix failing e2e test for lb
  .github/actions/e2e_lb/action.yml
  e2e/internal/lb/lb_test.go
Labels: bug-fix, no-changelog

#809 cli: add verbose debug logging
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/recover_test.go
  cli/internal/cmd/upgradeplan.go
  cli/internal/cmd/upgradeplan_test.go
Labels: feature

#855 cli: deactivate spinner for debug logging
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/iamcreateaws_test.go
  cli/internal/cmd/iamcreateazure_test.go
  cli/internal/cmd/iamcreategcp_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/spinner.go
  cli/internal/cmd/terminate_test.go
Labels: no-changelog

#857 ci: ignore ntia.gov and twitter checking links
  .lycheeignore
Labels: no-changelog

#859 versionsapi: fix semver dependency
  go.mod
  internal/versionsapi/cli/list.go
Labels: bug-fix, no-changelog

#860 ci: fix rebuild loop of microservice images
  .github/workflows/build-joinservice-image.yml
  .github/workflows/build-kms-image.yml
  .github/workflows/build-qemu-metadata-image.yml
  .github/workflows/build-verification-service.yml
Labels: dependencies, bug-fix, no-changelog

#858 operator: always create initial resources
  operators/constellation-node-operator/internal/cloud/azure/client/api.go
  operators/constellation-node-operator/internal/cloud/azure/client/autoscaler.go
  operators/constellation-node-operator/internal/cloud/azure/client/client.go
  operators/constellation-node-operator/internal/cloud/azure/client/client_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/config.go
  operators/constellation-node-operator/internal/cloud/azure/client/config_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/instanceview.go
  operators/constellation-node-operator/internal/cloud/azure/client/instanceview_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/nodeimage.go
  operators/constellation-node-operator/internal/cloud/azure/client/nodeimage_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/pendingnode.go
  operators/constellation-node-operator/internal/cloud/azure/client/pendingnode_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/providerid.go
  operators/constellation-node-operator/internal/cloud/azure/client/providerid_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/vmss.go
  operators/constellation-node-operator/internal/cloud/azure/client/vmss_test.go
  operators/constellation-node-operator/internal/cloud/fake/client/client.go
  operators/constellation-node-operator/internal/cloud/gcp/client/api.go
  operators/constellation-node-operator/internal/cloud/gcp/client/autocaler.go
  operators/constellation-node-operator/internal/cloud/gcp/client/client.go
  operators/constellation-node-operator/internal/cloud/gcp/client/client_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/config.go
  operators/constellation-node-operator/internal/cloud/gcp/client/config_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/disks.go
  operators/constellation-node-operator/internal/cloud/gcp/client/disks_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/gcpwrappers.go
  operators/constellation-node-operator/internal/cloud/gcp/client/instancegroupmanagers.go
  operators/constellation-node-operator/internal/cloud/gcp/client/instancegroupmanagers_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/instancetemplate.go
  operators/constellation-node-operator/internal/cloud/gcp/client/instancetemplate_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/metadata.go
  operators/constellation-node-operator/internal/cloud/gcp/client/metadata_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/nodeimage.go
  operators/constellation-node-operator/internal/cloud/gcp/client/nodeimage_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/pendingnode.go
  operators/constellation-node-operator/internal/cloud/gcp/client/pendingnode_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/project.go
  operators/constellation-node-operator/internal/cloud/gcp/client/project_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/providerid.go
  operators/constellation-node-operator/internal/cloud/gcp/client/providerid_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup_test.go
  operators/constellation-node-operator/internal/deploy/deploy.go
  operators/constellation-node-operator/internal/deploy/deploy_test.go
  operators/constellation-node-operator/internal/deploy/imageinfo.go
  operators/constellation-node-operator/internal/deploy/imageinfo_test.go
  operators/constellation-node-operator/main.go
Labels: bug-fix, no-changelog

#856 versionsapi: change image path
  .github/workflows/build-os-image.yml
  .github/workflows/generate-measurements.yml
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  internal/versionsapi/client/client.go
  internal/versionsapi/imageinfo.go
  internal/versionsapi/imageinfo_test.go
  internal/versionsapi/version.go
  internal/versionsapi/version_test.go
  rfc/apis.md
  rfc/image-api.md
Labels: no-changelog

#862 Downgrade azure kernel to 5.19.4
  image/Makefile
  image/mkosi.conf.d/mkosi.conf
  image/mkosi.files/mkosi.azure.conf
  image/mkosi.files/mkosi.gcp.conf
Labels: bug-fix, no-changelog

#864 deps: fix kas-network-proxy registry prefix
  renovate.json
Labels: no-changelog

#868 ci: increase verbosity of load balancer e2e test
  .github/actions/e2e_lb/lb.yml
  e2e/internal/lb/lb_test.go
Labels: no-changelog

#878 go mod tidy
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
Labels: no-changelog

#863 deps: upgrade AWS cloud controller manager
  internal/versions/versions.go
Labels: no-changelog

#881 versionsapi: replace shortname pkg
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  internal/shortname/shortname.go
  internal/shortname/shortname_test.go
  internal/versionsapi/version.go
  internal/versionsapi/version_test.go
Labels: no-changelog

#867 renovate: don't group k8s contstrained versions
  renovate.json
Labels: no-changelog

#887 deps: upgrade Azure sdk
  go.mod
  go.sum
  hack/build-manifest/azure/client.go
  hack/go.mod
  hack/go.sum
  internal/cloud/azure/cloud.go
  internal/cloud/azure/cloud_test.go
  internal/cloud/azure/interface.go
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
  operators/constellation-node-operator/internal/cloud/azure/client/api.go
  operators/constellation-node-operator/internal/cloud/azure/client/client.go
  operators/constellation-node-operator/internal/cloud/azure/client/client_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/instanceview.go
  operators/constellation-node-operator/internal/cloud/azure/client/instanceview_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/nodeimage.go
  operators/constellation-node-operator/internal/cloud/azure/client/nodeimage_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/pendingnode_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup_test.go
Labels: no-changelog

#875 AB#2564 add e2e test for constellation verify
  .github/actions/constellation_verify/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-weekly.yml
Labels: no-changelog

#897 hack: move terraform readmes into cli
  .github/docs/terraform.md
  cli/internal/terraform/terraform/iam/aws/README.md
  cli/internal/terraform/terraform/iam/azure/README.md
  cli/internal/terraform/terraform/iam/gcp/README.md
Labels: no-changelog

#890 devdocs: pr title conventions
  .github/docs/conventions.md
Labels: no-changelog

#900 hack: remove build-manifest
  .github/docs/development.md
  .github/workflows/release-cli.yml
  hack/build-manifest/README.md
  hack/build-manifest/azure/client.go
  hack/build-manifest/azure/options.go
  hack/build-manifest/gcp/client.go
  hack/build-manifest/gcp/options.go
  hack/build-manifest/gcp/options_test.go
  hack/build-manifest/main.go
  hack/build-manifest/manifest.go
  hack/go.mod
  hack/go.sum
Labels: no-changelog

#913 ci: add purge branch workflow
  .github/workflows/purge-branch.yml
  .github/workflows/versionsapi.yml
Labels: no-changelog

#916 ci: add missing secrets to purge branch workflow
  .github/workflows/purge-branch.yml
Labels: no-changelog

#917 ci: fix versionsapi workflow remove cmd
  .github/workflows/purge-branch.yml
  .github/workflows/versionsapi.yml
Labels: no-changelog

#906 Add codeowners
  CODEOWNERS
Labels: no-changelog

#899 devdocs: documentation of logging conventions
  dev-docs/conventions.md
Labels: no-changelog

#931 versionsapi: log aws region
  internal/versionsapi/cli/rm.go
Labels: no-changelog

#922 deps: update and pin github.com/katexochen/sh
  .github/workflows/test-shellcheck.yml
  .github/workflows/test-shellfmt.yml
Labels: dependencies

#935 rfc: mention required IAM secrets for recovery in eKMS rfc
  rfc/external-kms.md
Labels: no-changelog

#933 ci: join macos with normal tests
  .github/workflows/e2e-test-manual-macos.yml
  .github/workflows/e2e-test-manual.yml
Labels: no-changelog

#932 versions: repair hash generation
  go.mod
  internal/versions/hash-generator/generate.go
  internal/versions/hash-generator/generate_test.go
  internal/versions/versions.go
Labels: no-changelog

#939 upgrade: fix broken reference from constellation-os to constellation-version
  cli/internal/cloudcmd/upgrade.go
  internal/kubernetes/kubectl/kubectl_test.go
  operators/constellation-node-operator/README.md
  operators/constellation-node-operator/config/samples/update_v1alpha1_nodeversion.yaml
  operators/constellation-node-operator/config/samples/update_v1alpha1_scalinggroup.yaml
Labels: bug-fix

#782 cli: automatically add iam values to config
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/iam.go
  cli/internal/cmd/iamcreateaws.go
  cli/internal/cmd/iamcreateaws_test.go
  cli/internal/cmd/iamcreateazure.go
  cli/internal/cmd/iamcreateazure_test.go
  cli/internal/cmd/iamcreategcp.go
  cli/internal/cmd/iamcreategcp_test.go
Labels: feature

#949 deps: update Go to v1.19.5
  .github/actions/e2e_mini/action.yml
  .github/workflows/azure-snp-reporter.yml
  .github/workflows/build-binaries.yml
  .github/workflows/build-constellation-node-operator.yml
  .github/workflows/build-joinservice-image.yml
  .github/workflows/build-kms-image.yml
  .github/workflows/build-micro-service-manual.yml
  .github/workflows/build-operator-manual.yml
  .github/workflows/build-qemu-metadata-image.yml
  .github/workflows/build-verification-service.yml
  .github/workflows/check-licenses.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/generate-measurements.yml
  .github/workflows/on-release.yml
  .github/workflows/release-cli.yml
  .github/workflows/release.yml
  .github/workflows/test-actionlint.yml
  .github/workflows/test-go-generate.yml
  .github/workflows/test-govulncheck.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-operator-codegen.yml
  .github/workflows/test-shellcheck.yml
  .github/workflows/test-shellfmt.yml
  .github/workflows/test-tidy.yml
  .github/workflows/test-unittest.yml
  .github/workflows/update-cli-reference.yml
  .github/workflows/versionsapi.yml
  3rdparty/gcp-guest-agent/Dockerfile
  Dockerfile.build
  hack/qemu-metadata-api/Dockerfile
  joinservice/Dockerfile
  kms/Dockerfile
  proto/Dockerfile.gen-proto
  verify/Dockerfile
Labels: dependencies

#950 ci: deactivate dryrun of image deletion
  .github/workflows/purge-branch.yml
Labels: no-changelog

#957 cli: remove registry_auth for Docker Terraform module
  .github/actions/e2e_mini/run-e2e.sh
  cli/internal/terraform/terraform/qemu/main.tf
Labels: bug-fix

#963 cli: include search paths for image info json in error message printed to user
  cli/internal/image/image.go
Labels: no-changelog

#918 ci: increase Go test timeout in e2e lb
  .github/actions/e2e_lb/action.yml
Labels: no-changelog

#964 image: enable serial console access for MiniConstellation to simplify troubleshooting
  image/mkosi.files/mkosi.qemu.conf
  image/mkosi.postinst
  image/mkosi.skeleton/usr/lib/tmpfiles.d/constellation.conf
Labels: feature

#871 ci: reproducible builds ko (no gcp)
  .github/actions/build_apko/action.yml
  .github/actions/build_ko/action.yml
  .github/actions/build_micro_service_ko/action.yml
  .github/workflows/build-apko-image.yml
  .github/workflows/build-constellation-node-operator-ko.yml
  .github/workflows/build-joinservice-image-ko.yml
  .github/workflows/build-kms-image-ko.yml
  .github/workflows/build-verification-service-ko.yml
  .ko.yaml
  apko/alpine-base-user-65532.yaml
  apko/alpine-base.yaml
  apko/alpine-libcryptsetup.yaml
  apko/alpine-qemu-metadata-api.yaml
Labels: feature

#968 operator: reliability and simplification
  operators/constellation-node-operator/controllers/autoscalingstrategy_controller.go
  operators/constellation-node-operator/controllers/nodeversion_controller.go
  operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go
  operators/constellation-node-operator/controllers/pendingnode_controller.go
Labels: no-changelog

#969 ci: implement "console" stream for OS images to simplify debugging in customer environments
  .github/workflows/build-os-image.yml
  debugd/cmd/debugd/debugd.go
  debugd/internal/debugd/constants.go
  debugd/internal/debugd/deploy/seriallogin.go
  image/Makefile
  image/README.md
Labels: no-changelog

#973 image: apply shellfmt suggestions
  image/mkosi.postinst
Labels: no-changelog

#975 ci: remove residual references to "kms"
  .github/workflows/build-keyservice-image-ko.yml
  .github/workflows/release.yml
  .ko.yaml
Labels: no-changelog

#978 ci: delete old images of all streams on ref main
  .github/workflows/purge-main.yml
Labels: no-changelog

#980 versions: rename KmsImage to KeyServiceImage
  internal/versions/versions.go
Labels: no-changelog

#982 ci: fix versionsapi action output
  .github/actions/versionsapi/action.yml
Labels: bug-fix, no-changelog

#983 ci: switch gcp accounts to oidc
  .github/actions/e2e_test/action.yml
  .github/actions/login_gcp/action.yml
  .github/workflows/build-os-image.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/generate-measurements.yml
  .github/workflows/versionsapi.yml
Labels: no-changelog

#990 ci: fix versionsapi action
  .github/actions/versionsapi/action.yml
Labels: no-changelog

#996 ci: move verify e2e test
  .github/actions/e2e_test/action.yml
  .github/actions/e2e_verify/action.yml
Labels: no-changelog

#986 Configure CodeQL and scorecard workflow.
  .github/workflows/codeql.yml
  .github/workflows/scorecard.yml
  keyservice/setup/setup.go
  keyservice/setup/setup_test.go
Labels: no-changelog

#997 cli: adopt Cobra cli reference style
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/iam.go
  cli/internal/cmd/iamcreateaws.go
  cli/internal/cmd/iamcreateazure.go
  cli/internal/cmd/iamcreategcp.go
  cli/internal/cmd/init.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/terminate.go
  cli/internal/cmd/upgradeexecute.go
  dev-docs/conventions.md
Labels: no-changelog

#967 ci: fix scorecard/pinned-dependencies findings
  .github/actions/e2e_kbench/action.yml
  .github/actions/e2e_kbench/evaluate/requirements.txt
  .github/runners/azure-cvm/azure-function/requirements.txt
  .github/workflows/build-os-image-requirements.txt
  .github/workflows/build-os-image.yml
  .github/workflows/check-licenses.yml
  .github/workflows/test-actionlint.yml
  .github/workflows/test-go-generate.yml
  .github/workflows/test-govulncheck.yml
  hack/azure-snp-report-verify/Dockerfile
  renovate.json
Labels: no-changelog

#1002 verify: use fixed user data
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  hack/pcr-reader/main.go
  internal/constants/constants.go
  verify/server/server.go
  verify/server/server_test.go
  verify/verifyproto/verify.pb.go
  verify/verifyproto/verify.proto
Labels: no-changelog

#1005 ci: fix CLI SBOM generation
  .github/workflows/release-cli.yml
Labels: no-changelog

#991 azure: allow a set of idkeydigest values
  bootstrapper/cmd/bootstrapper/main.go
  bootstrapper/cmd/bootstrapper/run.go
  bootstrapper/cmd/bootstrapper/test.go
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/initserver/initserver_test.go
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  cli/internal/cloudcmd/validators.go
  cli/internal/cloudcmd/validators_test.go
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/configmap.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/values.schema.json
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/configmap.yaml
  internal/attestation/azure/snp/errors.go
  internal/attestation/azure/snp/validator.go
  internal/attestation/azure/snp/validator_test.go
  internal/attestation/idkeydigest/idkeydigest.go
  internal/attestation/idkeydigest/idkeydigest_test.go
  internal/cloud/vmtype/vmtype.go
  internal/cloud/vmtype/vmtype_string.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/constants/constants.go
  internal/watcher/validator.go
  internal/watcher/validator_test.go
Labels: feature

#1013 ci: install shellcheck using the action
  .github/workflows/test-actionlint.yml
  .github/workflows/test-go-generate.yml
  .github/workflows/test-tidy.yml
Labels: no-changelog

#1011 ci: move Syft & Grype installation into an action
  .github/actions/container_sbom/action.yml
  .github/actions/install_syft_grype/action.yml
  .github/workflows/release-cli.yml
Labels: no-changelog

#999 ci: adapt to new measurements format
  .github/actions/e2e_verify/action.yml
Labels: no-changelog

#1025 ci: run CodeQL only on Go/Python changes
  .github/workflows/codeql.yml
Labels: no-changelog

#845 ci: add e2e test for constellation recover
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_recover/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-weekly.yml
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform/aws/outputs.tf
  cli/internal/terraform/terraform/azure/outputs.tf
  cli/internal/terraform/terraform/gcp/outputs.tf
  cli/internal/terraform/terraform_test.go
  dev-docs/workflows/github-actions.md
Labels: no-changelog

#1028 ci: only run CodeQL on main
  .github/workflows/codeql.yml
Labels: no-changelog

#1036 ko: fix typo
  .ko.yaml
Labels: no-changelog

#1026 ci: run tests on workflow file change
  .github/workflows/check-licenses.yml
  .github/workflows/check-links.yml
  .github/workflows/test-govulncheck.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-operator-codegen.yml
  .github/workflows/test-shellcheck.yml
  .github/workflows/test-shellfmt.yml
  .github/workflows/test-tf.yml
  .github/workflows/test-tfsec.yml
  .github/workflows/test-tidy.yml
  .github/workflows/test-unittest.yml
Labels: no-changelog

#1027 image: upgrade azure kernel to 6.1.7
  image/Makefile
  image/mkosi.files/mkosi.azure.conf
Labels: no-changelog

#1010 ci: move apko building into separate script
  .github/actions/build_apko/action.yml
  .github/actions/build_apko/build_and_sign.sh
Labels: no-changelog

#1029 ci: curl flags
  .github/actions/build_cli/action.yml
  .github/actions/constellation_create/az-logs.sh
  .github/actions/e2e_mini/run-e2e.sh
  .github/actions/e2e_sonobuoy/action.yml
  .github/actions/e2e_verify/action.yml
  .github/actions/install_operator_sdk/action.yml
  .github/actions/setup_linux/action.yml
  .github/workflows/generate-measurements.yml
  .github/workflows/release-cli.yml
  debugd/internal/debugd/logcollector/logstash/Dockerfile
  image/Makefile
  image/secure-boot/azure/extract_vmgs.sh
  image/secure-boot/genkeys.sh
  image/secure-boot/signed-shim.sh
Labels: no-changelog

#1038 ci: fix GCP cloud controller manager build
  .github/workflows/build-ccm-gcp.yml
Labels: dependencies

#992 debugd: adapt README to set global image field in config
  debugd/README.md
Labels: no-changelog

#1051 deps: update cloud provider gcp image for k8s v1.26
  internal/versions/versions.go
Labels: dependencies

#1050 docs: update security issue warning to use Github warning banner
  README.md
Labels: no-changelog

#1049 operator: cleanup resources between tests
  operators/constellation-node-operator/controllers/nodeversion_controller.go
  operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go
Labels: no-changelog

#1048 cli: fix Terraform resource group dependencies
  cli/internal/terraform/terraform/iam/azure/main.tf
Labels: bug-fix

#1053 versions: update key-service name
  internal/versions/versions.go
Labels: no-changelog

#1054 cli: add godoc to iamid package
  cli/internal/iamid/id.go
Labels: no-changelog

#1037 docs: document terraform support
  cli/internal/terraform/terraform/aws/variables.tf
  docs/docs/getting-started/first-steps.md
  docs/docs/workflows/create.md
  docs/docs/workflows/terminate.md
Labels: documentation

#1055 ci: add workflow for proto code generation check
  .github/workflows/test-proto.yml
  disk-mapper/recoverproto/recover.pb.go
  disk-mapper/recoverproto/recover_grpc.pb.go
  joinservice/joinproto/join.pb.go
  joinservice/joinproto/join_grpc.pb.go
  verify/verifyproto/verify.pb.go
  verify/verifyproto/verify_grpc.pb.go
Labels: no-changelog

#1063 ci: add testdata trigger to unittest
  .github/workflows/test-unittest.yml
Labels: no-changelog

#1001 rfc: extend updates rfc with constraints section
  rfc/updates.md
Labels: no-changelog

#1064 config: fix digest naming
  cli/internal/cloudcmd/validators.go
  cli/internal/cloudcmd/validators_test.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/config/testdata/configAWSV2.yaml
  internal/config/testdata/configAzureV2MultipleIDKeyDigest.yaml
  internal/config/testdata/configAzureV2SingleIDKeyDigest.yaml
  internal/config/testdata/configGCPV2.yaml
Labels: breaking-change, bug-fix

#1068 config: fix digest naming
  cli/internal/cloudcmd/validators.go
  cli/internal/cloudcmd/validators_test.go
  cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/leader-election-rbac.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/manager-config.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/metrics-reader-rbac.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/metrics-service.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/proxy-rbac.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/deployment.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/leader-election-rbac.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/metrics-reader-rbac.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/metrics-service.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/proxy-rbac.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/selfsigned-issuer.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/serving-cert.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/validating-webhook-configuration.yaml
  cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/webhook-service.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/leader-election-rbac.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/manager-config.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/metrics-reader-rbac.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/metrics-service.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/proxy-rbac.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/deployment.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/leader-election-rbac.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/metrics-reader-rbac.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/metrics-service.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/proxy-rbac.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/selfsigned-issuer.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/serving-cert.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/validating-webhook-configuration.yaml
  cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/webhook-service.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/leader-election-rbac.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/manager-config.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/metrics-reader-rbac.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/metrics-service.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/proxy-rbac.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/deployment.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/leader-election-rbac.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/metrics-reader-rbac.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/metrics-service.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/proxy-rbac.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/selfsigned-issuer.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/serving-cert.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/validating-webhook-configuration.yaml
  cli/internal/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/webhook-service.yaml
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/config/testdata/configAWSV2.yaml
  internal/config/testdata/configAzureV2MultipleIDKeyDigest.yaml
  internal/config/testdata/configAzureV2SingleIDKeyDigest.yaml
  internal/config/testdata/configGCPV2.yaml
Labels: breaking change, bug fix, backport

#1069 cli: set placeholder uid for QEMU / MiniConstellation
  cli/internal/cmd/minidown.go
  cli/internal/cmd/miniup.go
  cli/internal/terraform/terraform/qemu/outputs.tf
  internal/constants/constants.go
Labels: bug fix

#1067 ci: use peter-evans' action to create prs
  .github/workflows/docs-update-reference.yml
  .github/workflows/release.yml
  .github/workflows/update-cli-reference.yml
Labels: no changelog

#1076 join-service: more logging on error
  internal/attestation/vtpm/attestation.go
  joinservice/internal/server/server.go
Labels: feature

#1079 ci: fix value substitution in pr messages
  .github/workflows/release.yml
Labels: no changelog

#1073 operator: make test more resilient
  operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go
Labels: no changelog

#1088 ci: improve readability of GitHub lables
  .github/release.yml
  .github/workflows/release.yml
  .github/workflows/update-cli-reference.yml
Labels: no changelog

#1087 terraform: make control-planes stateful on gcp
  cli/internal/terraform/terraform/gcp/.terraform.lock.hcl
  cli/internal/terraform/terraform/gcp/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/variables.tf
  hack/terraform/gcp/internal-loadbalancer/.terraform.lock.hcl
  hack/terraform/gcp/internal-loadbalancer/main.tf
  hack/terraform/gcp/internal-loadbalancer/modules/instance_group/main.tf
  hack/terraform/gcp/internal-loadbalancer/modules/instance_group/variables.tf
Labels: bug fix, needs backport

#1094 azure: add new idkeydigest
  internal/attestation/idkeydigest/idkeydigest.go
Labels: needs backport

#1095 azure: add new idkeydigest (#1094)
  internal/attestation/idkeydigest/idkeydigest.go
Labels: backport

#1081 ci: fix Constellation recover e2e test
  .github/actions/e2e_recover/action.yml
  .github/actions/e2e_test/action.yml
Labels: no changelog

#1070 debugd: keep mutex locked while receiving files
  debugd/internal/filetransfer/filetransfer.go
  debugd/internal/filetransfer/filetransfer_test.go
Labels: bug fix, no changelog

#1101 deps: update sonobuoy version
  .github/actions/e2e_sonobuoy/action.yml
Labels: dependencies

#1103 ci: pin kbench python dependencies
  .github/actions/e2e_kbench/evaluate/requirements.txt
Labels: dependencies

#1107 operator: log awaitingAnnotationNodes
  operators/constellation-node-operator/controllers/nodeversion_controller.go
Labels: no changelog

#1104 ci: minimal GitHub workflow token permissions
  .github/actions/build_micro_service/action.yml
  .github/workflows/azure-snp-reporter.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/build-os-image.yml
  .github/workflows/e2e-mini.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-tfsec.yml
Labels: no changelog

#1113 ci: fix purge branch permissions
  .github/workflows/purge-branch.yml
Labels: no changelog

#1116 ci: prevent empty tags field in build_ko pipeline
  .github/actions/build_ko/action.yml
  .github/actions/build_micro_service_ko/action.yml
  .github/workflows/release.yml
Labels: bug fix, no changelog

#1119 ci: fix purge-main permissions
  .github/workflows/purge-main.yml
Labels: no changelog

#1111 ci: fix oras download in package hasher
  .github/workflows/package-hasher.yml
Labels: bug fix, no changelog

#1115 ci: don't use k-bench install script
  .github/actions/e2e_kbench/action.yml
Labels: no changelog

#1121 ci: fix manual keyservice build workflow
  .github/workflows/build-keyservice-image.yml
Labels: bug fix, no changelog

#1123 ci: trigger builds on workflow change
  .github/workflows/build-apko-image.yml
  .github/workflows/build-constellation-node-operator.yml
  .github/workflows/build-joinservice-image.yml
  .github/workflows/build-keyservice-image.yml
  .github/workflows/build-qemu-metadata-image.yml
  .github/workflows/build-verification-service.yml
Labels: no changelog

#1122 ci: fix hasher permissions
  .github/workflows/package-hasher.yml
Labels: bug fix, no changelog
