Repository edgelesssys/constellation, pull requests merged in 2023-03, with the labels that each got.

#1311 cli: set constellation uid and role as instance metadata of OpenStack instances
  cli/internal/terraform/terraform/openstack/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/variables.tf
Labels: no changelog

#1312 disk-mapper: make openstack image bootable
  disk-mapper/cmd/main.go
Labels: no changelog

#1316 constants: make VersionInfo readonly
  CMakeLists.txt
  Dockerfile.build
  bootstrapper/cmd/bootstrapper/run.go
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/cmd/version.go
  cli/internal/cmd/version_test.go
  cli/internal/helm/client.go
  cli/internal/helm/loader.go
  disk-mapper/cmd/main.go
  internal/compatibility/compatibility.go
  internal/compatibility/compatibility_test.go
  internal/config/config.go
  internal/config/validation.go
  internal/config/validation_test.go
  internal/constants/constants.go
  internal/semver/semver.go
  joinservice/Dockerfile
  joinservice/cmd/main.go
  keyservice/Dockerfile
  keyservice/cmd/main.go
  verify/Dockerfile
  verify/cmd/main.go
Labels: no changelog

#1285 cli: allow existing config for IAM creation without --generate-config
  cli/internal/cmd/iamcreate.go
Labels: bug fix

#1308 docs: mention resource provider registration for Azure
  docs/docs/getting-started/install.md
  docs/docs/workflows/troubleshooting.md
  docs/versioned_docs/version-2.2/getting-started/install.md
  docs/versioned_docs/version-2.2/workflows/troubleshooting.md
  docs/versioned_docs/version-2.3/getting-started/install.md
  docs/versioned_docs/version-2.3/workflows/troubleshooting.md
  docs/versioned_docs/version-2.4/getting-started/install.md
  docs/versioned_docs/version-2.4/workflows/troubleshooting.md
  docs/versioned_docs/version-2.5/getting-started/install.md
  docs/versioned_docs/version-2.5/workflows/troubleshooting.md
Labels: documentation, no changelog

#1321 ci: run constellation commands with `--debug`
  .github/actions/constellation_create/action.yml
Labels: no changelog

#1322 oid: add alternative string representations for attestation variants
  cli/internal/cmd/init_test.go
  internal/attestation/aws/issuer.go
  internal/attestation/aws/validator.go
  internal/attestation/azure/snp/issuer.go
  internal/attestation/azure/snp/validator.go
  internal/attestation/gcp/issuer.go
  internal/attestation/gcp/validator.go
  internal/attestation/qemu/issuer.go
  internal/attestation/qemu/validator.go
  internal/oid/oid.go
Labels: no changelog

#1323 image: set attestation variant on kernel cmdline
  image/mkosi.files/mkosi.aws.conf
  image/mkosi.files/mkosi.azure.conf
  image/mkosi.files/mkosi.gcp.conf
  image/mkosi.files/mkosi.openstack.conf
  image/mkosi.files/mkosi.qemu.conf
  image/mkosi.skeleton/usr/lib/systemd/system/configure-constel-csp.service
Labels: no changelog

#1071 internal: refactor storage credentials
  bootstrapper/internal/initserver/initserver_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/recover_test.go
  go.mod
  hack/go.mod
  hack/go.sum
  internal/kms/README.md
  internal/kms/setup/setup.go
  internal/kms/setup/setup_test.go
  internal/kms/storage/awss3/awss3.go
  internal/kms/storage/awss3/awss3_test.go
  internal/kms/storage/azureblob/azureblob.go
  internal/kms/storage/azureblob/azureblob_test.go
  internal/kms/storage/azurestorage.go
  internal/kms/storage/gcloudstorage.go
  internal/kms/storage/gcloudstorage_integration_test.go
  internal/kms/storage/gcs/gcs.go
  internal/kms/storage/gcs/gcs_test.go
  internal/kms/storage/memfs/memfs.go
  internal/kms/storage/memfs/memfs_test.go
  internal/kms/storage/memfsstorage.go
  internal/kms/test/aws_test.go
  internal/kms/test/azure_test.go
  internal/kms/test/gcp_test.go
  internal/kms/test/integration_test.go
  internal/kms/uri/uri.go
  internal/kms/uri/uri_test.go
  keyservice/cmd/main.go
Labels: no changelog

#1318 cli/bootstrapper: remove deprecated master secret & KMS related fields
  bootstrapper/initproto/init.pb.go
  bootstrapper/initproto/init.proto
  cli/internal/cmd/init.go
Labels: no changelog

#1329 ci: change push/pr token
  .github/workflows/package-hasher.yml
  .github/workflows/release.yml
  .github/workflows/test-go-generate.yml
  .github/workflows/test-tf.yml
  .github/workflows/test-tidy.yml
  .github/workflows/update-cli-reference.yml
Labels: no changelog

#1326 cli: add `--kubernetes` flag to `iam create` (when used with `--create-config`)
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/iamcreate_test.go
Labels: feature

#1332 docs: update cli reference
  docs/docs/reference/cli.md
Labels: no changelog

#1320 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1325 renovate: fix versioning for containers
  renovate.json
Labels: no changelog

#1319 cli: restructure `upgrade apply` to change NodeVersion in one request
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/upgrade.go
  cli/internal/cloudcmd/upgrade_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/helm/client.go
  internal/compatibility/compatibility.go
Labels: no changelog

#1324 cli: log grpc connection state for init call
  cli/internal/cmd/init.go
Labels: no changelog

#1328 cli: set OpenStack service account credentials
  cli/internal/cloudcmd/create.go
  cli/internal/terraform/terraform/openstack/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/openstack/variables.tf
  cli/internal/terraform/variables.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/constants/constants.go
Labels: no changelog

#1330 deps: update sonobuoy
  .github/actions/e2e_sonobuoy/action.yml
Labels: no changelog

#1338 cli: upgrade libtpms in libvirt container
  cli/internal/libvirt/Dockerfile
Labels: bug fix

#1337 deps: fix dependabot security warnings
  hack/go.mod
  operators/constellation-node-operator/go.mod
Labels: no changelog

#1339 deps: manually upgrade libvirt container for upcoming release
  internal/versions/versions.go
Labels: dependencies, no changelog

#1220 docs: publish minor fixes
  docs/versioned_docs/version-2.5/workflows/config.md
  docs/versioned_docs/version-2.5/workflows/terminate.md
Labels: no changelog

#1345 image: pin aws uefivars version and install new deps
  .github/workflows/build-os-image.yml
  image/secure-boot/aws/create_uefivars.sh
Labels: dependencies, bug fix, no changelog

#1350 ci: move aws iam create test to less utilized zone
  .github/actions/e2e_test/action.yml
Labels: no changelog

#1351 image: add systemd-boot as explicit dependency
  image/mkosi.conf.d/secure-boot-tpm.conf
Labels: no changelog

#1349 ci: use latest ver of versionsapi cli container
  .github/actions/versionsapi/action.yml
Labels: no changelog

#1366 deps: update to Go 1.20.2
  .github/actions/build_ko/action.yml
  .github/actions/e2e_mini/action.yml
  .github/workflows/azure-snp-reporter.yml
  .github/workflows/build-binaries.yml
  .github/workflows/build-constellation-node-operator.yml
  .github/workflows/build-joinservice-image.yml
  .github/workflows/build-keyservice-image.yml
  .github/workflows/build-operator-manual.yml
  .github/workflows/build-os-image.yml
  .github/workflows/build-qemu-metadata-image.yml
  .github/workflows/build-verification-service.yml
  .github/workflows/build-versionsapi-ci-image.yml
  .github/workflows/check-licenses.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/on-release.yml
  .github/workflows/release-cli.yml
  .github/workflows/release.yml
  .github/workflows/test-actionlint.yml
  .github/workflows/test-go-generate.yml
  .github/workflows/test-govulncheck.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-operator-codegen.yml
  .github/workflows/test-shellcheck.yml
  .github/workflows/test-shellfmt.yml
  .github/workflows/test-tidy.yml
  .github/workflows/test-unittest.yml
  .github/workflows/update-cli-reference.yml
  3rdparty/gcp-guest-agent/Dockerfile
  Dockerfile.build
  WORKSPACE.bazel
  hack/qemu-metadata-api/Dockerfile
  joinservice/Dockerfile
  keyservice/Dockerfile
  proto/Dockerfile.gen-proto
  verify/Dockerfile
Labels: dependencies

#1354 use any instead of interface{}
  cli/internal/helm/loader.go
  internal/cloud/cloudprovider/cloudprovider.go
Labels: no changelog

#1369 image: downgrade systemd to 251.11-2
  image/Makefile
  image/mkosi.conf.d/mkosi.conf
  image/mkosi.conf.d/secure-boot-tpm.conf
  image/mkosi.files/mkosi.aws.conf
  image/mkosi.files/mkosi.azure.conf
  image/mkosi.files/mkosi.gcp.conf
  image/mkosi.files/mkosi.openstack.conf
  image/mkosi.files/mkosi.qemu.conf
Labels: bug fix

#1368 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1359 renovate: disable major updates of transitive deps
  renovate.json
Labels: no changelog

#1374 cli: add missing flag to miniConstellation
  cli/internal/cmd/init.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/spinner.go
Labels: no changelog

#1378 docs: update cli reference
  docs/docs/reference/cli.md
Labels: no changelog

#1382 renovate: exclude cloud-provider-gcp
  renovate.json
Labels: no changelog

#1381 Add measurement-reader tool
  CMakeLists.txt
  Dockerfile.build
  image/Makefile
  image/mkosi.conf.d/secure-boot-tpm.conf
  image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset
  image/mkosi.skeleton/usr/lib/systemd/system/measurements.service
  image/mkosi.skeleton/usr/libexec/constellation-pcrs
  internal/oid/oid.go
  measurement-reader/cmd/main.go
  measurement-reader/internal/sorted/sorted.go
  measurement-reader/internal/tpm/tpm.go
  measurement-reader/internal/tpm/tpm_test.go
Labels: feature

#1379 docs: add release v2.6.0
  docs/versioned_docs/version-2.6/_media/SLSA-Badge-full-level3.svg
  docs/versioned_docs/version-2.6/_media/benchmark_api_dpl.png
  docs/versioned_docs/version-2.6/_media/benchmark_api_pods.png
  docs/versioned_docs/version-2.6/_media/benchmark_api_svc.png
  docs/versioned_docs/version-2.6/_media/benchmark_io.png
  docs/versioned_docs/version-2.6/_media/benchmark_net.png
  docs/versioned_docs/version-2.6/_media/concept-constellation.svg
  docs/versioned_docs/version-2.6/_media/concept-managed.svg
  docs/versioned_docs/version-2.6/_media/constellation_oneline.svg
  docs/versioned_docs/version-2.6/_media/example-emojivoto.jpg
  docs/versioned_docs/version-2.6/_media/example-online-boutique.jpg
  docs/versioned_docs/version-2.6/_media/product-overview-dark.png
  docs/versioned_docs/version-2.6/_media/product-overview.png
  docs/versioned_docs/version-2.6/_media/recovery-gcp-serial-console-link.png
  docs/versioned_docs/version-2.6/_media/tcb.svg
  docs/versioned_docs/version-2.6/architecture/attestation.md
  docs/versioned_docs/version-2.6/architecture/encrypted-storage.md
  docs/versioned_docs/version-2.6/architecture/images.md
  docs/versioned_docs/version-2.6/architecture/keys.md
  docs/versioned_docs/version-2.6/architecture/microservices.md
  docs/versioned_docs/version-2.6/architecture/networking.md
  docs/versioned_docs/version-2.6/architecture/orchestration.md
  docs/versioned_docs/version-2.6/architecture/overview.md
  docs/versioned_docs/version-2.6/architecture/versions.md
  docs/versioned_docs/version-2.6/getting-started/examples.md
  docs/versioned_docs/version-2.6/getting-started/examples/emojivoto.md
  docs/versioned_docs/version-2.6/getting-started/examples/horizontal-scaling.md
  docs/versioned_docs/version-2.6/getting-started/examples/online-boutique.md
  docs/versioned_docs/version-2.6/getting-started/first-steps-local.md
  docs/versioned_docs/version-2.6/getting-started/first-steps.md
  docs/versioned_docs/version-2.6/getting-started/install.md
  docs/versioned_docs/version-2.6/intro.md
  docs/versioned_docs/version-2.6/overview/clouds.md
  docs/versioned_docs/version-2.6/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.6/overview/license.md
  docs/versioned_docs/version-2.6/overview/performance.md
  docs/versioned_docs/version-2.6/overview/product.md
  docs/versioned_docs/version-2.6/overview/security-benefits.md
  docs/versioned_docs/version-2.6/reference/cli.md
  docs/versioned_docs/version-2.6/reference/config-migration.md
  docs/versioned_docs/version-2.6/reference/slsa.md
  docs/versioned_docs/version-2.6/reference/terraform.md
  docs/versioned_docs/version-2.6/workflows/cert-manager.md
  docs/versioned_docs/version-2.6/workflows/config.md
  docs/versioned_docs/version-2.6/workflows/create.md
  docs/versioned_docs/version-2.6/workflows/lb.md
  docs/versioned_docs/version-2.6/workflows/recovery.md
  docs/versioned_docs/version-2.6/workflows/sbom.md
  docs/versioned_docs/version-2.6/workflows/scale.md
  docs/versioned_docs/version-2.6/workflows/storage.md
  docs/versioned_docs/version-2.6/workflows/terminate.md
  docs/versioned_docs/version-2.6/workflows/troubleshooting.md
  docs/versioned_docs/version-2.6/workflows/trusted-launch.md
  docs/versioned_docs/version-2.6/workflows/upgrade.md
  docs/versioned_docs/version-2.6/workflows/verify-cli.md
  docs/versioned_docs/version-2.6/workflows/verify-cluster.md
  docs/versioned_sidebars/version-2.6-sidebars.json
  docs/versions.json
Labels: no changelog

#1386 fix: add measurement-reader to build pipeline
  .github/actions/build_measurement_reader/action.yml
  .github/workflows/build-binaries.yml
  .github/workflows/build-os-image.yml
Labels: no changelog

#1389 constants: use "Enterprise" for enterprise build in "constellation version"
  internal/constants/enterprise.go
Labels: bug fix

#1384 docs: minor adjustements to the release docs
  dev-docs/workflows/release.md
Labels: no changelog

#1393 image: increase esp size
  image/mkosi.conf.d/mkosi.conf
Labels: no changelog

#1392 ci: ignore replaced ghsa
  .grype.yaml
  hack/go.mod
  operators/constellation-node-operator/go.mod
Labels: no changelog

#1395 cli: remove Edition in version command, which contains duplicate info
  cli/internal/cmd/version.go
  internal/constants/enterprise.go
  internal/constants/oss.go
Labels: no changelog

#1399 ci: tag GCP guest agent with semver
  .github/workflows/build-gcp-guest-agent.yml
Labels: no changelog

#1154 docs: embedd asciinema casts
  docs/docs/workflows/config.md
  docs/docs/workflows/create.md
  docs/docs/workflows/sbom.md
  docs/docs/workflows/terminate.md
  docs/docs/workflows/verify-cli.md
  docs/package.json
  docs/screencasts/.gitignore
  docs/screencasts/README.md
  docs/screencasts/docker/Dockerfile
  docs/screencasts/docker/check-sbom.expect
  docs/screencasts/docker/configure-cluster.expect
  docs/screencasts/docker/create-cluster.expect
  docs/screencasts/docker/github-readme.expect
  docs/screencasts/docker/terminate-cluster.expect
  docs/screencasts/docker/verify-cli.expect
  docs/screencasts/generate-readme-svg.sh
  docs/screencasts/generate-screencasts.sh
  docs/screencasts/window-frame.svg
  docs/src/components/AsciinemaWidget/index.js
  docs/src/css/custom.css
  docs/src/theme/MDXComponents.js
  docs/static/assets/check-sbom.cast
  docs/static/assets/configure-cluster.cast
  docs/static/assets/create-cluster.cast
  docs/static/assets/terminate-cluster.cast
  docs/static/assets/verify-cli.cast
  docs/static/img/shell-windowframe.svg
  docs/styles/Vocab/constellation/accept.txt
  docs/versioned_docs/version-2.6/workflows/config.md
  docs/versioned_docs/version-2.6/workflows/create.md
  docs/versioned_docs/version-2.6/workflows/sbom.md
  docs/versioned_docs/version-2.6/workflows/terminate.md
  docs/versioned_docs/version-2.6/workflows/verify-cli.md
Labels: documentation

#1405 docs: remove pcr warning from asciinema casts
  docs/static/assets/create-cluster.cast
  docs/static/img/shell-windowframe.svg
Labels: no changelog

#1400 deps: update GCP guest agent image
  internal/versions/versions.go
Labels: dependencies

#1407 deps: update containers to v2.7.0-pre
  internal/versions/versions.go
Labels: dependencies

#1406 image: update Azure and GCP to kernel 6.1.18
  image/Makefile
  image/mkosi.files/mkosi.azure.conf
  image/mkosi.files/mkosi.gcp.conf
Labels: dependencies

#1414 docs: refer to known issues
  README.md
  docs/docs/getting-started/first-steps-local.md
  docs/docs/getting-started/first-steps.md
  docs/docs/workflows/troubleshooting.md
  docs/versioned_docs/version-2.6/getting-started/first-steps-local.md
  docs/versioned_docs/version-2.6/getting-started/first-steps.md
  docs/versioned_docs/version-2.6/workflows/troubleshooting.md
Labels: no changelog

#1413 config: add attestation variant
  bootstrapper/cmd/bootstrapper/test.go
  bootstrapper/internal/initserver/BUILD.bazel
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/initserver/initserver_test.go
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/validators.go
  cli/internal/cloudcmd/validators_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/verify.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/daemonset.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/values.schema.json
  cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/values.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/verification-service/templates/daemonset.yaml
  cli/internal/helm/charts/edgeless/constellation-services/charts/verification-service/values.schema.json
  cli/internal/helm/charts/edgeless/constellation-services/charts/verification-service/values.yaml
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/daemonset.yaml
  cli/internal/helm/testdata/Azure/constellation-services/charts/verification-service/templates/daemonset.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/join-service/templates/daemonset.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/verification-service/templates/daemonset.yaml
  cli/internal/helm/testdata/QEMU/constellation-services/charts/join-service/templates/daemonset.yaml
  cli/internal/helm/testdata/QEMU/constellation-services/charts/verification-service/templates/daemonset.yaml
  internal/config/BUILD.bazel
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/config/validation.go
  internal/constants/constants.go
  internal/watcher/BUILD.bazel
  internal/watcher/validator.go
  internal/watcher/validator_test.go
  joinservice/cmd/BUILD.bazel
  joinservice/cmd/main.go
  verify/cmd/BUILD.bazel
  verify/cmd/main.go
Labels: no changelog

#1425 bazel: command to prepare development workspace
  BUILD.bazel
  CODEOWNERS
  bazel/ci/BUILD.bazel
  bazel/devbuild/BUILD.bazel
  bazel/devbuild/prepare_developer_workspace.sh.in
  cli/BUILD.bazel
  debugd/cmd/cdbg/BUILD.bazel
  dev-docs/workflows/build-test-run.md
Labels: no changelog

#1428 bazel: format devbuild files
  bazel/devbuild/BUILD.bazel
  bazel/devbuild/prepare_developer_workspace.sh.in
Labels: no changelog

#1412 Use version.txt to generate (pseudo-)version information
  .bazelrc
  .github/actions/build_ko/action.yml
  .github/actions/build_micro_service/action.yml
  .github/actions/build_operator/action.yml
  .github/actions/os_build_variables/action.yml
  .github/actions/pseudo_version/action.yml
  .github/workflows/build-apko-image.yml
  .github/workflows/build-os-image.yml
  hack/pseudo-version/internal/git/BUILD.bazel
  hack/pseudo-version/internal/git/git.go
  hack/pseudo-version/pseudo-version.go
  tools/dnf-init.sh
  tools/dnf-tree.sh
  tools/workspace_status.sh
  version.txt
Labels: no changelog

#1388 ci: remove Go setup where Bazel is used for building
  .github/workflows/build-binaries.yml
  .github/workflows/release-cli.yml
Labels: no changelog

#1430 docs: pin base image of screencast container
  docs/screencasts/docker/Dockerfile
Labels: no changelog

#1402 deps: upgrade rules_oci to v0.3.3
  WORKSPACE.bazel
  bazel/toolchains/oci_deps.bzl
Labels: dependencies

#1434 bazel: use host platform by default
  .bazelrc
  CMakeLists.txt
  bazel/devbuild/BUILD.bazel
  bazel/go/platform.bzl
  bootstrapper/cmd/bootstrapper/BUILD.bazel
  debugd/cmd/debugd/BUILD.bazel
  disk-mapper/cmd/BUILD.bazel
  measurement-reader/cmd/BUILD.bazel
  upgrade-agent/cmd/BUILD.bazel
Labels: no changelog

#1439 bazel: add actionlint to //:check
  .github/workflows/purge-main.yml
  .github/workflows/test-actionlint.yml
  bazel/ci/BUILD.bazel
  bazel/ci/actionlint.sh.in
  bazel/toolchains/go_module_deps.bzl
  hack/tools/BUILD.bazel
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: no changelog

#1454 cli: remove ctx parameter from rollbackOnError to prevent wrong use
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/iam.go
  cli/internal/cloudcmd/rollback.go
Labels: no changelog

#1446 e2e: Remove Ubuntu builder for debug artifacts required for macOS runner
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-manual.yml
Labels: no changelog

#1375 cli: support custom attestation policies for maa
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/clusterid/id.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform/azure/main.tf
  cli/internal/terraform/terraform/azure/outputs.tf
  cli/internal/terraform/terraform/azure/variables.tf
  cli/internal/terraform/terraform_test.go
  cli/internal/terraform/variables.go
  go.mod
  hack/go.mod
  hack/go.sum
  internal/constants/constants.go
Labels: feature

#1461 config: set Azure-SEV-SNP as default azure attestation variant
  internal/config/validation.go
Labels: no changelog

#1463 cli: fix typo
  cli/internal/cmd/init.go
Labels: bug fix, no changelog

#1456 bazel: use remote caching
  .bazelrc
  .github/actions/build_bootstrapper/action.yml
  .github/actions/build_cdbg/action.yml
  .github/actions/build_cli/action.yml
  .github/actions/build_debugd/action.yml
  .github/actions/build_disk_mapper/action.yml
  .github/actions/build_measurement_reader/action.yml
  .github/actions/build_upgrade_agent/action.yml
  .github/actions/e2e_mini/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/setup_bazel/action.yml
  .github/workflows/build-binaries.yml
  .github/workflows/build-os-image.yml
  .github/workflows/e2e-mini.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/release-cli.yml
  dev-docs/workflows/build-test-run.md
  tools/workspace_status.sh
Labels: no changelog

#1441 cli: minor restructuring for loading helm charts
  cli/internal/helm/loader.go
  internal/attestation/azure/snp/BUILD.bazel
Labels: no changelog

#1465 terraform: valid Azure attestation provider name
  cli/internal/terraform/terraform/azure/main.tf
Labels: no changelog

#1470 bazel: allow user defined overwrites
  .bazelrc
  .gitignore
Labels: no changelog

#1467 cli: add attestationVariant upgrade migration
  cli/internal/helm/client.go
Labels: no changelog

#1444 ci: use github actions cache to speedup bazel builds
  .github/actions/setup_bazel/action.yml
  .github/workflows/warm-bazel-cache.yml
Labels: no changelog

#1472 terraform: unique Azure attestation provider name
  cli/internal/terraform/terraform/azure/main.tf
Labels: bug fix, no changelog

#1474 bazel: upgrade bazel-zig-cc to allow caching of launcher
  WORKSPACE.bazel
  bazel/toolchains/zig_cc_deps.bzl
Labels: no changelog

#1477 ci: rename scheduled OS image build action
  .github/workflows/build-os-image-scheduled.yml
Labels: no changelog

#1471 terraform: allow for multiple instance groups on gcp
  cli/internal/terraform/terraform/gcp/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/variables.tf
  hack/terraform/gcp/internal-loadbalancer/main.tf
  hack/terraform/gcp/internal-loadbalancer/modules/instance_group/main.tf
  hack/terraform/gcp/internal-loadbalancer/modules/instance_group/variables.tf
Labels: no changelog

#1480 e2e: install Terraform for macOS runner for boot log collection
  .github/workflows/e2e-test-manual.yml
Labels: no changelog

#1462 measurements: refactor validation option
  bootstrapper/cmd/bootstrapper/main.go
  cli/internal/cloudcmd/upgrade.go
  cli/internal/cloudcmd/upgrade_test.go
  cli/internal/cloudcmd/validators.go
  cli/internal/cloudcmd/validators_test.go
  cli/internal/cmd/init_test.go
  cli/internal/helm/loader_test.go
  internal/attestation/measurements/measurement-generator/generate.go
  internal/attestation/measurements/measurements.go
  internal/attestation/measurements/measurements_enterprise.go
  internal/attestation/measurements/measurements_oss.go
  internal/attestation/measurements/measurements_test.go
  internal/attestation/vtpm/attestation.go
  internal/attestation/vtpm/attestation_test.go
  internal/config/config_test.go
  internal/watcher/validator_test.go
  measurement-reader/internal/tpm/tpm_test.go
Labels: no changelog

#1468 cli: fix `upgrade apply` for image-only upgrades
  cli/internal/cloudcmd/upgrade.go
  cli/internal/cloudcmd/upgrade_test.go
Labels: bug fix, needs backport

#1502 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1503 go: update submodules to Go 1.20
  3rdparty/node-maintenance-operator/go.mod
  hack/go.mod
  operators/constellation-node-operator/api/go.mod
  operators/constellation-node-operator/go.mod
Labels: no changelog

#1466 ci: add unittests for the benchmark actions
  .github/actions/e2e_benchmark/evaluate/compare.py
  .github/actions/e2e_benchmark/evaluate/parse.py
  .github/actions/e2e_benchmark/evaluate/test-inputs/constellation-azure.json
  .github/actions/e2e_benchmark/evaluate/test-inputs/fio-constellation-azure.json
  .github/actions/e2e_benchmark/evaluate/test-inputs/knb-constellation-azure.json
  .github/actions/e2e_benchmark/evaluate/test.py
Labels: no changelog

#1494 bazel: add golangci-lint to //:check target
  .github/workflows/test-lint.yml
  .github/workflows/test-tidy.yml
  bazel/ci/BUILD.bazel
  bazel/ci/golangci.sh.in
  bazel/sh/def.bzl
  bazel/toolchains/BUILD.golangci.bazel
  bazel/toolchains/ci_deps.bzl
Labels: no changelog

#1510 fix measurement generator
  internal/attestation/measurements/measurement-generator/generate.go
  internal/attestation/measurements/measurements_enterprise.go
Labels: no changelog

#1511 bazel: add buf as protobuf formatter to //:tidy
  bazel/ci/BUILD.bazel
  bazel/ci/buf.sh.in
  bazel/toolchains/ci_deps.bzl
  debugd/service/debugd.proto
  disk-mapper/recoverproto/recover.proto
  joinservice/joinproto/join.proto
  keyservice/keyserviceproto/keyservice.proto
  upgrade-agent/upgradeproto/upgrade.proto
  verify/verifyproto/verify.proto
Labels: no changelog

#1515 docs: update cli reference
  docs/docs/reference/cli.md
Labels: no changelog

#1518 cli: warn about missing support for upgrades on AWS, OpenStack, QEMU
  cli/internal/cmd/upgradeapply.go
  docs/docs/workflows/upgrade.md
Labels: needs backport

#1521 ci: fix PCR5 warnings on GCP by not statically setting it
  .github/workflows/build-os-image.yml
Labels: bug fix, needs backport

#1514 bazel: exclude node modules from shellcheck
  bazel/ci/shellcheck.sh.in
  bazel/ci/shfmt.sh.in
Labels: no changelog

#1536 docs: add CDN cache invalidation to release docs
  dev-docs/workflows/release.md
Labels: no changelog

#1537 go: clean work file
  go.work
Labels: no changelog

#1538 internal: refactor oid package to variant package
  bootstrapper/cmd/bootstrapper/BUILD.bazel
  bootstrapper/cmd/bootstrapper/main.go
  bootstrapper/internal/initserver/BUILD.bazel
  bootstrapper/internal/initserver/initserver_test.go
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/validators.go
  cli/internal/cloudcmd/validators_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/verify_test.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/loader_test.go
  disk-mapper/cmd/BUILD.bazel
  disk-mapper/cmd/main.go
  disk-mapper/internal/recoveryserver/BUILD.bazel
  disk-mapper/internal/recoveryserver/recoveryserver_test.go
  internal/atls/BUILD.bazel
  internal/atls/atls.go
  internal/atls/atls_test.go
  internal/attestation/aws/BUILD.bazel
  internal/attestation/aws/issuer.go
  internal/attestation/aws/validator.go
  internal/attestation/azure/snp/BUILD.bazel
  internal/attestation/azure/snp/issuer.go
  internal/attestation/azure/snp/validator.go
  internal/attestation/azure/trustedlaunch/BUILD.bazel
  internal/attestation/azure/trustedlaunch/issuer.go
  internal/attestation/azure/trustedlaunch/validator.go
  internal/attestation/choose/BUILD.bazel
  internal/attestation/choose/choose.go
  internal/attestation/choose/choose_test.go
  internal/attestation/gcp/BUILD.bazel
  internal/attestation/gcp/issuer.go
  internal/attestation/gcp/validator.go
  internal/attestation/qemu/BUILD.bazel
  internal/attestation/qemu/issuer.go
  internal/attestation/qemu/validator.go
  internal/config/BUILD.bazel
  internal/config/config_test.go
  internal/config/validation.go
  internal/grpc/dialer/BUILD.bazel
  internal/grpc/dialer/dialer_test.go
  internal/variant/BUILD.bazel
  internal/variant/variant.go
  internal/watcher/BUILD.bazel
  internal/watcher/validator.go
  internal/watcher/validator_test.go
  joinservice/cmd/BUILD.bazel
  joinservice/cmd/main.go
  measurement-reader/cmd/BUILD.bazel
  measurement-reader/cmd/main.go
  verify/cmd/BUILD.bazel
  verify/cmd/main.go
Labels: no changelog

#1531 docs: update govulncheck badge to new workflow
  README.md
Labels: no changelog

#1540 cli: set cluster's measurements from user's config using Helm instead of loading them from node on boot
  bootstrapper/cmd/bootstrapper/BUILD.bazel
  bootstrapper/cmd/bootstrapper/main.go
  bootstrapper/cmd/bootstrapper/test.go
  bootstrapper/initproto/init.pb.go
  bootstrapper/initproto/init.proto
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/initserver/initserver_test.go
  bootstrapper/internal/kubernetes/BUILD.bazel
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  cli/internal/cmd/init.go
  cli/internal/helm/loader.go
  internal/config/config.go
Labels: no changelog

#1542 measurements: compare to constants for clarity
  internal/attestation/measurements/measurements.go
  internal/attestation/vtpm/attestation.go
Labels: no changelog

#1545 atls: fix link in README.md
  internal/atls/README.md
Labels: no changelog

#1539 config: deprecate confidentialVM option for Azure clusters in favor of using attestationVariant option
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cmd/create.go
  cli/internal/image/BUILD.bazel
  cli/internal/image/image.go
  cli/internal/image/image_test.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/validation.go
  internal/config/validation_test.go
Labels: feature

#1327 feat: journald package
  bootstrapper/internal/journald/BUILD.bazel
  bootstrapper/internal/journald/journald.go
  bootstrapper/internal/journald/journald_test.go
Labels: feature

#1436 rfc: attestation config options
  rfc/attestation-config.md
Labels: no changelog

#1487 versionsapi: Split GCP image URI to extract the image name
  internal/versionsapi/cli/rm.go
Labels: no changelog

#1535 ci: set correct fromVersion for upgrade test in weekly e2e job
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#1442 docs: list minimal permissions for Constellation setup
  docs/docs/getting-started/install.md
  docs/docs/workflows/config.md
  docs/styles/Vocab/constellation/accept.txt
Labels: feature

#1554 bazel: add protoc codegen to //:generate target
  .github/workflows/test-proto.yml
  bazel/ci/BUILD.bazel
  bazel/ci/proto_targets.bzl
  bazel/ci/proto_targets_check.sh.in
  bazel/proto/BUILD.bazel
  bazel/proto/rules.bzl
  bootstrapper/initproto/BUILD.bazel
  bootstrapper/initproto/init.pb.go
  bootstrapper/initproto/init_grpc.pb.go
  debugd/service/BUILD.bazel
  debugd/service/debugd.pb.go
  debugd/service/debugd_grpc.pb.go
  dev-docs/conventions.md
  dev-docs/layout.md
  dev-docs/workflows/build-test-run.md
  disk-mapper/recoverproto/BUILD.bazel
  disk-mapper/recoverproto/recover.pb.go
  disk-mapper/recoverproto/recover_grpc.pb.go
  joinservice/joinproto/BUILD.bazel
  joinservice/joinproto/join.pb.go
  joinservice/joinproto/join_grpc.pb.go
  keyservice/keyserviceproto/BUILD.bazel
  keyservice/keyserviceproto/keyservice.pb.go
  keyservice/keyserviceproto/keyservice_grpc.pb.go
  proto/Dockerfile.gen-proto
  proto/README.md
  upgrade-agent/upgradeproto/BUILD.bazel
  upgrade-agent/upgradeproto/upgrade.pb.go
  upgrade-agent/upgradeproto/upgrade_grpc.pb.go
  verify/verifyproto/BUILD.bazel
  verify/verifyproto/verify.pb.go
  verify/verifyproto/verify_grpc.pb.go
Labels: no changelog

#1559 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1562 deps: update ko base images
  .ko.yaml
Labels: dependencies, security fix

#1493 add version.txt step to release pipeline
  .github/workflows/e2e-test-manual.yml
  .github/workflows/release.yml
  e2e/miniconstellation/cloud-init.yaml
  e2e/miniconstellation/main.tf
  e2e/miniconstellation/test-remote.sh
  internal/attestation/measurements/measurements_enterprise.go
  tools/workspace_status.sh
Labels: no changelog

#1568 cli: remove duplicated print
  cli/internal/cmd/iamcreate.go
Labels: no changelog

#1572 cli: add missing -y short flag to iam create
  cli/internal/cmd/iamcreate.go
  docs/docs/reference/cli.md
Labels: no changelog

#1560 ci: sort apk hashes
  apko/SHA256SUMS-apk-amd64
  hack/package-hasher/Containerfile.apk.hasher
Labels: no changelog

#1541 config: remove deprecated upgradeConfig and require name and microserviceVersion fields
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/create.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/config/validation.go
Labels: breaking change
