Repository edgelesssys/constellation, pull requests merged in 2023-05, with the labels that each got.

#1706 image: fix pcr 12 calculation
  image/measured-boot/precalculate_pcr_12.sh
Labels: no changelog

#1711 image: upgrade mkosi to support repart (#1684)
  .github/actions/setup_mkosi/action.yaml
  .github/workflows/build-os-image.yml
  image/Makefile
  image/README.md
  image/mkosi.conf.d/mkosi.aws.conf
  image/mkosi.conf.d/mkosi.azure.conf
  image/mkosi.conf.d/mkosi.conf
  image/mkosi.conf.d/mkosi.gcp.conf
  image/mkosi.conf.d/mkosi.openstack.conf
  image/mkosi.conf.d/mkosi.qemu.conf
  image/mkosi.conf.d/selinux.conf
  image/mkosi.repart/00-esp.conf
  image/mkosi.repart/10-root.conf
  image/mkosi.repart/20-root-verity.conf
  image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/module-setup.sh
  image/mkosi.skeleton/usr/lib/systemd/resolved.conf.d/fallback_dns.conf
  image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset
Labels: no changelog, backport

#1712 image: fix pcr 12 calculation (#1706)
  image/measured-boot/precalculate_pcr_12.sh
Labels: no changelog, backport

#1708 upgrade: fix 2.6 -> 2.7 migration for 2.7.1 patch (#1649)
  .github/workflows/e2e-upgrade.yml
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/client.go
  cli/internal/helm/client_test.go
  e2e/internal/upgrade/image.go
  e2e/internal/upgrade/upgrade_test.go
  hack/pseudo-version/pseudo-version.go
Labels: bug fix, backport

#1709 cli: create namespaced folders for upgrade backups (#1702)
  cli/internal/helm/backup.go
  cli/internal/helm/backup_test.go
Labels: bug fix, backport

#1714 ci: skip e2e tests if caller was not successful
  .github/workflows/e2e-mini.yml
  .github/workflows/e2e-test-release.yml
Labels: no changelog, needs backport

#1720 ci: use uuidgen to get uuid, for macos compability
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#1721 ci: skip e2e tests if caller was not successful (#1714)
  .github/workflows/e2e-mini.yml
  .github/workflows/e2e-test-release.yml
Labels: no changelog, backport

#1719 cli: remove ambiguity in path for CR backups
  cli/internal/helm/backup.go
  cli/internal/helm/backup_test.go
Labels: no changelog, needs backport

#1723 cli: remove ambiguity in path for CR backups (#1719)
  cli/internal/helm/backup.go
  cli/internal/helm/backup_test.go
Labels: no changelog, backport

#1728 ci: fix e2e miniconstellation abort condition
  .github/workflows/e2e-mini.yml
Labels: no changelog, needs backport

#1731 ci: update measurement overwrite for config v3
  .github/actions/constellation_create/action.yml
Labels: no changelog

#1730 ci: fix e2e miniconstellation abort condition (#1728)
  .github/workflows/e2e-mini.yml
Labels: no changelog, backport

#1654 docs: add short explanation on attestation config options
  docs/docs/architecture/attestation.md
Labels: documentation

#1736 Update release.md
  dev-docs/workflows/release.md
Labels: no changelog

#1741 ci: fix measurement generation on scheduled build
  .github/workflows/build-os-image-scheduled.yml
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image.go
Labels: no changelog

#1669 deps: add Kubernetes v1.27, remove Kubernetes v1.24
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  docs/docs/reference/cli.md
  internal/config/config_test.go
  internal/config/validation.go
  internal/versions/versions.go
  operators/constellation-node-operator/Makefile
Labels: feature

#1739 ci: guard measurement removal behind config version check
  .github/actions/constellation_create/action.yml
Labels: no changelog

#1755 ci: fix measurements injection in verify e2e test
  .github/actions/e2e_verify/action.yml
Labels: no changelog

#1763 ci: fix minicon e2e test
  .github/actions/e2e_mini/action.yml
  .github/workflows/e2e-mini.yml
  cli/internal/cmd/miniup.go
Labels: no changelog

#1756 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image.go
Labels: no changelog

#1722 ci: set toImage argument in e2e-test-release
  .github/workflows/e2e-test-release.yml
Labels: no changelog

#1768 image: include stream in gcp image name
  internal/osimage/gcp/gcpupload.go
Labels: no changelog

#1774 bazel: dont stop check on error
  bazel/ci/BUILD.bazel
Labels: no changelog

#1782 deps: update bazeldnf digest to v0.5.7
  bazel/toolchains/dnf_deps.bzl
Labels: no changelog

#1769 cli: new flag to set the attestation type for `config generate`
  cli/internal/cloudcmd/create_test.go
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
  dev-docs/workflows/build-test-run.md
  docs/docs/reference/cli.md
  internal/config/config.go
  internal/config/config_test.go
  internal/variant/BUILD.bazel
  internal/variant/variant.go
Labels: feature

#1795 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image.go
Labels: no changelog

#1797 deps: bump minimum terraform version
  cli/internal/terraform/terraform.go
Labels: bug fix, no changelog

#1758 Add autoscaling and cluster upgrade support for AWS
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
  bazel/toolchains/go_module_deps.bzl
  bootstrapper/internal/kubernetes/kubernetes.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/terraform/terraform/iam/aws/main.tf
  docs/docs/workflows/scale.md
  docs/docs/workflows/upgrade.md
  hack/tools/go.mod
  hack/tools/go.sum
  operators/constellation-node-operator/BUILD.bazel
  operators/constellation-node-operator/controllers/nodeversion_controller.go
  operators/constellation-node-operator/controllers/pendingnode_controller.go
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
  operators/constellation-node-operator/internal/cloud/aws/client/BUILD.bazel
  operators/constellation-node-operator/internal/cloud/aws/client/api.go
  operators/constellation-node-operator/internal/cloud/aws/client/autoscaler.go
  operators/constellation-node-operator/internal/cloud/aws/client/client.go
  operators/constellation-node-operator/internal/cloud/aws/client/client_test.go
  operators/constellation-node-operator/internal/cloud/aws/client/nodeimage.go
  operators/constellation-node-operator/internal/cloud/aws/client/nodeimage_test.go
  operators/constellation-node-operator/internal/cloud/aws/client/pendingnode.go
  operators/constellation-node-operator/internal/cloud/aws/client/pendingnode_test.go
  operators/constellation-node-operator/internal/cloud/aws/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/aws/client/scalinggroup_test.go
  operators/constellation-node-operator/main.go
Labels: feature

#1753 bazel: provide semi-hermetic python toolchain
  WORKSPACE.bazel
  bazel/container/Containerfile
  bazel/toolchains/python_deps.bzl
Labels: no changelog

#1804 bazel: add Bazel shell completion scripts
  bazel/bazel-complete.bash
  bazel/ci/shellcheck.sh.in
  dev-docs/workflows/build-test-run.md
Labels: no changelog

#1685 cli: Terraform migrations on upgrade
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/helm/backup.go
  cli/internal/kubernetes/BUILD.bazel
  cli/internal/kubernetes/upgrade.go
  cli/internal/terraform/loader.go
  cli/internal/terraform/loader_test.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform_test.go
  cli/internal/upgrade/BUILD.bazel
  cli/internal/upgrade/terraform.go
  cli/internal/upgrade/terraform_test.go
  cli/internal/upgrade/upgrade.go
  e2e/internal/upgrade/upgrade_test.go
  internal/constants/constants.go
  internal/file/file.go
  internal/file/file_test.go
Labels: feature

#1809 ci: fix os image archive path
  image/upload/internal/cmd/upload.go
Labels: no changelog

#1788 cli: split image into oss and enterprise
  .github/actions/e2e_mini/action.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/release.yml
  cli/internal/cloudcmd/create.go
  cli/internal/libvirt/libvirt.go
  cli/internal/terraform/terraform.go
  e2e/miniconstellation/BUILD.bazel
  internal/config/BUILD.bazel
  internal/config/image_enterprise.go
  internal/config/image_oss.go
Labels: no changelog

#1817 docs: publish
  docs/docs/getting-started/first-steps-local.md
  docs/docs/reference/config-migration.md
  docs/versioned_docs/version-2.7/getting-started/first-steps-local.md
  docs/versioned_docs/version-2.7/getting-started/first-steps.md
  docs/versioned_docs/version-2.7/overview/clouds.md
  docs/versioned_docs/version-2.7/reference/config-migration.md
  docs/versioned_docs/version-2.7/workflows/config.md
  docs/versioned_docs/version-2.7/workflows/create.md
Labels: no changelog

#1819 ci: add pipeline to precalc launchmeasurements
  .github/workflows/aws-snp-launchmeasurement.yml
Labels: no changelog

#1822 ci: explicitly disable cgo in golangci-lint
  bazel/ci/golangci_lint.sh.in
Labels: no changelog

#1628 ci: run release workflow on temporary branch
  .github/workflows/on-release.yml
  .github/workflows/release.yml
  dev-docs/workflows/release.md
Labels: no changelog

#1828 ci: disable codeql autobuild for go
  .github/workflows/codeql.yml
Labels: no changelog

#1832 bazel: make imagefetcher visible to all subpackages
  internal/imagefetcher/BUILD.bazel
Labels: no changelog

#1803 cli: support StackIT provider on config generate
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  docs/docs/reference/cli.md
  internal/cloud/cloudprovider/cloudprovider.go
  internal/cloud/cloudprovider/cloudprovider_test.go
  internal/config/config.go
Labels: no changelog

#1835 cli: add windows amd64 build target
  bazel/toolchains/go_module_deps.bzl
  cli/BUILD.bazel
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/miniup.go
  cli/internal/cmd/miniup_cross.go
  cli/internal/cmd/miniup_linux_amd64.go
  cli/internal/terraform/loader.go
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
Labels: no changelog

#1618 bootstrapper: collect journald logs on failure
  bootstrapper/initproto/init.pb.go
  bootstrapper/initproto/init.proto
  bootstrapper/internal/initserver/BUILD.bazel
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/initserver/initserver_test.go
  bootstrapper/internal/journald/journald_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  internal/constants/constants.go
  internal/file/file.go
  internal/file/file_test.go
  internal/grpc/atlscredentials/atlscredentials_test.go
Labels: no changelog

#1833 ci: static file uploader with automatic cache invalidation
  internal/staticupload/BUILD.bazel
  internal/staticupload/delete.go
  internal/staticupload/staticupload.go
  internal/staticupload/staticupload_test.go
  internal/staticupload/upload.go
Labels: no changelog

#1841 deps: align k8s deps
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
Labels: no changelog
