Repository edgelesssys/constellation, pull requests merged in 2023-10, with the labels that each got.

#2384 docs: add observability page
  docs/docs/architecture/observability.md
  docs/docs/architecture/overview.md
  docs/sidebars.js
  docs/styles/Vocab/constellation/accept.txt
  docs/versioned_docs/version-2.11/architecture/observability.md
  docs/versioned_docs/version-2.11/architecture/overview.md
  docs/versioned_sidebars/version-2.11-sidebars.json
Labels: documentation

#2399 ci: use larger runners for os image pipeline
  .github/workflows/build-os-image.yml
Labels: no changelog

#2397 github: add AB ticket link to PR template
  .github/pull_request_template.md
Labels: no changelog

#2407 github: remove unnecessary link
  .github/pull_request_template.md
Labels: no changelog

#2378 docs: document gcp permissions needed for upgrade
  docs/docs/getting-started/install.md
Labels: documentation

#2408 csi: fix concurrent use of `cryptmapper` package
  csi/cryptmapper/cryptmapper.go
  csi/cryptmapper/cryptmapper_test.go
  csi/test/mount_integration_test.go
Labels: no changelog

#2409 Refactor Terraform to have all ports in a list
  cli/internal/terraform/terraform/aws/main.tf
  cli/internal/terraform/terraform/azure/main.tf
  cli/internal/terraform/terraform/azure/modules/load_balancer_backend/main.tf
  cli/internal/terraform/terraform/azure/modules/load_balancer_backend/variables.tf
  cli/internal/terraform/terraform/gcp/main.tf
Labels: no changelog

#2412 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2398 s3proxy: add keyservice integration
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  s3proxy/cmd/main.go
  s3proxy/deploy/README.md
  s3proxy/internal/crypto/BUILD.bazel
  s3proxy/internal/crypto/crypto.go
  s3proxy/internal/crypto/crypto_test.go
  s3proxy/internal/kms/BUILD.bazel
  s3proxy/internal/kms/kms.go
  s3proxy/internal/kms/kms_test.go
  s3proxy/internal/router/BUILD.bazel
  s3proxy/internal/router/object.go
  s3proxy/internal/router/router.go
  s3proxy/internal/router/router_test.go
Labels: no changelog

#2415 attestation: update list of accepted id key digests
  internal/attestation/idkeydigest/idkeydigest.go
Labels: no changelog

#2414 ci: use West US region for Azure e2e test until problems are resolved
  .github/actions/e2e_test/action.yml
Labels: no changelog

#2416 cli: update Azure/GCP CSI charts
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/charts/edgeless/csi/Chart.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/Chart.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  cli/internal/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/values.yaml
  cli/internal/helm/charts/edgeless/csi/charts/gcp-compute-persistent-disk-csi-driver/Chart.yaml
  cli/internal/helm/charts/edgeless/csi/charts/gcp-compute-persistent-disk-csi-driver/values.yaml
  cli/internal/helm/update-csi-charts.sh
Labels: dependencies

#2391 cli: new flag for JSON output of `constellation verify`
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  docs/docs/reference/cli.md
  internal/verify/BUILD.bazel
  internal/verify/verify.go
Labels: feature, breaking change

#2419 ci: free up disk space on GitHub hosted runners
  .github/actions/setup_bazel/action.yml
Labels: no changelog

#2395 cli: use state file on init and upgrade
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_verify/action.yml
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/iamdestroy.go
  cli/internal/cmd/iamdestroy_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/minidown.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/recover_test.go
  cli/internal/cmd/terminate.go
  cli/internal/cmd/terminate_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/helm.go
  cli/internal/helm/helm_test.go
  cli/internal/helm/loader.go
  cli/internal/helm/loader_test.go
  cli/internal/helm/overrides.go
  cli/internal/state/BUILD.bazel
  cli/internal/state/state.go
  cli/internal/state/state_test.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform/aws/outputs.tf
  cli/internal/terraform/terraform/azure/outputs.tf
  cli/internal/terraform/terraform/gcp/outputs.tf
  cli/internal/terraform/terraform/openstack/outputs.tf
  cli/internal/terraform/terraform/qemu/outputs.tf
  cli/internal/terraform/terraform_test.go
  debugd/internal/cdbg/cmd/deploy.go
  docs/docs/architecture/orchestration.md
  docs/docs/reference/cli.md
  docs/docs/workflows/create.md
  docs/docs/workflows/recovery.md
  docs/docs/workflows/terminate.md
  docs/docs/workflows/verify-cluster.md
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  internal/file/file.go
  internal/file/file_test.go
  rfc/state-file.md
Labels: feature

#2420 s3proxy: add allow-multipart flag
  s3proxy/cmd/main.go
  s3proxy/deploy/deployment-s3proxy.yaml
  s3proxy/internal/router/BUILD.bazel
  s3proxy/internal/router/handler.go
  s3proxy/internal/router/router.go
Labels: no changelog

#2418 docs: add note about current AWS CVM issues
  docs/docs/getting-started/first-steps.md
  docs/versioned_docs/version-2.11/getting-started/first-steps.md
Labels: no changelog

#2417 s3proxy: add new page to documentation
  docs/docs/architecture/encrypted-storage.md
  docs/docs/getting-started/examples/filstash-s3proxy.md
  docs/docs/workflows/s3proxy.md
  docs/sidebars.js
  docs/styles/Vocab/constellation/accept.txt
  s3proxy/deploy/deployment-s3proxy.yaml
Labels: documentation

#2426 ci: start v2.13-pre window
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  version.txt
Labels: no changelog

#2424 cli: fix broken verify test due to jq usage insteaf of yq
  .github/actions/e2e_verify/action.yml
Labels: no changelog

#2428 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2423 renovate: relax rules to allow updates to minor versions
  renovate.json5
Labels: bug fix, no changelog

#2441 s3proxy: remove unnecessary pull secret
  docs/docs/getting-started/examples/filestash-s3proxy.md
  docs/versioned_docs/version-2.12/getting-started/examples/filestash-s3proxy.md
  s3proxy/deploy/README.md
  s3proxy/deploy/deployment-s3proxy.yaml
Labels: no changelog

#2445 docs: extend filestash example with more regions
  docs/docs/getting-started/examples/filestash-s3proxy.md
  docs/versioned_docs/version-2.12/getting-started/examples/filestash-s3proxy.md
  s3proxy/deploy/deployment-s3proxy.yaml
Labels: documentation

#2450 Deps: bump Go to 1.21.3
  .github/actions/setup_bazel_nix/action.yml
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  WORKSPACE.bazel
  bazel/go/go.nix
  go.work
Labels: dependencies

#2440 cli: remove old migration steps and id-file references
  CODEOWNERS
  cli/internal/clusterid/BUILD.bazel
  cli/internal/clusterid/id.go
  cli/internal/clusterid/id_test.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/terminate.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/kubecmd/BUILD.bazel
  cli/internal/kubecmd/kubecmd.go
  cli/internal/state/BUILD.bazel
  cli/internal/state/state.go
  cli/internal/state/state_test.go
  internal/constants/constants.go
Labels: no changelog

#2448 docs: add s3proxy to features
  README.md
  docs/docs/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.12/overview/confidential-kubernetes.md
Labels: no changelog

#2451 ci: remove python from codeql
  .github/workflows/codeql.yml
Labels: no changelog

#2452 ci: execute unit tests and tidy check against merge of PR branch and main
  .github/workflows/test-tidy.yml
  .github/workflows/test-unittest.yml
Labels: no changelog

#2456 bump golang.org/x/net to v0.17.0
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
Labels: dependencies

#2425 cli: refactor flag parsing code
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/cmd.go
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configfetchmeasurements_test.go
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/iam.go
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/iamcreate_test.go
  cli/internal/cmd/iamcreateaws.go
  cli/internal/cmd/iamcreateazure.go
  cli/internal/cmd/iamcreategcp.go
  cli/internal/cmd/iamdestroy.go
  cli/internal/cmd/iamdestroy_test.go
  cli/internal/cmd/iamupgradeapply.go
  cli/internal/cmd/iamupgradeapply_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/recover_test.go
  cli/internal/cmd/status.go
  cli/internal/cmd/status_test.go
  cli/internal/cmd/terminate.go
  cli/internal/cmd/terminate_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  go.mod
Labels: no changelog

#2459 ci: add missing quotation marks for region flag
  .github/actions/constellation_iam_create/action.yml
  .github/actions/e2e_test/action.yml
Labels: no changelog

#2453 cli: add field docs to the state file
  cli/internal/state/BUILD.bazel
  cli/internal/state/state.go
  cli/internal/state/state_doc.go
  cli/internal/state/state_test.go
Labels: feature

#2455 cli: generate state file during `constellation config generate`
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  docs/docs/getting-started/first-steps.md
  docs/docs/reference/cli.md
Labels: feature

#2463 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2460 cli: use custom byte-slice marshalling for state file
  bazel/toolchains/go_module_deps.bzl
  cli/internal/state/BUILD.bazel
  cli/internal/state/state.go
  cli/internal/state/state_doc.go
  cli/internal/state/state_test.go
  cli/internal/terraform/BUILD.bazel
  cli/internal/terraform/terraform_test.go
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
Labels: no changelog

#2471 image: move mkosi settings into their actual sections
  image/base/mkosi.conf
  image/initrd/mkosi.conf
  image/system/mkosi.conf
Labels: no changelog

#2473 image: use systemd-dissect from the host when calculating measurements
  .github/workflows/build-os-image.yml
  image/measured-boot/cmd/BUILD.bazel
Labels: no changelog

#2442 image: add rpm database as build output
  .github/workflows/build-os-image.yml
  image/base/BUILD.bazel
  image/base/mkosi.conf
  image/base/mkosi.postinst
  image/initrd/mkosi.conf
  image/system/BUILD.bazel
  image/system/mkosi.conf
Labels: no changelog

#2470 cli: create or read state file during `constellation create`
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/state/state.go
  cli/internal/state/state_test.go
Labels: no changelog

#2429 api: for Azure attestationconfigapi use TCB values from SNP report instead of MAA token
  .github/actions/e2e_verify/action.yml
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cmd/verify.go
  go.mod
  go.sum
  internal/api/attestationconfigapi/cli/BUILD.bazel
  internal/api/attestationconfigapi/cli/delete.go
  internal/api/attestationconfigapi/cli/e2e/test.sh.in
  internal/api/attestationconfigapi/cli/main.go
  internal/api/attestationconfigapi/cli/main_test.go
  internal/verify/verify.go
Labels: no changelog

#2476 ci: build rpmdb explicitly
  .github/workflows/build-os-image.yml
Labels: no changelog

#2475 align tf output vars with CLI parsing
  cli/internal/terraform/terraform/openstack/outputs.tf
  cli/internal/terraform/terraform/qemu/outputs.tf
Labels: no changelog

#2474 helm: add gcp ccm permissions for internal LBs
  cli/internal/helm/BUILD.bazel
  cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/templates/gcp-clusterrolebinding.yaml
  cli/internal/helm/testdata/GCP/constellation-services/charts/ccm/templates/gcp-clusterrolebinding.yaml
Labels: bug fix

#2479 ci: remove force flag from CLI commands
  .github/actions/constellation_create/action.yml
  .github/actions/e2e_recover/action.yml
  .github/actions/e2e_verify/action.yml
Labels: no changelog

#2485 cli: set image version in tests to stamped binary version
  cli/internal/cmd/init_test.go
Labels: no changelog

#2483 ci: pick Azure region randomly
  .github/actions/e2e_test/action.yml
  .github/actions/pick_assignee/action.yml
  .github/actions/pick_azure_region/action.yml
Labels: no changelog

#2488 nix: flake update
  flake.lock
  flake.nix
Labels: no changelog

#2498 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2489 cli: remove unnecessary check from QEMU rollbacker
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/rollback.go
  cli/internal/cloudcmd/rollback_test.go
Labels: no changelog

#2499 ci: fix win build
  .github/workflows/e2e-windows.yml
Labels: no changelog

#2481 terraform: always output node cidr
  cli/internal/helm/loader_test.go
  cli/internal/state/state.go
  cli/internal/state/state_doc.go
  cli/internal/state/state_test.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform/aws/main.tf
  cli/internal/terraform/terraform/aws/outputs.tf
  cli/internal/terraform/terraform/azure/main.tf
  cli/internal/terraform/terraform/azure/outputs.tf
  cli/internal/terraform/terraform/openstack/outputs.tf
  cli/internal/terraform/terraform/qemu/main.tf
  cli/internal/terraform/terraform/qemu/outputs.tf
  cli/internal/terraform/terraform_test.go
Labels: no changelog

#2500 cli: increase kubecmd retry limit
  cli/internal/kubecmd/kubecmd.go
  cli/internal/kubecmd/kubecmd_test.go
Labels: no changelog

#2411 readme: update links
  README.md
Labels: no changelog

#2480 validation: add generic validation framework
  internal/validation/BUILD.bazel
  internal/validation/constraints.go
  internal/validation/errors.go
  internal/validation/errors_test.go
  internal/validation/validation.go
  internal/validation/validation_test.go
Labels: no changelog

#2449 cli: common backend for `init` and `upgrade apply` commands
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/serviceaccount.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/applyhelm.go
  cli/internal/cmd/applyinit.go
  cli/internal/cmd/applyterraform.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/kubecmd/kubecmd.go
  internal/config/attestation.go
Labels: no changelog

#2505 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2501 cli: refactor terraform code to be update/create agnostic
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clusterupgrade.go
  cli/internal/cloudcmd/clusterupgrade_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/iam.go
  cli/internal/cloudcmd/iamupgrade.go
  cli/internal/cloudcmd/tfupgrade.go
  cli/internal/cloudcmd/tfupgrade_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/terraform/loader.go
  cli/internal/terraform/loader_test.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform_test.go
  internal/constants/constants.go
Labels: no changelog

#2522 cli: init should not call terraform
  cli/internal/cmd/init.go
Labels: no changelog

#2515 cli: retry fetching of JoinConfig during init process
  cli/internal/kubecmd/kubecmd.go
Labels: no changelog

#2484 cli: add `constellation apply` command to replace `init` and `upgrade apply`
  .github/actions/constellation_create/action.yml
  .github/workflows/e2e-windows.yml
  cli/cmd/root.go
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/upgradeapply.go
  docs/docs/reference/cli.md
  e2e/internal/upgrade/upgrade_test.go
Labels: feature

#2487 docs: refer to apply command instead of `init` or `upgrade apply`
  debugd/README.md
  dev-docs/workflows/debug-cluster.md
  dev-docs/workflows/release.md
  dev-docs/workflows/versions-support.md
  docs/docs/architecture/attestation.md
  docs/docs/architecture/orchestration.md
  docs/docs/getting-started/first-steps-local.md
  docs/docs/getting-started/first-steps.md
  docs/docs/workflows/create.md
  docs/docs/workflows/terminate.md
  docs/docs/workflows/troubleshooting.md
  docs/docs/workflows/upgrade.md
  docs/docs/workflows/verify-cluster.md
  docs/screencasts/docker/create-cluster.expect
  docs/screencasts/docker/github-readme.expect
  e2e/internal/upgrade/upgrade.go
  internal/kms/README.md
  operators/constellation-node-operator/README.md
Labels: documentation

#2472 ci: add e2e test for self-managed infrastructure
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_destroy/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/self_managed_create/action.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-manual-internal.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-upgrade.yml
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/clusterupgrade.go
  cli/internal/cloudcmd/create.go
  cli/internal/cmd/init.go
  hack/image-fetch/BUILD.bazel
  hack/image-fetch/main.go
  hack/image-fetch/main_test.go
  hack/maa-patch/BUILD.bazel
  hack/maa-patch/main.go
  hack/maa-patch/main_test.go
  internal/maa/BUILD.bazel
  internal/maa/maa.go
  internal/maa/patch.go
  internal/maa/patch_test.go
Labels: no changelog

#2528 terraform: revert GCP provider upgrade
  cli/internal/terraform/terraform/gcp/.terraform.lock.hcl
  cli/internal/terraform/terraform/gcp/main.tf
  cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
  cli/internal/terraform/terraform/gcp/modules/internal_load_balancer/main.tf
  cli/internal/terraform/terraform/gcp/modules/jump_host/main.tf
  cli/internal/terraform/terraform/gcp/modules/loadbalancer/main.tf
  cli/internal/terraform/terraform/iam/gcp/.terraform.lock.hcl
  cli/internal/terraform/terraform/iam/gcp/main.tf
Labels: no changelog

#2534 hack: don't limit memory in Metricbeat daemonset
  hack/logcollector/internal/templates/metricbeat/values-all-nodes.yml
  hack/logcollector/internal/templates/metricbeat/values-control-plane.yml
Labels: no changelog

#2526 cli: fix apply flag issues
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/upgradeapply_test.go
Labels: no changelog

#2535 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2525 docs: align self-managed infrastructure docs with e2e worfklow
  docs/docs/workflows/create.md
Labels: documentation

#2532 image: use all of cilium's sysctl overrides
  image/base/mkosi.skeleton/usr/lib/sysctl.d/10-cilium.conf
  image/base/mkosi.skeleton/usr/lib/sysctl.d/99-zzz-override_cilium.conf
Labels: no changelog

#2529 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2536 cli: only create Terraform client when needed
  cli/internal/cmd/apply.go
  cli/internal/cmd/applyterraform.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/upgradeapply_test.go
Labels: no changelog

#2537 ci: mark self-managed infrastructure tests
  .github/actions/cdbg_deploy/action.yml
  .github/actions/constellation_create/action.yml
  .github/actions/deploy_logcollection/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/notify_failure/action.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#2540 ci: increase collection period for Metricbeat
  debugd/metricbeat/templates/metricbeat.yml
Labels: no changelog

#2542 debugd: add missing `self-managed-infra` field
  debugd/internal/debugd/logcollector/fields.go
Labels: no changelog

#2538 ci: force delete files on self-managed destroy
  .github/actions/constellation_destroy/action.yml
Labels: no changelog

#2513 cli: unify `cloudcmd` create and upgrade code
  cli/internal/cloudcmd/BUILD.bazel
  cli/internal/cloudcmd/apply.go
  cli/internal/cloudcmd/apply_test.go
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/clusterupgrade.go
  cli/internal/cloudcmd/clusterupgrade_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cloudcmd/iam_test.go
  cli/internal/cloudcmd/iamupgrade.go
  cli/internal/cloudcmd/rollback.go
  cli/internal/cloudcmd/terminate.go
  cli/internal/cloudcmd/terminate_test.go
  cli/internal/cloudcmd/tfplan.go
  cli/internal/cloudcmd/tfplan_test.go
  cli/internal/cloudcmd/tfvars.go
  cli/internal/cloudcmd/tfvars_test.go
  cli/internal/cmd/apply.go
  cli/internal/cmd/applyterraform.go
  cli/internal/cmd/cloud.go
  cli/internal/cmd/cloud_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/cmd/upgradeapply_test.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/upgradecheck_test.go
  cli/internal/libvirt/libvirt.go
  internal/file/file.go
  internal/file/file_test.go
Labels: no changelog
