Repository edgelesssys/constellation, pull requests merged in 2023-02, with the labels that each got.

#1034 cli: refactor iam create command
  cli/internal/cmd/cloud.go
  cli/internal/cmd/iam.go
  cli/internal/cmd/iam_test.go
  cli/internal/cmd/iamcreateaws.go
  cli/internal/cmd/iamcreateaws_test.go
  cli/internal/cmd/iamcreateazure.go
  cli/internal/cmd/iamcreateazure_test.go
  cli/internal/cmd/iamcreategcp.go
  cli/internal/cmd/iamcreategcp_test.go
Labels: no changelog

#1128 build: specify C toolchains correctly
  .bazelrc
  WORKSPACE.bazel
Labels: bug fix, no changelog

#1132 ci: allow ci reference workflow to create pr
  .github/workflows/update-cli-reference.yml
Labels: no changelog

#1130 ci: add containerized libvirt build workflow
  .github/workflows/build-libvirt-image.yml
  .github/workflows/build-micro-service-manual.yml
  .github/workflows/release.yml
  cli/internal/libvirt/Dockerfile
Labels: no changelog

#1138 ci: fix location of cli docgen output
  .github/workflows/update-cli-reference.yml
Labels: no changelog

#1146 cli: enable jumbo frames for GCP VPCs
  cli/internal/terraform/terraform/gcp/main.tf
Labels: bug fix

#1153 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1150 Enable cryptsetup read/write workqueue bypass
  csi/cryptmapper/cryptmapper.go
  disk-mapper/internal/mapper/mapper.go
  internal/cryptsetup/cryptsetup.go
Labels: feature

#1012 internal: use go-kms-wrapping for KMS backends
  disk-mapper/internal/recoveryserver/recoveryserver_test.go
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
  internal/kms/README.md
  internal/kms/kms/aws/aws.go
  internal/kms/kms/aws/aws_test.go
  internal/kms/kms/azure/azure.go
  internal/kms/kms/azure/azure_test.go
  internal/kms/kms/azure/hsm.go
  internal/kms/kms/azure/hsm_test.go
  internal/kms/kms/cluster/cluster.go
  internal/kms/kms/cluster/cluster_test.go
  internal/kms/kms/gcp/gcp.go
  internal/kms/kms/gcp/gcp_test.go
  internal/kms/kms/internal/internal.go
  internal/kms/kms/internal/internal_test.go
  internal/kms/kms/kms.go
  internal/kms/kms/util/crypto.go
  internal/kms/kms/util/crypto_test.go
  internal/kms/setup/setup.go
  internal/kms/setup/setup_test.go
  internal/kms/test/aws_test.go
  internal/kms/test/azure_test.go
  internal/kms/test/gcp_test.go
  internal/kms/test/integration_test.go
  internal/kms/uri/uri.go
  keyservice/cmd/main.go
  keyservice/internal/server/server_test.go
  keyservice/internal/test/aws_test.go
  keyservice/internal/test/azure_test.go
  keyservice/internal/test/gcp_test.go
  keyservice/internal/test/integration_test.go
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
Labels: no changelog

#1151 bootstrapper: retry helm chart installation
  bootstrapper/internal/helm/helm.go
Labels: bug fix

#1127 cli: add debug logging to iam create command
  cli/internal/cmd/create.go
  cli/internal/cmd/iam.go
  cli/internal/cmd/iam_test.go
Labels: feature

#1152 ci: refactor image measurement generation
  .github/actions/e2e_verify/action.yml
  .github/workflows/build-os-image.yml
  .github/workflows/generate-measurements.yml
  .github/workflows/release.yml
  rfc/apis.md
  rfc/image-api.md
Labels: no changelog

#1155 config: fix incorrect kubernetes version validation
  internal/config/config.go
  internal/config/validation.go
  internal/versions/versions.go
Labels: bug fix

#1133 init: create kubeconfig file with unique user/cluster name
  .github/actions/constellation_create/action.yml
  bootstrapper/cmd/bootstrapper/test.go
  bootstrapper/initproto/init.pb.go
  bootstrapper/initproto/init.proto
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/initserver/initserver_test.go
  bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
  bootstrapper/internal/kubernetes/k8sapi/kubeadm_config.go
  bootstrapper/internal/kubernetes/k8sutil.go
  bootstrapper/internal/kubernetes/kubeconfig.go
  bootstrapper/internal/kubernetes/kubeconfig_test.go
  bootstrapper/internal/kubernetes/kubernetes.go
  bootstrapper/internal/kubernetes/kubernetes_test.go
  cli/internal/cloudcmd/create.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cmd/cloud.go
  cli/internal/cmd/cloud_test.go
  cli/internal/cmd/configgenerate_test.go
  cli/internal/cmd/create.go
  cli/internal/cmd/create_test.go
  cli/internal/cmd/iam_test.go
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/miniup.go
  docs/static/img/shell-windowframe.svg
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/validation.go
  internal/constants/constants.go
Labels: feature

#1136 cli: add option to automatically merge kubeconfig file on init
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
Labels: feature

#1165 ci: fix workdir of apko base image build
  .github/actions/build_apko/action.yml
  .github/actions/build_apko/build_and_sign.sh
  .github/workflows/build-apko-image.yml
Labels: no changelog

#1170 cli: adapt "upgrade check" reference to conventions
  cli/cmd/root.go
  cli/internal/cmd/upgradecheck.go
Labels: no changelog

#1148 cli: fix iam rollback
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/create_test.go
  cli/internal/cloudcmd/rollback.go
  cli/internal/cloudcmd/rollback_test.go
  cli/internal/cloudcmd/terminate.go
  cli/internal/cloudcmd/terminate_test.go
  cli/internal/cmd/iam.go
  cli/internal/cmd/iam_test.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform_test.go
Labels: bug fix

#1173 ci: fix yq command for new k8s version format
  .github/actions/constellation_create/action.yml
Labels: bug fix, no changelog

#1164 operators: move api into a dedicated submodule
  go.work
  operators/constellation-node-operator/Makefile
  operators/constellation-node-operator/api/api.go
  operators/constellation-node-operator/api/go.mod
  operators/constellation-node-operator/api/go.sum
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/internal/cloud/gcp/client/pendingnode.go
Labels: no changelog

#1174 cli: fix init with k8s version without v prefix
  cli/internal/cmd/init.go
  cli/internal/cmd/init_test.go
Labels: bug fix, no changelog

#1171 ci: update vale action
  .github/workflows/docs-vale.yml
Labels: no changelog

#1169 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1177 ci: better naming for spelling check workflow
  .github/workflows/docs-vale.yml
Labels: no changelog

#1176 renovate: group hashicorp/go-kms-wrapping upgrades
  renovate.json
Labels: no changelog

#1179 cli: add name of build type to version cmd output
  cli/internal/cmd/version.go
  internal/constants/enterprise.go
  internal/constants/oss.go
Labels: feature

#1183 cli: add missing logger to versionCollector object
  cli/internal/cmd/upgradecheck.go
Labels: bug fix, no changelog

#1172 deps: vendor node-maintenance-operator api
  .github/workflows/check-licenses.yml
  .golangci.yml
  3rdparty/node-maintenance-operator/LICENSE
  3rdparty/node-maintenance-operator/api/v1beta1/download.sh
  3rdparty/node-maintenance-operator/api/v1beta1/groupversion_info.go
  3rdparty/node-maintenance-operator/api/v1beta1/nodemaintenance_types.go
  3rdparty/node-maintenance-operator/api/v1beta1/v1beta1.go
  3rdparty/node-maintenance-operator/api/v1beta1/zz_generated.deepcopy.go
  3rdparty/node-maintenance-operator/go.mod
  3rdparty/node-maintenance-operator/go.sum
  go.work
  operators/constellation-node-operator/controllers/nodeversion_controller.go
  operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go
  operators/constellation-node-operator/controllers/nodeversion_watches.go
  operators/constellation-node-operator/controllers/nodeversion_watches_test.go
  operators/constellation-node-operator/controllers/schemes_test.go
  operators/constellation-node-operator/controllers/suite_test.go
  operators/constellation-node-operator/go.mod
  operators/constellation-node-operator/go.sum
  operators/constellation-node-operator/main.go
Labels: dependencies, no changelog

#1181 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1184 image: upgrade to Linux 6.1.12 for Azure
  image/Makefile
  image/mkosi.files/mkosi.azure.conf
Labels: dependencies, bug fix

#1203 hack: add api module to container during build
  hack/qemu-metadata-api/Dockerfile
Labels: bug fix, no changelog

#1207 cli: option to disable spinner via environment variable
  cli/internal/cmd/spinner.go
  cli/internal/cmd/terminate.go
  internal/constants/constants.go
Labels: feature

#1209 cli: fix incorrect output for single worker/control-plane clusters
  cli/internal/cmd/create.go
Labels: bug fix

#1208 Allow unset 'name' key but print warning if unset
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/validation.go
Labels: no changelog

#1175 rfc: specify cli version api
  rfc/apis.md
  rfc/cli-api.md
  rfc/image-api.md
Labels: no changelog

#1210 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1213 ci: fix: upload signature of measurements.
  .github/workflows/build-os-image.yml
Labels: bug fix, no changelog

#1214 ci: use correct container name to tag joinservice
  .github/workflows/build-joinservice-image.yml
Labels: bug fix, no changelog

#1217 docs: extend docs on Terraform iam resource destruction
  docs/docs/workflows/config.md
Labels: documentation, no changelog

#1212 docs: fix terminate docs filename
  docs/docs/workflows/terminate.md
Labels: documentation, no changelog

#1219 Fix links and clean lycheeignore
  .lycheeignore
  docs/docs/architecture/components.md
  docs/docs/architecture/images.md
  docs/docs/architecture/keys.md
  docs/docs/architecture/networking.md
  docs/versioned_docs/version-2.0/architecture/components.md
  docs/versioned_docs/version-2.0/architecture/images.md
  docs/versioned_docs/version-2.0/architecture/keys.md
  docs/versioned_docs/version-2.0/architecture/networking.md
  docs/versioned_docs/version-2.1/architecture/components.md
  docs/versioned_docs/version-2.1/architecture/images.md
  docs/versioned_docs/version-2.1/architecture/keys.md
  docs/versioned_docs/version-2.1/architecture/networking.md
  docs/versioned_docs/version-2.2/architecture/components.md
  docs/versioned_docs/version-2.2/architecture/images.md
  docs/versioned_docs/version-2.2/architecture/keys.md
  docs/versioned_docs/version-2.2/architecture/networking.md
  docs/versioned_docs/version-2.3/architecture/components.md
  docs/versioned_docs/version-2.3/architecture/images.md
  docs/versioned_docs/version-2.3/architecture/keys.md
  docs/versioned_docs/version-2.3/architecture/networking.md
  docs/versioned_docs/version-2.4/architecture/components.md
  docs/versioned_docs/version-2.4/architecture/images.md
  docs/versioned_docs/version-2.4/architecture/keys.md
  docs/versioned_docs/version-2.4/architecture/networking.md
  docs/versioned_docs/version-2.5/architecture/components.md
  docs/versioned_docs/version-2.5/architecture/images.md
  docs/versioned_docs/version-2.5/architecture/keys.md
  docs/versioned_docs/version-2.5/architecture/networking.md
Labels: no changelog

#1223 cli: upgrade apply uses correct measurements key
  cli/internal/cmd/upgradeapply.go
  internal/config/config.go
Labels: bug fix, no changelog

#1216 docs: mention 'needs-backport' label in release process
  dev-docs/workflows/release.md
Labels: documentation, no changelog

#1222 config: allow k8s version MAJOR.MINOR for v2.6
  internal/config/config.go
  internal/config/config_test.go
  internal/config/validation.go
Labels: bug fix, no changelog

#1227 ci: add missing ci token
  .github/workflows/test-go-generate.yml
  .github/workflows/test-tf.yml
  .github/workflows/test-tidy.yml
Labels: no changelog

#1228 renovate: update transitive Go dependencies
  renovate.json
Labels: no changelog

#1229 ci: add missing replaced mod files to docker build
  .github/actions/versionsapi/Dockerfile
  hack/qemu-metadata-api/Dockerfile
Labels: no changelog

#1188 ci: fix self trigger paths of workflows
  .github/workflows/codeql.yml
  .github/workflows/test-govulncheck.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-shellcheck.yml
  .github/workflows/test-shellfmt.yml
  .github/workflows/test-tf.yml
  .github/workflows/test-tfsec.yml
  .github/workflows/test-tidy.yml
  .github/workflows/test-unittest.yml
Labels: no changelog

#1158 ci: integrate automatic iam creation in e2e test
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_iam_create/action.yml
  .github/actions/constellation_iam_destroy/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-manual.yml
  .github/workflows/e2e-test-weekly.yml
  cli/internal/cmd/iam.go
Labels: no changelog

#1226 cli: add `--kubernetes` flag to `config generate`
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/configgenerate_test.go
  internal/config/validation.go
Labels: feature

#1248 ci: ignore GHSA-r2h5-3hgw-8j34 in grype
  .grype.yaml
Labels: no changelog

#1205 cli: refer to --force and --config flags
  cli/internal/cmd/miniup.go
  internal/config/validation.go
Labels: no changelog

#1247 iam: assign uami role to base resource group
  cli/internal/terraform/terraform/iam/azure/main.tf
Labels: bug fix, needs backport

#1224 cli: add `config kubernetes-versions` subcommand
  cli/internal/cmd/config.go
  cli/internal/cmd/configkubernetesversions.go
  docs/docs/architecture/versions.md
  docs/docs/workflows/config.md
  internal/versions/versions.go
Labels: feature

#1245 helm: retry on connection refused
  bootstrapper/internal/helm/helm.go
  bootstrapper/internal/kubernetes/kubewaiter/kubewaiter.go
Labels: bug fix, needs backport

#1249 repo: hand off code ownership
  CODEOWNERS
Labels: no changelog

#1120 ci: update Syft to 0.72.0 and Grype to 0.57.1
  .github/actions/container_sbom/action.yml
  .github/actions/install_syft_grype/action.yml
  .github/workflows/release-cli.yml
Labels: no changelog

#1221 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1258 ci: specify URL predicate because shortnames are unreliable
  .github/actions/container_sbom/action.yml
Labels: no changelog

#1266 ci: fix comparision of ref name
  .github/actions/build_ko/action.yml
Labels: no changelog

#946 cli: iam destroy
  cli/internal/cloudcmd/clients.go
  cli/internal/cloudcmd/clients_test.go
  cli/internal/cloudcmd/iam.go
  cli/internal/cloudcmd/iam_test.go
  cli/internal/cmd/cloud.go
  cli/internal/cmd/cloud_test.go
  cli/internal/cmd/iam.go
  cli/internal/cmd/iamdestroy.go
  cli/internal/cmd/iamdestroy_test.go
  cli/internal/terraform/terraform.go
  docs/docs/workflows/config.md
Labels: feature

#1261 deps: update apk package hashes
  apko/SHA256SUMS-apk-amd64
Labels: dependencies

#1218 ci: add cli k8s compatibility table artifact upload to ci
  .github/workflows/build-os-image.yml
  hack/cli-k8s-compatibility/main.go
  hack/go.mod
  hack/go.sum
  internal/versionsapi/client/client.go
  internal/versionsapi/cliinfo.go
  internal/versionsapi/cliinfo_test.go
  internal/versionsapi/fetcher/fetcher.go
  internal/versionsapi/version.go
  internal/versionsapi/version_test.go
Labels: no changelog

#1270 ci: fix build-ko action bash
  .github/actions/build_ko/action.yml
Labels: no changelog

#1260 cli: fix force flag debug print in init
  cli/internal/cmd/init.go
Labels: bug fix, no changelog

#1159 image: verbose debugging options
  disk-mapper/cmd/main.go
  disk-mapper/internal/setup/setup.go
  image/Makefile
  image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/prepare-state-disk.service
  image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/prepare-state-disk.sh
  image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset
  image/mkosi.skeleton/usr/lib/systemd/system/constellation-bootstrapper.service
  image/mkosi.skeleton/usr/lib/systemd/system/constellation-upgrade-agent.service
  image/mkosi.skeleton/usr/lib/systemd/system/export_constellation_debug.service
Labels: feature

#1271 ko: update apko base images
  .ko.yaml
Labels: no changelog

#1273 ci: fix quoting of versionsapi flags
  .github/actions/versionsapi/action.yml
Labels: no changelog

#1253 ci: fix release pipeline
  .github/workflows/release.yml
Labels: bug fix, no changelog

#1279 ci: ensure ci prs trigger workflows
  .github/workflows/package-hasher.yml
  .github/workflows/release.yml
  .github/workflows/update-cli-reference.yml
Labels: no changelog

#1286 image: update to Linux 6.1.14 for Azure
  image/Makefile
  image/mkosi.files/mkosi.azure.conf
Labels: dependencies

#1283 cli: add basic support for `constellation create` on OpenStack
  .github/actions/os_build_variables/action.yml
  .github/workflows/build-os-image.yml
  cli/internal/cloudcmd/create.go
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/create.go
  cli/internal/image/image.go
  cli/internal/image/image_test.go
  cli/internal/terraform/terraform/openstack/.terraform.lock.hcl
  cli/internal/terraform/terraform/openstack/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/outputs.tf
  cli/internal/terraform/terraform/openstack/modules/instance_group/variables.tf
  cli/internal/terraform/terraform/openstack/modules/loadbalancer/main.tf
  cli/internal/terraform/terraform/openstack/modules/loadbalancer/variables.tf
  cli/internal/terraform/terraform/openstack/outputs.tf
  cli/internal/terraform/terraform/openstack/variables.tf
  cli/internal/terraform/variables.go
  debugd/cmd/debugd/debugd.go
  disk-mapper/cmd/main.go
  image/Makefile
  image/README.md
  image/mkosi.files/mkosi.openstack.conf
  image/upload/upload_aws.sh
  image/upload/upload_azure.sh
  image/upload/upload_gcp.sh
  image/upload/upload_openstack.sh
  image/upload/upload_qemu.sh
  internal/cloud/cloudprovider/cloudprovider.go
  internal/cloud/cloudprovider/cloudprovider_test.go
  internal/cloud/cloudprovider/provider_string.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/config/validation.go
  internal/versionsapi/imageinfo.go
  internal/versionsapi/imageinfo_test.go
  rfc/image-api.md
Labels: feature

#1292 docs: update cli reference
  docs/docs/reference/cli.md
Labels: no changelog

#1272 ci: use iam destroy command for resource destruction
  .github/actions/constellation_iam_destroy/action.yml
  .github/workflows/e2e-test-manual.yml
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/iamcreate_test.go
  cli/internal/cmd/iamdestroy.go
Labels: no changelog

#1259 cli: handle invalid upgrades for microservice consistently
  cli/internal/cloudcmd/upgrade.go
  cli/internal/cloudcmd/upgrade_test.go
  cli/internal/cmd/upgradeapply.go
  cli/internal/helm/client.go
  cli/internal/helm/client_test.go
  internal/compatibility/compatibility.go
Labels: no changelog

#1256 internal: add custom version type
  internal/semver/semver.go
  internal/semver/semver_test.go
Labels: no changelog

#1263 docs: add docs on general Terraform usage
  docs/docs/architecture/orchestration.md
  docs/docs/getting-started/first-steps.md
  docs/docs/reference/terraform.md
  docs/docs/workflows/config.md
  docs/docs/workflows/create.md
  docs/docs/workflows/terminate.md
  docs/sidebars.js
Labels: documentation

#1264 internal: add logging to attestation issuer
  bootstrapper/cmd/bootstrapper/main.go
  disk-mapper/cmd/main.go
  internal/attestation/aws/issuer.go
  internal/attestation/azure/azure.go
  internal/attestation/azure/snp/issuer.go
  internal/attestation/azure/trustedlaunch/issuer.go
  internal/attestation/azure/trustedlaunch/trustedlaunch_test.go
  internal/attestation/gcp/issuer.go
  internal/attestation/qemu/issuer.go
  internal/attestation/vtpm/attestation.go
  internal/attestation/vtpm/attestation_test.go
  verify/cmd/main.go
Labels: feature

#1293 docs: update cli reference
  docs/docs/reference/cli.md
Labels: no changelog

#1287 config: use toPtr func to get pointers
  internal/config/config.go
  internal/config/config_test.go
Labels: no changelog

#1309 ci: pin ko version
  .github/actions/build_ko/action.yml
  .github/workflows/build-keyservice-image.yml
Labels: no changelog
