Repository edgelesssys/constellation, pull requests merged in 2024-08, with the labels that each got.

#3275 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3281 renovate: group non-core bazel dependency updates
  renovate.json5
Labels: dependencies

#3284 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3290 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3296 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3297 ci: give scheduled image builds more time between executions
  .github/workflows/build-os-image-scheduled.yml
Labels: no changelog

#3305 renovate: schedule dependency updates
  renovate.json5
Labels: no changelog

#3307 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3309 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3310 image: document uidmap dependency
  image/README.md
Labels: no changelog

#3311 docs: remove date from "feature status of clouds" page
  docs/docs/overview/clouds.md
  docs/versioned_docs/version-2.17/overview/clouds.md
Labels: no changelog

#3312 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3314 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3316 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3318 Add files via upload
  README.md
  docs/static/img/BannerConstellationanimated.svg
  docs/static/img/banner.svg
Labels: no changelog

#3324 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3326 docs: remove deprecated master-secret flag from recovery
  docs/docs/workflows/recovery.md
  docs/versioned_docs/version-2.17/workflows/recovery.md
Labels: documentation, no changelog

#3329 logging: reduce grpc logging noise
  bootstrapper/cmd/bootstrapper/main.go
  bootstrapper/internal/initserver/initserver.go
  debugd/internal/debugd/server/server.go
  disk-mapper/internal/recoveryserver/recoveryserver.go
  internal/logger/grpclogger.go
  internal/logger/levelhandler.go
  internal/logger/log.go
  joinservice/internal/server/server.go
  keyservice/internal/server/server.go
  upgrade-agent/cmd/main.go
  upgrade-agent/internal/server/server.go
  verify/server/server.go
Labels: no changelog

#3330 terraform-provider: document MAA patching more prominently
  terraform-provider-constellation/docs/data-sources/attestation.md
  terraform-provider-constellation/examples/full/azure/main.tf
  terraform-provider-constellation/internal/provider/attestation_data_source.go
Labels: no changelog
