Repository edgelesssys/constellation, pull requests merged in 2024-03, with the labels that each got.

#2963 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2966 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2967 ci: use collision resistant name for Terraform e2e test
  .github/workflows/e2e-test-provider-example.yml
  terraform-provider-constellation/examples/full/azure/main.tf
  terraform-provider-constellation/examples/full/gcp/main.tf
Labels: no changelog

#2968 bootstrapper: bounded retry of k8s join
  bootstrapper/internal/joinclient/joinclient.go
  bootstrapper/internal/joinclient/joinclient_test.go
Labels: bug fix, no changelog

#2970 docs: add installation instructions for the Windows CLI variant
  docs/docs/getting-started/install.md
  docs/docs/workflows/verify-cli.md
  docs/versioned_docs/version-2.16/getting-started/install.md
  docs/versioned_docs/version-2.16/workflows/verify-cli.md
Labels: no changelog

#2976 cli: retry auth handshake deadline exceeded errors in CLI and Terraform
  internal/grpc/retry/retry.go
  internal/grpc/retry/retry_test.go
Labels: bug fix

#2978 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2979 docs: add runtime measurement table for Constellation v2.16
  docs/versioned_docs/version-2.16/architecture/attestation.md
Labels: no changelog

#2980 docs: remove steps for STACKIT credentials in config
  docs/docs/getting-started/first-steps.md
  docs/versioned_docs/version-2.16/getting-started/first-steps.md
Labels: no changelog

#2971 bootstrapper: wipe disk and reboot on non-recoverable error
  bootstrapper/cmd/bootstrapper/run.go
  bootstrapper/internal/diskencryption/diskencryption.go
  bootstrapper/internal/initserver/BUILD.bazel
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/initserver/initserver_test.go
  bootstrapper/internal/joinclient/BUILD.bazel
  bootstrapper/internal/joinclient/joinclient.go
  bootstrapper/internal/joinclient/joinclient_test.go
  csi/test/mount_integration_test.go
  disk-mapper/internal/test/integration_test.go
Labels: bug fix

#2983 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2981 ci: make waiting for nodes more robust
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_create/wait-for-nodes.sh
Labels: no changelog

#2984 helm: manually retry uninstalling a failed release
  internal/constellation/helm/action.go
  internal/constellation/helm/actionfactory.go
Labels: no changelog

#2987 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2986 docs: order csp strictly alphabetically
  README.md
  docs/docs/architecture/attestation.md
  docs/docs/getting-started/first-steps.md
  docs/docs/getting-started/install.md
  docs/docs/workflows/config.md
  docs/docs/workflows/recovery.md
  docs/docs/workflows/scale.md
  docs/docs/workflows/storage.md
  docs/docs/workflows/terraform-provider.md
  docs/versioned_docs/version-2.16/architecture/attestation.md
  docs/versioned_docs/version-2.16/getting-started/first-steps.md
  docs/versioned_docs/version-2.16/getting-started/install.md
  docs/versioned_docs/version-2.16/workflows/config.md
  docs/versioned_docs/version-2.16/workflows/recovery.md
  docs/versioned_docs/version-2.16/workflows/scale.md
  docs/versioned_docs/version-2.16/workflows/storage.md
  docs/versioned_docs/version-2.16/workflows/terraform-provider.md
Labels: documentation

#2989 docs: change to inter font
  docs/src/css/custom.css
Labels: documentation, no changelog

#2990 operator: escape dots in url
  operators/constellation-node-operator/internal/cloud/gcp/client/disks.go
  operators/constellation-node-operator/internal/cloud/gcp/client/disks_test.go
Labels: no changelog

#2985 ci: query identity directly instead of searching in list
  .github/actions/cdbg_deploy/action.yml
Labels: no changelog

#2991 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2992 provider: Add build tag for Terraform provider
  terraform-provider-constellation/BUILD.bazel
Labels: no changelog

#2994 ci: fix pvc clean-up on non deletable namespaces
  .github/actions/constellation_destroy/action.yml
Labels: no changelog

#2996 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3001 ci: fix unwanted license checks for some e2e test configs
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-provider-example.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#3002 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3000 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog
