Repository edgelesssys/constellation, pull requests merged in 2024-12, with the labels that each got.

#3512 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3513 ci: run memory intensive `check` targets sequentially
  bazel/ci/BUILD.bazel
Labels: no changelog

#3522 constellation-node-operator: don't bail out on listing errors
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup_test.go
Labels: no changelog

#3527 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3530 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3528 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3534 flake: update to Bazel 7.4.1
  flake.lock
  flake.nix
Labels: dependencies

#3541 ci: exclude CoreDNS chart from renovate
  renovate.json5
Labels: no changelog

#3543 image: use uplosi from nixpkgs-unstable
  flake.lock
  flake.nix
  internal/osimage/uplosi/uplosi.conf.in
Labels: no changelog

#3544 operator: drop REST API workaround for SEV-SNP GCP instances
  operators/constellation-node-operator/internal/cloud/gcp/client/BUILD.bazel
  operators/constellation-node-operator/internal/cloud/gcp/client/api.go
  operators/constellation-node-operator/internal/cloud/gcp/client/client.go
  operators/constellation-node-operator/internal/cloud/gcp/client/client_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/gcpwrappers.go
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup_test.go
Labels: no changelog

#3545 docs: correct STACKIT IDs
  docs/docs/getting-started/first-steps.md
  docs/docs/getting-started/install.md
  docs/versioned_docs/version-2.19/getting-started/first-steps.md
  docs/versioned_docs/version-2.19/getting-started/install.md
  docs/versioned_docs/version-2.20/getting-started/first-steps.md
  docs/versioned_docs/version-2.20/getting-started/install.md
Labels: documentation, needs backport

#3549 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3551 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3554 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3555 image: include files from git reproducibly
  image/BUILD.bazel
  image/base/BUILD.bazel
  image/initrd/BUILD.bazel
Labels: no changelog

#3556 ci: enable STACKIT e2e tests
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_iam_create/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/login_stackit/action.yml
  .github/actions/notify_stackit/action.yml
  .github/actions/terraform_apply/action.yml
  .github/workflows/e2e-test-stackit.yml
  .github/workflows/e2e-test.yml
Labels: no changelog

#3559 ci: only write STACKIT configuration if STACKIT test runs
  .github/actions/constellation_iam_create/action.yml
Labels: no changelog

#3564 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies
