Repository edgelesssys/constellation, pull requests merged in 2024-04, with the labels that each got.

#3004 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3005 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3006 ci: disable license check for minicon e2e
  e2e/miniconstellation/test-remote.sh
Labels: no changelog

#3008 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3009 bazel: patch Go SDK to increase tls maxHandshake size
  3rdparty/bazel/org_golang/BUILD.bazel
  3rdparty/bazel/org_golang/go_tls_max_handshake_size.patch
  WORKSPACE.bazel
Labels: bug fix

#2997 logging: unify debug log message format
  cli/internal/cmd/apply.go
  cli/internal/cmd/applyhelm.go
  cli/internal/cmd/applyinit.go
  cli/internal/cmd/configfetchmeasurements.go
  cli/internal/cmd/configgenerate.go
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/init.go
  cli/internal/cmd/maapatch.go
  cli/internal/cmd/recover.go
  cli/internal/cmd/upgradecheck.go
  cli/internal/cmd/verify.go
  e2e/malicious-join/malicious-join.go
  hack/bazel-deps-mirror/check.go
  hack/bazel-deps-mirror/fix.go
  hack/bazel-deps-mirror/internal/mirror/mirror.go
  hack/bazel-deps-mirror/upgrade.go
  hack/oci-pin/codegen.go
  hack/oci-pin/merge.go
  hack/oci-pin/sum.go
  image/upload/internal/cmd/info.go
  image/upload/internal/cmd/measurementsenvelope.go
  image/upload/internal/cmd/measurementsmerge.go
  image/upload/internal/cmd/measurementsupload.go
  image/upload/internal/cmd/uplosi.go
  internal/api/client/client.go
  internal/api/versionsapi/cli/add.go
  internal/api/versionsapi/cli/latest.go
  internal/api/versionsapi/cli/list.go
  internal/api/versionsapi/cli/rm.go
  internal/api/versionsapi/client.go
  internal/attestation/measurements/measurements.go
  internal/constellation/apply.go
  internal/constellation/applyinit.go
  internal/constellation/helm/actionfactory.go
  internal/constellation/helm/retryaction.go
  internal/constellation/kubecmd/backup.go
  internal/constellation/kubecmd/kubecmd.go
  internal/grpc/grpclog/grpclog.go
  internal/grpc/grpclog/grpclog_test.go
  internal/osimage/archive/archive.go
  internal/osimage/imageinfo/imageinfo.go
  internal/osimage/measurementsuploader/measurementsuploader.go
  internal/osimage/nop/nop.go
  internal/staticupload/staticupload.go
  internal/verify/verify.go
  joinservice/internal/certcache/amdkds/amdkds_test.go
  joinservice/internal/certcache/certcache.go
  joinservice/internal/watcher/validator.go
Labels: no changelog

#3012 rfc: remove broken Distroless link
  rfc/006-reproducible-builds.md
Labels: no changelog

#3010 deps: update Go toolchain to 1.22.2
  .github/actions/versionsapi/Dockerfile
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  WORKSPACE.bazel
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  go.work
Labels: dependencies

#3014 ci: fix slsa generator action by updating to new version
  .github/workflows/draft-release.yml
Labels: no changelog, needs backport

#3013 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3015 ci: bump slsa-verifier to v2.5.1
  .github/workflows/draft-release.yml
Labels: no changelog, needs backport

#3017 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2995 docs: update images with inter font
  docs/docs/_media/concept-constellation.svg
  docs/docs/_media/concept-managed.svg
  docs/docs/_media/product-overview-dark.png
  docs/docs/_media/product-overview.png
  docs/docs/_media/tcb.svg
  docs/static/img/concept.svg
  docs/versioned_docs/version-2.16/_media/concept-constellation.svg
  docs/versioned_docs/version-2.16/_media/concept-managed.svg
  docs/versioned_docs/version-2.16/_media/product-overview-dark.png
  docs/versioned_docs/version-2.16/_media/product-overview.png
  docs/versioned_docs/version-2.16/_media/tcb.svg
Labels: documentation, no changelog

#3019 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3022 helm: unbreak helm test after Cilium version bump
  internal/constellation/helm/helm_test.go
Labels: no changelog

#3026 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3024 dev-docs: document security advisory process
  dev-docs/workflows/security-patch.md
Labels: no changelog

#3028 kubecmd: retry any K8s errors in CLI and Terraform
  internal/constellation/kubecmd/backup.go
  internal/constellation/kubecmd/kubecmd.go
  internal/constellation/kubecmd/kubecmd_test.go
Labels: bug fix

#3030 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3032 deps: auto-assign reviewer for deps PRs
  .github/workflows/assign_reviewer.yml
Labels: no changelog

#3034 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3033 cli: allow tagging cloud resources with custom tags
  cli/internal/cloudcmd/tfvars.go
  cli/internal/cmd/configgenerate.go
  cli/internal/terraform/variables.go
  cli/internal/terraform/variables_test.go
  docs/docs/reference/cli.md
  internal/cloud/cloudprovider/cloudprovider.go
  internal/config/config.go
  internal/config/config_doc.go
  terraform/infrastructure/aws/main.tf
  terraform/infrastructure/aws/modules/jump_host/main.tf
  terraform/infrastructure/aws/modules/jump_host/variables.tf
  terraform/infrastructure/aws/variables.tf
  terraform/infrastructure/azure/main.tf
  terraform/infrastructure/azure/modules/jump_host/main.tf
  terraform/infrastructure/azure/modules/jump_host/variables.tf
  terraform/infrastructure/azure/modules/load_balancer_backend/variables.tf
  terraform/infrastructure/azure/variables.tf
  terraform/infrastructure/gcp/main.tf
  terraform/infrastructure/gcp/variables.tf
  terraform/infrastructure/openstack/main.tf
  terraform/infrastructure/openstack/variables.tf
  terraform/legacy-module/aws-constellation/main.tf
  terraform/legacy-module/aws-constellation/variables.tf
  terraform/legacy-module/azure-constellation/main.tf
  terraform/legacy-module/azure-constellation/variables.tf
  terraform/legacy-module/gcp-constellation/main.tf
  terraform/legacy-module/gcp-constellation/variables.tf
Labels: feature

#3036 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3038 attestation: dont set a default for TDX MRSEAM
  internal/config/azure.go
  internal/config/config.go
Labels: needs backport

#3040 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3035 ci: tag resources created by e2e tests with the run name
  .github/actions/constellation_iam_create/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-windows.yml
Labels: no changelog

#3043 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3045 terraform: simplify additional tagging logic to ensure they are always applied
  terraform/infrastructure/aws/main.tf
  terraform/infrastructure/azure/main.tf
  terraform/infrastructure/gcp/main.tf
Labels: no changelog

#2874 ci: Delete e2e terraform state
  .github/actions/artifact_delete/delete_artifact.sh
  .github/actions/artifact_upload/action.yml
  .github/actions/e2e_cleanup_timeframe/action.yml
  .github/actions/e2e_cleanup_timeframe/e2e-cleanup.sh
  .github/actions/update_tfstate/action.yml
  .github/workflows/e2e-cleanup-weekly.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/e2e-windows.yml
Labels: no changelog

#3047 dev-docs: howto generate kubeconfigs
  dev-docs/howto/kubeconfigs.md
Labels: no changelog
