Repository edgelesssys/constellation, pull requests merged in 2024-06, with the labels that each got.

#3131 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3139 image: fix podman config path
  image/base/mkosi.skeleton/etc/containers/containers.conf
  image/base/mkosi.skeleton/etc/containers/registries.conf
Labels: no changelog

#3142 flake: pin bazel to 7.1.2
  flake.lock
  flake.nix
Labels: no changelog

#3130 helm: use Cilium chart from fork
  internal/constellation/helm/charts/cilium/README.md
  internal/constellation/helm/charts/cilium/templates/cilium-agent/daemonset.yaml
  internal/constellation/helm/charts/cilium/values.yaml.tmpl
  internal/constellation/helm/cilium.patch
  internal/constellation/helm/generateCilium.sh
Labels: no changelog

#3141 Update conditions on when to pick reviewer
  .github/workflows/assign_reviewer.yml
Labels: no changelog

#3144 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3134 bootstrapper: disable gRPC logging
  bootstrapper/cmd/bootstrapper/main.go
  image/base/mkosi.skeleton/usr/lib/systemd/system/constellation-bootstrapper.service
  image/base/mkosi.skeleton/usr/lib/systemd/system/constellation-upgrade-agent.service
  upgrade-agent/cmd/main.go
Labels: no changelog

#3146 deps: bump Go version to v1.22.4
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-operator-codegen.yml
  MODULE.bazel
  MODULE.bazel.lock
  dev-docs/workflows/bump-go-version.md
Labels: dependencies

#3145 ci: author scheduled PRs using edgelessci account
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/update-rpms.yml
Labels: no changelog

#3051 rfc: node access
  rfc/016-node-access.md
Labels: no changelog

#3147 bazel: use go_bin_for_host for all CI scripts
  bazel/ci/BUILD.bazel
Labels: no changelog

#3148 ci: don't filter output of govulncheck
  bazel/ci/govulncheck.sh.in
Labels: no changelog

#3151 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3152 docs: adjust MAA updating
  docs/docs/getting-started/install.md
  docs/docs/workflows/create.md
  docs/versioned_docs/version-2.10/getting-started/install.md
  docs/versioned_docs/version-2.11/getting-started/install.md
  docs/versioned_docs/version-2.12/getting-started/install.md
  docs/versioned_docs/version-2.13/getting-started/install.md
  docs/versioned_docs/version-2.13/workflows/create.md
  docs/versioned_docs/version-2.14/getting-started/install.md
  docs/versioned_docs/version-2.14/workflows/create.md
  docs/versioned_docs/version-2.15/getting-started/install.md
  docs/versioned_docs/version-2.15/workflows/create.md
  docs/versioned_docs/version-2.16/getting-started/install.md
  docs/versioned_docs/version-2.16/workflows/create.md
  docs/versioned_docs/version-2.7/getting-started/install.md
  docs/versioned_docs/version-2.8/getting-started/install.md
  docs/versioned_docs/version-2.9/getting-started/install.md
Labels: no changelog

#3153 cli: return a more helpful error message on MAA patch failure
  internal/maa/patch.go
Labels: no changelog

#3156 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3158 ci: bump origin versions of upgrade tests
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#3149 helm: upgrade Cilium to v1.15.5-edg.1
  internal/constellation/helm/charts/cilium/Chart.yaml
  internal/constellation/helm/charts/cilium/README.md
  internal/constellation/helm/charts/cilium/files/agent/poststart-eni.bash
  internal/constellation/helm/charts/cilium/files/cilium-agent/dashboards/cilium-dashboard.json
  internal/constellation/helm/charts/cilium/files/nodeinit/startup.bash
  internal/constellation/helm/charts/cilium/templates/cilium-agent/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-agent/servicemonitor.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-configmap.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-envoy/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-envoy/servicemonitor.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-nodeinit/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-preflight/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-preflight/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/clustermesh-apiserver/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/hubble-relay/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/spire/agent/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/spire/namespace.yaml
  internal/constellation/helm/charts/cilium/values.yaml
  internal/constellation/helm/charts/cilium/values.yaml.tmpl
  internal/constellation/helm/cilium.patch
  internal/constellation/helm/generateCilium.sh
  internal/constellation/helm/helm_test.go
  internal/constellation/helm/loader.go
Labels: dependencies

#3054 deps: upgrade to tink-go v2.1.0
  go.mod
Labels: no changelog

#3162 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3164 cli: enable JSON output for `constellation verify` on Azure TDX
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  internal/attestation/azure/tdx/issuer.go
  internal/attestation/azure/tdx/tdx.go
  internal/attestation/azure/tdx/validator.go
  internal/verify/verify.go
Labels: feature

#3167 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3168 ci: make cdbg deploy errors easier to spot
  .github/actions/cdbg_deploy/action.yml
Labels: no changelog

#3169 ci: don't assign 3u13r for e2e failures
  .github/actions/pick_assignee/action.yml
Labels: no changelog

#3170 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3172 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3174 ci: better fence around tidy-check-generate summary
  .github/workflows/test-tidy.yml
Labels: no changelog

#3178 ci: fix GCP CCM findvers.sh script
  .github/actions/gcpccm_vers_to_build/findvers.sh
Labels: no changelog

#3173 versions: default to k8s v1.29, support k8s v1.30, EOL v1.27
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-test.yml
  docs/docs/architecture/versions.md
  docs/docs/reference/cli.md
  internal/versions/versions.go
  terraform-provider-constellation/docs/resources/cluster.md
Labels: dependencies

#3182 ci: fix cdbg_deploy error reporting
  .github/actions/cdbg_deploy/action.yml
Labels: no changelog

#3175 helm: update Azure CSI, GCP CSI, and CSI snapshotter charts
  internal/constellation/helm/charts/edgeless/csi/Chart.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/Chart.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/values.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/gcp-compute-persistent-disk-csi-driver/Chart.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/gcp-compute-persistent-disk-csi-driver/values.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/Chart.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/templates/admission-configuration.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/templates/serving-cert.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/templates/snapshot-controller.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/templates/snapshot-webhook.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/values.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-crds/Chart.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-crds/templates/volumesnapshotclasses.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-crds/templates/volumesnapshotcontents.yaml
  internal/constellation/helm/charts/edgeless/csi/charts/snapshot-crds/templates/volumesnapshots.yaml
  internal/constellation/helm/update-csi-charts.sh
Labels: dependencies

#3189 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3184 cli: fix `constellation verify` depending on an initialized `constellation-state.yaml` file
  cli/internal/cmd/verify.go
  cli/internal/cmd/verify_test.go
  docs/docs/workflows/verify-cluster.md
  docs/versioned_docs/version-2.15/workflows/verify-cluster.md
  docs/versioned_docs/version-2.16/workflows/verify-cluster.md
Labels: bug fix

#3188 ci: make bazel generate more stable
  bazel/ci/BUILD.bazel
Labels: no changelog

#3195 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3192 bazel: use released version of gazelle
  MODULE.bazel
  MODULE.bazel.lock
Labels: no changelog

#3193 deps: update k8s replace directive
  go.mod
Labels: no changelog

#3201 operator: fix gRPC dialing over UDS
  operators/constellation-node-operator/internal/upgrade/BUILD.bazel
  operators/constellation-node-operator/internal/upgrade/upgrade.go
  operators/constellation-node-operator/internal/upgrade/upgrade_test.go
Labels: no changelog

#3204 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3212 docs: add policy troubleshooting tip
  docs/docs/workflows/troubleshooting.md
  docs/versioned_docs/version-2.16/workflows/troubleshooting.md
Labels: documentation, no changelog

#3213 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3216 debugd: daemonize logstash containers
  debugd/internal/debugd/logcollector/logcollector.go
Labels: no changelog
