Repository edgelesssys/constellation, pull requests merged in 2024-10, with the labels that each got.

#3384 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3387 image: improve AWS performance by retiring idle=poll option
  image/system/variants.bzl
Labels: bug fix

#3386 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3390 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3388 helm: manage CoreDNS addon as Helm chart
  bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
  bootstrapper/internal/kubernetes/kubernetes.go
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/applyhelm.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/upgradeapply_test.go
  go.mod
  go.sum
  internal/constellation/helm.go
  internal/constellation/helm/BUILD.bazel
  internal/constellation/helm/charts/coredns/Chart.yaml
  internal/constellation/helm/charts/coredns/templates/clusterrole.yaml
  internal/constellation/helm/charts/coredns/templates/clusterrolebinding.yaml
  internal/constellation/helm/charts/coredns/templates/configmap.yaml
  internal/constellation/helm/charts/coredns/templates/deployment.yaml
  internal/constellation/helm/charts/coredns/templates/service.yaml
  internal/constellation/helm/charts/coredns/templates/serviceaccount.yaml
  internal/constellation/helm/charts/coredns/values.yaml
  internal/constellation/helm/corednsgen/BUILD.bazel
  internal/constellation/helm/corednsgen/corednsgen.go
  internal/constellation/helm/helm.go
  internal/constellation/helm/helm_test.go
  internal/constellation/helm/loader.go
  internal/constellation/helm/loader_test.go
  internal/constellation/helm/overrides.go
  internal/kubernetes/kubectl/kubectl.go
  terraform-provider-constellation/internal/provider/cluster_resource.go
Labels: breaking change

#3393 readme: remove demo references
  README.md
Labels: no changelog

#3394 dev-docs: link to docs website instead of to local files
  dev-docs/security-overview.md
  dev-docs/workflows/github-actions.md
  dev-docs/workflows/qemu.md
Labels: no changelog

#3392 helm: upgrade Cilium to v1.15.8
  internal/constellation/helm/charts/cilium/Chart.yaml
  internal/constellation/helm/charts/cilium/README.md
  internal/constellation/helm/charts/cilium/README.md.gotmpl
  internal/constellation/helm/charts/cilium/files/hubble/dashboards/hubble-dashboard.json
  internal/constellation/helm/charts/cilium/files/hubble/dashboards/hubble-dns-namespace.json
  internal/constellation/helm/charts/cilium/files/hubble/dashboards/hubble-network-overview-namespace.json
  internal/constellation/helm/charts/cilium/templates/_helpers.tpl
  internal/constellation/helm/charts/cilium/templates/cilium-agent/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-configmap.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-envoy/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-ingress-service.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-nodeinit/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-operator/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-operator/poddisruptionbudget.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-preflight/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-preflight/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-preflight/poddisruptionbudget.yaml
  internal/constellation/helm/charts/cilium/templates/clustermesh-apiserver/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/clustermesh-apiserver/poddisruptionbudget.yaml
  internal/constellation/helm/charts/cilium/templates/clustermesh-apiserver/service.yaml
  internal/constellation/helm/charts/cilium/templates/clustermesh-apiserver/tls-cronjob/cronjob.yaml
  internal/constellation/helm/charts/cilium/templates/etcd-operator/cilium-etcd-operator-deployment.yaml
  internal/constellation/helm/charts/cilium/templates/etcd-operator/poddisruptionbudget.yaml
  internal/constellation/helm/charts/cilium/templates/hubble-relay/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/hubble-relay/poddisruptionbudget.yaml
  internal/constellation/helm/charts/cilium/templates/hubble-ui/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/hubble-ui/ingress.yaml
  internal/constellation/helm/charts/cilium/templates/hubble-ui/poddisruptionbudget.yaml
  internal/constellation/helm/charts/cilium/templates/hubble/peer-service.yaml
  internal/constellation/helm/charts/cilium/templates/hubble/tls-cronjob/cronjob.yaml
  internal/constellation/helm/charts/cilium/templates/validate.yaml
  internal/constellation/helm/charts/cilium/values.yaml
  internal/constellation/helm/charts/cilium/values.yaml.tmpl
  internal/constellation/helm/cilium.patch
  internal/constellation/helm/generateCilium.sh
  internal/constellation/helm/helm_test.go
  internal/constellation/helm/loader.go
Labels: dependencies

#3257 Allow upgrades on azure without Terraform changes on LBs created from within Kubernetes
  docs/docs/reference/migration.md
  internal/constellation/helm/overrides.go
  terraform/infrastructure/aws/main.tf
  terraform/infrastructure/azure/main.tf
  terraform/infrastructure/azure/modules/scale_set/main.tf
  terraform/infrastructure/gcp/main.tf
  terraform/infrastructure/openstack/main.tf
  terraform/infrastructure/qemu/main.tf
Labels: bug fix, no changelog

#3402 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3404 ci: ignore GO-2024-3166 in govulncheck
  MODULE.bazel
  bazel/ci/BUILD.bazel
  bazel/ci/govulncheck.sh.in
Labels: no changelog

#3400 CODEOWNERS: move ownership of Helm charts to burgerdev
  CODEOWNERS
Labels: no changelog

#3410 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3413 ci: upgrade to ubuntu-24.04 fixups
  .github/actions/e2e_cleanup_timeframe/action.yml
  .github/workflows/e2e-test-internal-lb.yml
  .github/workflows/e2e-test-marketplace-image.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-terraform-provider.yml
  .github/workflows/e2e-test.yml
Labels: no changelog

#3427 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3422 ci: enable Teams mentions for burgerdev
  .github/actions/notify_teams/README.md
  .github/actions/notify_teams/action.yml
  .github/actions/notify_teams/teams_payload_template.json
Labels: no changelog

#3439 e2e: fix malicious join test
  e2e/malicious-join/malicious-join.go
Labels: no changelog

#3441 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3442 helm: allow namespace handling for node-maintenance-operator
  internal/constellation/helm/charts/edgeless/operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/AWS/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/OpenStack/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
Labels: no changelog, needs backport

#3445 chore: v2.19.0 post-release
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  version.txt
Labels: no changelog

#3440 terraform: upgrade hashicorp/google to 6.7.0
  terraform/infrastructure/gcp/.terraform.lock.hcl
  terraform/infrastructure/gcp/main.tf
  terraform/infrastructure/gcp/modules/instance_group/main.tf
  terraform/infrastructure/gcp/modules/internal_load_balancer/main.tf
  terraform/infrastructure/gcp/modules/jump_host/main.tf
  terraform/infrastructure/gcp/modules/loadbalancer/main.tf
  terraform/infrastructure/iam/gcp/.terraform.lock.hcl
  terraform/infrastructure/iam/gcp/main.tf
Labels: no changelog

#3455 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3456 ci: use GOPROXY fallbacks
  bazel/bazelrc/ci.bazelrc
Labels: no changelog

#3457 cli: also log applier debug messages to debug log file
  cli/internal/cmd/apply.go
Labels: no changelog

#3458 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3449 docs: clarify for Azure TDX with Terraform provider
  docs/docs/workflows/terraform-provider.md
  docs/versioned_docs/version-2.19/workflows/terraform-provider.md
  terraform-provider-constellation/examples/full/azure/main.tf
Labels: documentation

#3459 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3460 ci: report failure in scheduled Terraform provider tests on cancel
  .github/workflows/e2e-test-provider-example.yml
Labels: no changelog

#3461 e2e-upgrade: guard function return values behind `sync.WaitGroup`
  e2e/internal/upgrade/upgrade.go
Labels: no changelog

#3451 docs: how to reproduce released artifacts
  .github/workflows/reproducible-builds.yml
  docs/docs/workflows/reproducible-builds.md
  docs/sidebars.js
  nix/cc/cryptsetup.nix
  nix/cc/libvirt.nix
  renovate.json5
Labels: documentation

#3462 deps: update terraform-provider-stackit
  terraform/infrastructure/openstack/.terraform.lock.hcl
  terraform/infrastructure/openstack/main.tf
  terraform/infrastructure/openstack/modules/stackit_loadbalancer/main.tf
Labels: dependencies, no changelog

#3464 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog
