Repository edgelesssys/constellation, pull requests merged in 2024-07, with the labels that each got.

#3218 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3222 ci: fix directory deletion
  .github/actions/upload_terraform_module/action.yml
Labels: no changelog

#3223 ci: only commit measurements if changes are present
  .github/workflows/release.yml
Labels: no changelog

#3225 deps: bump Go version to v1.22.5
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-operator-codegen.yml
  MODULE.bazel
  dev-docs/workflows/bump-go-version.md
  go.mod
  go.work
Labels: dependencies

#3231 ci: run versionsapi through Bazel instead of building a container
  .github/actions/find_latest_image/action.yml
  .github/actions/select_image/action.yml
  .github/actions/versionsapi/Dockerfile
  .github/actions/versionsapi/action.yml
  .github/workflows/build-versionsapi-ci-image.yml
  .github/workflows/purge-main.yml
  .github/workflows/versionsapi.yml
Labels: no changelog

#3229 chore: v2.17.0 post-release
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
  version.txt
Labels: no changelog

#3232 terraform: update StackIT provider to v0.23.0
  terraform/infrastructure/openstack/.terraform.lock.hcl
  terraform/infrastructure/openstack/main.tf
  terraform/infrastructure/openstack/modules/stackit_loadbalancer/main.tf
Labels: dependencies

#3233 docs: update concept graphic
  docs/static/img/concept.svg
Labels: no changelog

#3234 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3235 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3243 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3237 ci: fix TF attestation version assertion in integration test
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
Labels: no changelog

#3239 dev-docs: set an MTU on the VPN route
  dev-docs/howto/vpn/helm/templates/_helpers.tpl
  dev-docs/howto/vpn/helm/values.yaml
  nix/container/vpn/sidecar.sh
Labels: bug fix

#3238 attestationconfigapi: revise upload frequency
  .github/actions/e2e_verify/action.yml
  internal/api/attestationconfigapi/cli/BUILD.bazel
  internal/api/attestationconfigapi/cli/client/reporter.go
  internal/api/attestationconfigapi/cli/compare.go
  internal/api/attestationconfigapi/cli/delete.go
  internal/api/attestationconfigapi/cli/main.go
  internal/api/attestationconfigapi/cli/upload.go
  internal/api/attestationconfigapi/cli/validargs.go
Labels: no changelog

#3250 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3253 renovate: exclude stackit from Terraform group
  renovate.json5
Labels: no changelog

#3256 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3247 helm: add serviceProxyName to conformance values
  internal/constellation/helm/overrides.go
Labels: no changelog

#3255 Update concept.svg
  docs/static/img/concept.svg
Labels: no changelog

#3260 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3265 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3268 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3269 attestation: replace expired test vlek
  internal/attestation/aws/snp/testdata/report.txt
  internal/attestation/aws/snp/testdata/vlek.pem
Labels: no changelog

#3267 Make SEV-SNP the default attestation variant on GCP
  .github/actions/terraform_apply/action.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  cli/internal/cmd/init_test.go
  docs/docs/architecture/attestation.md
  docs/docs/overview/clouds.md
  docs/docs/reference/cli.md
  docs/versioned_docs/version-2.16/architecture/attestation.md
  docs/versioned_docs/version-2.17/architecture/attestation.md
  docs/versioned_docs/version-2.17/overview/clouds.md
  internal/attestation/variant/variant.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/config/validation.go
  terraform-provider-constellation/docs/data-sources/attestation.md
  terraform-provider-constellation/docs/data-sources/image.md
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/examples/full/gcp/main.tf
  terraform-provider-constellation/internal/provider/shared_attributes.go
Labels: feature

#3271 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3272 ci: run performance e2e tests using nightly image
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#3270 terraform: azure remove unused lb backends
  terraform/infrastructure/azure/main.tf
Labels: no changelog

#3273 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3274 ci: mirror GCP SEV-SNP marketplace images
  .github/workflows/on-release.yml
Labels: breaking change

#3276 ci: correctly fetch image on nightly image ref
  .github/actions/select_image/action.yml
Labels: no changelog

#3277 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog
