Repository edgelesssys/constellation, pull requests merged in 2024-09, with the labels that each got.

#3333 terraform: tidy files
  terraform-provider-constellation/examples/full/azure/main.tf
Labels: no changelog

#3332 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3331 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3334 terraform-provider-constellation: make kubeconfig output fine-grained
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/cluster_resource.go
Labels: feature

#3335 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3338 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3342 image: update mkosi to 24.3
  flake.lock
  flake.nix
  image/base/mkosi.conf
  image/base/mkosi.postinst
  image/initrd/mkosi.conf
  image/system/mkosi.conf
Labels: no changelog

#3341 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3343 treewide: update Go toolchain to 1.22.7
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-operator-codegen.yml
  MODULE.bazel
  go.mod
  go.work
Labels: dependencies

#3344 helm: cilium: allow multiple default routes
  internal/constellation/helm/charts/cilium/templates/cilium-agent/daemonset.yaml
  internal/constellation/helm/cilium.patch
Labels: bug fix

#3350 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3352 terraform-provider-constellation: set correct cc_technology in GCP example
  terraform-provider-constellation/examples/full/gcp/main.tf
Labels: no changelog

#3351 e2e: remove immediate node status printing
  e2e/internal/upgrade/upgrade.go
Labels: no changelog

#3353 helm: fix kubeadm bugs caused by CoreDNS installation
  cli/internal/cmd/apply.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/init_test.go
  cli/internal/cmd/upgradeapply_test.go
  internal/constellation/helm.go
  internal/constellation/helm/charts/coredns/templates/configmap.yaml
  internal/constellation/helm/charts/coredns/templates/deployment.yaml
  internal/constellation/helm/corednsgen/corednsgen.go
  terraform-provider-constellation/internal/provider/cluster_resource.go
  upgrade-agent/internal/server/server.go
Labels: no changelog

#3354 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3356 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3355 image: re-enable autologin for debug and console images
  bazel/mkosi/mkosi_image.bzl
  image/sysroot-tree/usr/lib/systemd/system-preset/20-constellation-base.preset
  image/sysroot-tree/usr/lib/systemd/system/serial-getty@ttyS0.service.d/autologin.conf
  image/system/BUILD.bazel
  image/system/variants.bzl
Labels: no changelog

#3362 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3361 operator: use GCP REST API for instance templates
  go.mod
  go.sum
  operators/constellation-node-operator/internal/cloud/gcp/client/BUILD.bazel
  operators/constellation-node-operator/internal/cloud/gcp/client/api.go
  operators/constellation-node-operator/internal/cloud/gcp/client/client.go
  operators/constellation-node-operator/internal/cloud/gcp/client/client_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/gcpwrappers.go
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup_test.go
Labels: no changelog

#3369 ci: remove obsolete python dep
  .github/workflows/aws-snp-launchmeasurement.yml
  .github/workflows/aws-snp-launchmeasurements-requirements.txt
Labels: no changelog

#3371 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3372 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3377 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3379 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3381 treewide: v2.18.0 post-release
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  version.txt
Labels: no changelog

#3380 ci: fix matrix runner spec
  .github/workflows/e2e-test-release.yml
Labels: no changelog
