Repository edgelesssys/constellation, pull requests merged in 2024-01, with the labels that each got.

#2782 helm: masq traffic to the mini-qemu-metadata container so that the join-service can retrieve it's metadata
  e2e/miniconstellation/test-remote.sh
  internal/constellation/helm/overrides.go
Labels: bug fix, needs backport

#2788 node-operator: fix setting Azure node image
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup_test.go
Labels: bug fix, needs backport

#2789 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2781 Add pod disruption budgets so the cluster-autoscaler is able to move kube-admin namespaced resources
  internal/constellation/helm/BUILD.bazel
  internal/constellation/helm/charts/edgeless/constellation-services/charts/autoscaler/templates/coredns-pdb.yaml
  internal/constellation/helm/loader.go
  internal/constellation/helm/testdata/AWS/constellation-services/charts/autoscaler/templates/coredns-pdb.yaml
  internal/constellation/helm/testdata/Azure/constellation-services/charts/autoscaler/templates/coredns-pdb.yaml
  internal/constellation/helm/testdata/GCP/constellation-services/charts/autoscaler/templates/coredns-pdb.yaml
  internal/constellation/helm/values.go
Labels: feature

#2745 ci: e2e test for Terraform provider examples
  .github/actions/setup_bazel_nix/action.yml
  .github/actions/upload_terraform_module/action.yml
  .github/workflows/draft-release.yml
  .github/workflows/e2e-test-provider-example.yml
  CODEOWNERS
  dev-docs/workflows/terraform-provider.md
  terraform-provider-constellation/examples/full/aws/main.tf
  terraform-provider-constellation/examples/full/azure/main.tf
  terraform-provider-constellation/examples/full/gcp/main.tf
  terraform-provider-constellation/internal/provider/cluster_resource.go
Labels: no changelog

#2791 terraform-provider: require kubernetes and microservice version
  .github/workflows/e2e-test-provider-example.yml
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/examples/full/aws/main.tf
  terraform-provider-constellation/examples/full/azure/main.tf
  terraform-provider-constellation/examples/full/gcp/main.tf
  terraform-provider-constellation/internal/provider/BUILD.bazel
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/cluster_resource_test.go
Labels: breaking change

#2795 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2796 bazel: use prebuilt Go toolchain (go.dev/dl)
  WORKSPACE.bazel
  bazel/go/go.nix
  dev-docs/workflows/bump-go-version.md
Labels: no changelog

#2797 ci: ignore Wireguard pdf in lychee
  .github/workflows/check-links.yml
  .gitignore
  .lychee.toml
  .lycheeignore
  docs/docs/overview/performance/io.md
Labels: no changelog

#2739 terraform: add module deprecation notice
  terraform/legacy-module/README.md
Labels: no changelog

#2777 docs: update asciinema videos
  docs/screencasts/docker/create-cluster.expect
  docs/screencasts/docker/github-readme.expect
  docs/screencasts/generate-readme-svg.sh
  docs/static/assets/check-sbom.cast
  docs/static/assets/configure-cluster.cast
  docs/static/assets/create-cluster.cast
  docs/static/assets/terminate-cluster.cast
  docs/static/assets/verify-cli.cast
  docs/static/img/shell-windowframe.svg
Labels: documentation, no changelog

#2802 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2792 cli: support for GCP marketplace images
  .github/actions/constellation_create/action.yml
  .github/workflows/e2e-test-marketplace-image.yml
  dev-docs/workflows/marketplace-images.md
  docs/docs/overview/license.md
  internal/config/config.go
  internal/config/config_doc.go
  internal/imagefetcher/imagefetcher.go
  terraform-provider-constellation/docs/data-sources/image.md
  terraform-provider-constellation/internal/provider/image_data_source.go
Labels: feature

#2808 deps: bump cilium to v1.15.0-pre.3-edg.1
  internal/constellation/helm/loader.go
Labels: bug fix, no changelog

#2800 Fix various small things throughout the codebase
  .github/actions/deploy_logcollection/action.yml
  .github/actions/login_gcp/action.yml
  .github/workflows/on-release.yml
  .github/workflows/reproducible-builds.yml
  bootstrapper/cmd/bootstrapper/main.go
  cli/internal/cmd/configfetchmeasurements.go
  hack/cli-k8s-compatibility/BUILD.bazel
  hack/cli-k8s-compatibility/main.go
  image/upload/internal/cmd/BUILD.bazel
  image/upload/internal/cmd/image.go
  image/upload/internal/cmd/info.go
  image/upload/internal/cmd/measurementsupload.go
  internal/api/versionsapi/cli/list.go
  internal/attestation/measurements/measurement-generator/BUILD.bazel
  internal/attestation/measurements/measurement-generator/generate.go
  internal/constellation/helm/generateCertManager.sh
  internal/constellation/helm/generateCilium.sh
  internal/constellation/helm/update-csi-charts.sh
  internal/osimage/measurementsuploader/measurementsuploader.go
Labels: no changelog

#2811 ci: remove reference to absent go.mod file
  .github/actions/versionsapi/Dockerfile
  .github/actions/versionsapi/action.yml
  .github/workflows/build-versionsapi-ci-image.yml
Labels: no changelog

#2812 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2810 cli: fix AWS SEV-SNP latest version resolution in cluster
  internal/config/aws.go
  internal/config/azure.go
  internal/config/config.go
Labels: bug fix, needs backport

#2814 terraform-provider: validate microservice and image version during plan
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/cluster_resource_test.go
  terraform-provider-constellation/main.go
Labels: bug fix

#2815 image: lower file limit for containerd
  image/base/mkosi.skeleton/usr/lib/systemd/system/containerd.service.d/local.conf
Labels: no changelog

#2816 ci: remove derpsteb from e2e assignee list
  .github/actions/pick_assignee/action.yml
Labels: no changelog

#2817 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2775 ci: add upgrade to provider example test
  .github/workflows/e2e-test-provider-example.yml
  e2e/internal/upgrade/BUILD.bazel
  e2e/internal/upgrade/upgrade.go
  e2e/internal/upgrade/upgrade_test.go
  e2e/provider-upgrade/BUILD.bazel
  e2e/provider-upgrade/upgrade_test.go
  terraform-provider-constellation/examples/full/aws/main.tf
  terraform-provider-constellation/examples/full/azure/main.tf
  terraform-provider-constellation/examples/full/gcp/main.tf
Labels: no changelog

#2819 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2818 ci: fetch OpenSearch password from e2e test project
  debugd/internal/debugd/logcollector/credentials.go
Labels: no changelog

#2820 ci: automate GCP MPI mirroring
  .github/workflows/on-release.yml
Labels: no changelog

#2823 ci: don't check Wireguard weblinks
  .lychee.toml
Labels: no changelog

#2620 dev-docs: Helm chart for full L3 VPN connectivity
  dev-docs/howto/vpn/helm/README.md
  dev-docs/howto/vpn/helm/files/operator/entrypoint.sh
  dev-docs/howto/vpn/helm/files/strongswan/sidecar.sh
  dev-docs/howto/vpn/helm/files/tproxy-setup.sh
  dev-docs/howto/vpn/helm/files/wireguard-setup.sh
  dev-docs/howto/vpn/helm/templates/_helpers.tpl
  dev-docs/howto/vpn/helm/templates/configmaps.yaml
  dev-docs/howto/vpn/helm/templates/operator-deployment.yaml
  dev-docs/howto/vpn/helm/templates/rbac.yaml
  dev-docs/howto/vpn/helm/templates/secrets.yaml
  dev-docs/howto/vpn/helm/templates/service.yaml
  dev-docs/howto/vpn/helm/templates/strongswan-statefulset.yaml
  dev-docs/howto/vpn/helm/templates/wireguard-secret.tpl
  dev-docs/howto/vpn/helm/templates/wireguard-statefulset.yaml
  dev-docs/howto/vpn/helm/values.yaml
Labels: feature

#2822 helm: bump Cilium chart version
  internal/constellation/helm/BUILD.bazel
  internal/constellation/helm/charts/cilium/Chart.yaml
  internal/constellation/helm/charts/cilium/README.md
  internal/constellation/helm/charts/cilium/files/cilium-envoy/configmap/bootstrap-config.json
  internal/constellation/helm/charts/cilium/files/hubble/dashboards/hubble-dashboard.json
  internal/constellation/helm/charts/cilium/templates/cilium-agent/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-agent/serviceaccount.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-configmap.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-envoy/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-envoy/service.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-flowlog-configmap.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-operator/dashboards-configmap.yaml
  internal/constellation/helm/charts/cilium/templates/clustermesh-apiserver/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/hubble-relay/deployment.yaml
  internal/constellation/helm/charts/cilium/templates/spire/agent/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/validate.yaml
  internal/constellation/helm/charts/cilium/values.yaml
  internal/constellation/helm/charts/cilium/values.yaml.tmpl
  internal/constellation/helm/generateCilium.sh
  internal/constellation/helm/helm_test.go
Labels: no changelog

#2828 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2831 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2833 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2724 ci: parallelize upgrade e2e test
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#2835 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2839 ci: remove broken label from OpenSearch query link
  .github/actions/notify_e2e_failure/action.yml
Labels: no changelog

#2838 ci: fix pod ip cidr setting when not on GCP
  terraform-provider-constellation/internal/provider/cluster_resource.go
  terraform-provider-constellation/internal/provider/cluster_resource_test.go
Labels: no changelog

#2842 helm: re-enable native routing for gcp
  internal/constellation/helm/loader.go
Labels: bug fix, no changelog

#2848 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2847 ci: update vale
  .github/workflows/docs-vale.yml
  .vale.ini
  docs/docs/workflows/config.md
  docs/styles/Google/OptionalPlurals.yml
  docs/styles/Google/Spelling.yml
  docs/styles/Google/Units.yml
  docs/styles/Microsoft/Contractions.yml
  docs/styles/Microsoft/Foreign.yml
  docs/styles/Microsoft/Plurals.yml
  docs/styles/Microsoft/Terms.yml
  docs/styles/config/vocabularies/edgeless/accept.txt
Labels: no changelog

#2834 Ref/docs/clouds
  dev-docs/workflows/marketplace-images.md
  docs/docs/getting-started/marketplaces.md
  docs/docs/overview/clouds.md
  docs/sidebars.js
Labels: documentation, no changelog

#2846 operator: fix get-handling of Azure marketplace images
  operators/constellation-node-operator/internal/cloud/azure/client/nodeimage.go
  operators/constellation-node-operator/internal/cloud/azure/client/nodeimage_test.go
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup.go
  operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup_test.go
Labels: bug fix

#2851 image: update Linux to 6.1.74
  bazel/toolchains/linux_kernel.bzl
Labels: no changelog, dependency

#2852 ci: fix Opensearch link
  .github/actions/notify_e2e_failure/action.yml
Labels: no changelog

#2849 helm: remove kube-rbac-proxy
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/values.yaml
  internal/constellation/helm/testdata/AWS/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/OpenStack/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/deployment.yaml
Labels: no changelog

#2840 ci: add TF provider example test to weekly
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#2850 ci: fix e2e_benchmark comparison
  .github/actions/e2e_benchmark/.gitignore
  .github/actions/e2e_benchmark/action.yml
  .github/actions/e2e_benchmark/evaluate/compare.py
Labels: bug fix, no changelog

#2859 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2858 Add Azure region Germany West Central
  docs/docs/getting-started/first-steps.md
  docs/docs/workflows/config.md
  flake.lock
  flake.nix
Labels: documentation

#2854 terraform-provider: enable Azure TDX
  .github/actions/terraform_apply/action.yml
  internal/config/azure.go
  terraform-provider-constellation/docs/data-sources/attestation.md
  terraform-provider-constellation/docs/data-sources/image.md
  terraform-provider-constellation/docs/resources/cluster.md
  terraform-provider-constellation/internal/provider/attestation_data_source.go
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
  terraform-provider-constellation/internal/provider/convert.go
  terraform-provider-constellation/internal/provider/shared_attributes.go
Labels: no changelog

#2855 cilium: performance fixes and reproducible images
  internal/constellation/helm/charts/cilium/Chart.yaml
  internal/constellation/helm/cilium.patch
  internal/constellation/helm/helm_test.go
  internal/constellation/helm/loader.go
Labels: bug fix

#2863 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2866 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2869 ci: run provider upgrade test only once
  e2e/provider-upgrade/BUILD.bazel
Labels: no changelog

#2870 image: replicate to us-east-1 for aws marketplace
  internal/osimage/uplosi/uplosi.conf.in
Labels: no changelog

#2861 ci: pin the kube-bench plugin definitions for sonobuoy
  .github/actions/e2e_test/action.yml
Labels: no changelog

#2865 terraform-provider: only print license warning once in provider
  terraform-provider-constellation/internal/provider/cluster_resource.go
Labels: no changelog

#2867 ci: set board fields for tf example test
  .github/workflows/e2e-test-provider-example.yml
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#2871 ref: pre v2.15 cleanup
  cli/internal/cloudcmd/tfvars.go
  cli/internal/terraform/variables.go
  internal/constellation/helm/actionfactory.go
  internal/constellation/kubecmd/BUILD.bazel
  internal/constellation/kubecmd/kubecmd.go
  internal/constellation/kubecmd/kubecmd_test.go
  internal/constellation/state/state.go
  operators/constellation-node-operator/internal/upgrade/upgrade.go
  upgrade-agent/internal/server/server.go
  upgrade-agent/internal/server/server_test.go
  upgrade-agent/upgradeproto/upgrade.pb.go
  upgrade-agent/upgradeproto/upgrade.proto
Labels: no changelog

#2876 ci: fix empty run-id in OpenSearch URL
  .github/actions/notify_e2e_failure/action.yml
Labels: no changelog

#2877 ci: fix upload CLI path line splitting
  .github/workflows/draft-release.yml
Labels: no changelog

#2836 ci: introduce keep-sorted
  CODEOWNERS
  bazel/ci/BUILD.bazel
  bazel/ci/keep_sorted.sh.in
  bazel/toolchains/go_module_deps.bzl
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: no changelog

#2878 ci: fix self managed e2e for Azure TDX
  .github/actions/self_managed_create/action.yml
Labels: no changelog

#2872 deps: update `hashicorp/google` to 5.13.0
  terraform/infrastructure/gcp/.terraform.lock.hcl
  terraform/infrastructure/gcp/main.tf
  terraform/infrastructure/gcp/modules/instance_group/main.tf
  terraform/infrastructure/gcp/modules/internal_load_balancer/main.tf
  terraform/infrastructure/gcp/modules/jump_host/main.tf
  terraform/infrastructure/gcp/modules/loadbalancer/main.tf
  terraform/infrastructure/iam/gcp/.terraform.lock.hcl
  terraform/infrastructure/iam/gcp/main.tf
Labels: no changelog

#2853 ci: Upload e2e terraform state as artifact
  .github/actions/constellation_create/action.yml
Labels: no changelog

#2881 ci: v2.15 post-release cleanup
  .github/actions/e2e_verify/action.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
  version.txt
Labels: no changelog

#2882 terraform-provider: fix integration test
  terraform-provider-constellation/internal/provider/attestation_data_source_test.go
Labels: no changelog
