Repository edgelesssys/constellation, pull requests merged in 2024-11, with the labels that each got.

#3454 terraform: fix security rule reconciliation on Azure
  .github/workflows/e2e-upgrade.yml
  docs/docs/reference/migration.md
  e2e/internal/upgrade/BUILD.bazel
  e2e/internal/upgrade/upgrade.go
  e2e/internal/upgrade/upgrade_test.go
  terraform/infrastructure/azure/main.tf
Labels: bug fix, needs backport

#3466 image: unset password reset date to ensure reprodicibility
  image/base/BUILD.bazel
  image/base/mkosi.finalize
Labels: bug fix

#3469 docs: add migrate instructions to v2.19
  docs/versioned_docs/version-2.19/reference/migration.md
Labels: no changelog

#3468 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3471 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3470 docs: stackit improve clouds.yaml description
  docs/docs/getting-started/install.md
  docs/versioned_docs/version-2.19/getting-started/install.md
Labels: documentation, no changelog

#3474 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3475 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3476 docs: change wording contrast with comparison
  docs/docs/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.0/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.1/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.10/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.11/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.12/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.13/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.14/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.15/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.16/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.17/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.18/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.19/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.2/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.3/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.4/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.5/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.6/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.7/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.8/overview/confidential-kubernetes.md
  docs/versioned_docs/version-2.9/overview/confidential-kubernetes.md
Labels: documentation, no changelog

#3473 docs: update azure firmware with openhcl
  docs/docs/overview/clouds.md
  docs/styles/config/vocabularies/edgeless/accept.txt
  docs/versioned_docs/version-2.0/overview/clouds.md
  docs/versioned_docs/version-2.1/overview/clouds.md
  docs/versioned_docs/version-2.10/overview/clouds.md
  docs/versioned_docs/version-2.11/overview/clouds.md
  docs/versioned_docs/version-2.12/overview/clouds.md
  docs/versioned_docs/version-2.13/overview/clouds.md
  docs/versioned_docs/version-2.14/overview/clouds.md
  docs/versioned_docs/version-2.15/overview/clouds.md
  docs/versioned_docs/version-2.16/overview/clouds.md
  docs/versioned_docs/version-2.17/overview/clouds.md
  docs/versioned_docs/version-2.18/overview/clouds.md
  docs/versioned_docs/version-2.19/overview/clouds.md
  docs/versioned_docs/version-2.2/overview/clouds.md
  docs/versioned_docs/version-2.3/overview/clouds.md
  docs/versioned_docs/version-2.4/overview/clouds.md
  docs/versioned_docs/version-2.5/overview/clouds.md
  docs/versioned_docs/version-2.6/overview/clouds.md
  docs/versioned_docs/version-2.7/overview/clouds.md
  docs/versioned_docs/version-2.8/overview/clouds.md
  docs/versioned_docs/version-2.9/overview/clouds.md
Labels: documentation, no changelog

#3478 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3479 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3481 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3483 ci: update workload identity provider url
  .github/actions/login_gcp/action.yml
Labels: no changelog

#3485 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3484 ci: pin nix version to 2.25.2
  .github/actions/setup_bazel_nix/action.yml
Labels: no changelog

#3487 deps: use forked google/go-sev-guest to support v3 AMD SEV-SNP attestation reports
  go.mod
  go.sum
Labels: dependencies

#3477 Pin crane and npm dependencies
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/release.yml
  docs/.gitignore
  docs/README.md
  docs/package-lock.json
  docs/package.json
  docs/versioned_docs/version-2.6/overview/performance.md
  docs/versioned_docs/version-2.7/overview/performance.md
  docs/versioned_docs/version-2.8/overview/performance.md
Labels: no changelog

#3491 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3490 deps: update google/go-sev-guest to v0.11.2-0.20241122022416-97a55186df28
  go.mod
  go.sum
Labels: dependencies

#3492 docs: refactor gtag
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/static/gtagman.js
Labels: no changelog

#3494 ci: update workflows to initialize upgrade tests with v2.19.3
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#3496 bootstrapper: only err if no control plane IPs available
  bootstrapper/internal/joinclient/joinclient.go
Labels: bug fix

#3497 dev-docs: make post release steps more prominent
  dev-docs/workflows/release.md
Labels: no changelog

#3500 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3493 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3508 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog
