Repository edgelesssys/constellation, pull requests merged in 2024-02, with the labels that each got.

#2885 ci: reduce amount of regular tests
  .github/actions/cdbg_deploy/action.yml
  .github/actions/constellation_create/action.yml
  .github/actions/constellation_destroy/action.yml
  .github/actions/deploy_logcollection/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/notify_e2e_failure/action.yml
  .github/actions/self_managed_create/action.yml
  .github/pull_request_template.md
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-self-managed.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-test.yml
Labels: no changelog

#2886 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2889 cleanup: various minor debugging improvements
  .github/actions/constellation_create/action.yml
  .github/workflows/e2e-upgrade.yml
  internal/atls/atls.go
  internal/constellation/kubecmd/kubecmd.go
  joinservice/internal/server/server.go
Labels: no changelog

#2890 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2873 deps: update go-uefi and use new authenticode package
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
  image/measured-boot/cmd/main.go
  image/measured-boot/measure/BUILD.bazel
  image/measured-boot/measure/authentihash.go
  image/measured-boot/measure/authentihash_test.go
Labels: dependencies

#2891 ci: fix workspace related errors when setting up k8s version for test
  .github/workflows/e2e-test-provider-example.yml
Labels: no changelog

#2893 ci: make instance type configurable for provider sample
  .github/workflows/e2e-test-provider-example.yml
  terraform-provider-constellation/examples/full/aws/main.tf
  terraform-provider-constellation/examples/full/azure/main.tf
  terraform-provider-constellation/examples/full/gcp/main.tf
Labels: no changelog

#2888 terraform: support AWS marketplace images
  .github/actions/constellation_create/action.yml
  .github/workflows/e2e-test-marketplace-image.yml
  cli/internal/cloudcmd/tfvars.go
  docs/docs/getting-started/marketplaces.md
  docs/docs/overview/license.md
  internal/config/config.go
  internal/config/config_doc.go
  internal/imagefetcher/imagefetcher.go
  terraform-provider-constellation/docs/data-sources/image.md
  terraform-provider-constellation/internal/provider/image_data_source.go
  terraform-provider-constellation/internal/provider/image_data_source_test.go
  terraform/infrastructure/aws/variables.tf
Labels: feature

#2892 terraform: remove cloud loggers
  bazel/toolchains/go_module_deps.bzl
  bootstrapper/cmd/bootstrapper/BUILD.bazel
  bootstrapper/cmd/bootstrapper/main.go
  bootstrapper/cmd/bootstrapper/run.go
  docs/docs/workflows/troubleshooting.md
  go.mod
  go.sum
  hack/qemu-metadata-api/server/server.go
  hack/qemu-metadata-api/server/server_test.go
  internal/cloud/aws/BUILD.bazel
  internal/cloud/aws/aws.go
  internal/cloud/aws/logger.go
  internal/cloud/aws/logger_test.go
  internal/cloud/azure/BUILD.bazel
  internal/cloud/azure/interface.go
  internal/cloud/azure/logger.go
  internal/cloud/azure/logger_test.go
  internal/cloud/gcp/BUILD.bazel
  internal/cloud/gcp/logger.go
  internal/cloud/qemu/BUILD.bazel
  internal/cloud/qemu/logger.go
  terraform/infrastructure/aws/main.tf
  terraform/infrastructure/azure/main.tf
  terraform/infrastructure/gcp/main.tf
  terraform/infrastructure/qemu/main.tf
Labels: breaking change

#2895 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2898 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2902 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2903 ci: prevent duplicate artifact naming in same workflow
  .github/workflows/e2e-test-provider-example.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#2904 helm: move yawol into a separate release
  internal/constellation/helm/BUILD.bazel
  internal/constellation/helm/charts/edgeless/constellation-services/Chart.yaml
  internal/constellation/helm/charts/edgeless/constellation-services/values.yaml
  internal/constellation/helm/charts/yawol/.helmignore
  internal/constellation/helm/charts/yawol/Chart.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-config/.helmignore
  internal/constellation/helm/charts/yawol/charts/yawol-config/Chart.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-config/templates/secret.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-config/values.schema.json
  internal/constellation/helm/charts/yawol/charts/yawol-config/values.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/Chart.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/README.md
  internal/constellation/helm/charts/yawol/charts/yawol-controller/crds/yawol.stackit.cloud_loadbalancermachines.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/crds/yawol.stackit.cloud_loadbalancers.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/crds/yawol.stackit.cloud_loadbalancersets.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/templates/_helpers.tpl
  internal/constellation/helm/charts/yawol/charts/yawol-controller/templates/rbac-yawol-cloud-controller.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/templates/rbac-yawol-controller.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/templates/sa-yawol-cloud-controller.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/templates/sa-yawol-controller.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/templates/vpa.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/templates/yawol-cloud-controller.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/templates/yawol-controller.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/templates/yawol-gardener-monitoring.yaml
  internal/constellation/helm/charts/yawol/charts/yawol-controller/values.yaml
  internal/constellation/helm/charts/yawol/templates/.gitkeep
  internal/constellation/helm/charts/yawol/values.yaml
  internal/constellation/helm/loader.go
  internal/constellation/helm/overrides.go
Labels: no changelog

#2908 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2905 helm: fix log formatting
  internal/constellation/helm/action.go
Labels: no changelog

#2909 vpn: ship our own container image
  WORKSPACE.bazel
  bazel/oci/containers.bzl
  dev-docs/howto/vpn/helm/files/strongswan/charon-logging.conf
  dev-docs/howto/vpn/helm/templates/operator-deployment.yaml
  dev-docs/howto/vpn/helm/templates/strongswan-statefulset.yaml
  dev-docs/howto/vpn/helm/values.yaml
  flake.nix
  nix/container/vpn/BUILD.bazel
  nix/container/vpn/operator.sh
  nix/container/vpn/sidecar.sh
  nix/container/vpn/strongswan.sh
  nix/container/vpn/vpn.nix
Labels: no changelog

#2912 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2917 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2913 ci: fix artifact overwriting in upgrade test
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#2920 deps: update go-git
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
Labels: no changelog

#2923 debugd: enable debug logging for systemd units
  debugd/internal/debugd/deploy/service.go
  debugd/internal/debugd/deploy/service_test.go
Labels: no changelog

#2928 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2926 ci: fetch latest console logs on aws
  .github/actions/constellation_create/aws-logs.sh
Labels: no changelog

#2934 ci: fix duplicate benchmark artificat name
  .github/actions/e2e_benchmark/action.yml
Labels: no changelog

#2906 cli: collect debug logs in file
  bazel/toolchains/go_module_deps.bzl
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/apply.go
  go.mod
  go.sum
  internal/constants/constants.go
Labels: no changelog

#2935 deps: update all 3rdparty github actions
  .github/actions/artifact_download/action.yml
  .github/actions/build_cli/action.yml
  .github/actions/build_micro_service/action.yml
  .github/actions/cdbg_deploy/action.yml
  .github/actions/constellation_destroy/action.yml
  .github/actions/constellation_iam_destroy/action.yml
  .github/actions/container_sbom/action.yml
  .github/actions/deploy_logcollection/action.yml
  .github/actions/download_release_binaries/action.yml
  .github/actions/e2e_attestationconfigapi/action.yml
  .github/actions/e2e_benchmark/action.yml
  .github/actions/e2e_mini/action.yml
  .github/actions/e2e_sonobuoy/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/e2e_verify/action.yml
  .github/actions/find_latest_image/action.yml
  .github/actions/login_azure/action.yml
  .github/actions/login_gcp/action.yml
  .github/actions/notify_e2e_failure/action.yml
  .github/actions/publish_helmchart/action.yml
  .github/actions/select_image/action.yml
  .github/actions/setup_bazel_nix/action.yml
  .github/workflows/aws-snp-launchmeasurement.yml
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-gcp-guest-agent.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/build-os-image.yml
  .github/workflows/check-links.yml
  .github/workflows/codeql.yml
  .github/workflows/draft-release.yml
  .github/workflows/e2e-mini.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/e2e-windows.yml
  .github/workflows/on-release.yml
  .github/workflows/purge-main.yml
  .github/workflows/release.yml
  .github/workflows/reproducible-builds.yml
  .github/workflows/scorecard.yml
  .github/workflows/sync-terraform-docs.yml
  .github/workflows/test-tidy.yml
  .github/workflows/test-unittest.yml
  .github/workflows/update-rpms.yml
  .github/workflows/versionsapi.yml
Labels: dependencies

#2925 STACKIT Kubernetes API load balancing
  cli/internal/cloudcmd/tfvars.go
  cli/internal/terraform/variables.go
  cli/internal/terraform/variables_test.go
  internal/cloud/openstack/api.go
  internal/cloud/openstack/api_test.go
  internal/cloud/openstack/imds.go
  internal/cloud/openstack/openstack.go
  internal/cloud/openstack/openstack_test.go
  internal/config/config.go
  internal/config/config_doc.go
  internal/constellation/helm/overrides.go
  terraform/BUILD.bazel
  terraform/infrastructure/openstack/.terraform.lock.hcl
  terraform/infrastructure/openstack/main.tf
  terraform/infrastructure/openstack/modules/instance_group/main.tf
  terraform/infrastructure/openstack/modules/instance_group/outputs.tf
  terraform/infrastructure/openstack/modules/instance_group/variables.tf
  terraform/infrastructure/openstack/modules/stackit_loadbalancer/main.tf
  terraform/infrastructure/openstack/modules/stackit_loadbalancer/variables.tf
  terraform/infrastructure/openstack/variables.tf
Labels: feature

#2943 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2924 docs: add STACKIT
  docs/docs/getting-started/first-steps.md
  docs/docs/getting-started/install.md
  docs/docs/getting-started/marketplaces.md
  docs/docs/overview/license.md
  docs/docs/overview/product.md
  docs/docs/workflows/config.md
  docs/docs/workflows/storage.md
Labels: no changelog

#2946 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#2933 deps: update all terraform providers
  dev-docs/howto/vpn/on-prem-terraform/.terraform.lock.hcl
  dev-docs/howto/vpn/on-prem-terraform/main.tf
  dev-docs/miniconstellation/azure-terraform/.terraform.lock.hcl
  dev-docs/miniconstellation/azure-terraform/main.tf
  e2e/miniconstellation/.terraform.lock.hcl
  e2e/miniconstellation/main.tf
  terraform/infrastructure/aws/.terraform.lock.hcl
  terraform/infrastructure/aws/main.tf
  terraform/infrastructure/aws/modules/instance_group/main.tf
  terraform/infrastructure/aws/modules/jump_host/main.tf
  terraform/infrastructure/aws/modules/load_balancer_target/main.tf
  terraform/infrastructure/aws/modules/public_private_subnet/main.tf
  terraform/infrastructure/azure/.terraform.lock.hcl
  terraform/infrastructure/azure/main.tf
  terraform/infrastructure/azure/modules/load_balancer_backend/main.tf
  terraform/infrastructure/azure/modules/scale_set/main.tf
  terraform/infrastructure/gcp/.terraform.lock.hcl
  terraform/infrastructure/gcp/main.tf
  terraform/infrastructure/gcp/modules/instance_group/main.tf
  terraform/infrastructure/gcp/modules/internal_load_balancer/main.tf
  terraform/infrastructure/gcp/modules/jump_host/main.tf
  terraform/infrastructure/gcp/modules/loadbalancer/main.tf
  terraform/infrastructure/iam/aws/.terraform.lock.hcl
  terraform/infrastructure/iam/aws/main.tf
  terraform/infrastructure/iam/azure/.terraform.lock.hcl
  terraform/infrastructure/iam/azure/main.tf
  terraform/infrastructure/iam/gcp/.terraform.lock.hcl
  terraform/infrastructure/iam/gcp/main.tf
  terraform/infrastructure/qemu/.terraform.lock.hcl
Labels: dependencies

#2947 deps: update Linux LTS and stable kernel
  bazel/toolchains/linux_kernel.bzl
Labels: dependencies

#2948 ci: fix artifact naming problems in e2e test
  .github/actions/e2e_benchmark/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#2950 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#2957 ci: match version of actions/download-artifact for slsa provenance
  .github/workflows/draft-release.yml
Labels: no changelog

#2953 release: use cosign sign-blob in non-interative mode
  .github/actions/build_cli/action.yml
  .github/workflows/draft-release.yml
  rfc/003-secure-software-distribution.md
Labels: no changelog
