Repository edgelesssys/constellation, pull requests merged in 2024-05, with the labels that each got.

#3057 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3055 ci: reduce noise from warnings
  .github/actions/e2e_cleanup_timeframe/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/login_azure/action.yml
  .github/actions/notify_e2e_failure/action.yml
  .github/actions/update_tfstate/action.yml
  .github/workflows/e2e-test-provider-example.yml
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#3058 ci: enable gcp-sev-snp for daily tests
  .github/actions/e2e_verify/action.yml
  .github/workflows/e2e-test-daily.yml
Labels: no changelog

#3060 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3061 measurements: fix tool not generating measurements for gcp-sev-snp
  internal/attestation/measurements/measurements_enterprise.go
Labels: no changelog

#3052 terraform: set empty default value for `additional_tags`
  .github/workflows/e2e-test.yml
  terraform/infrastructure/aws/variables.tf
  terraform/infrastructure/azure/variables.tf
  terraform/infrastructure/gcp/variables.tf
  terraform/infrastructure/openstack/variables.tf
Labels: no changelog

#3059 ci: correctly clean up failed windows e2e tests
  .github/workflows/e2e-windows.yml
Labels: no changelog

#3065 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3064 terraform: Allow nodes to join the cluster when using a jump host by removing the `constellation-uid` tag
  terraform/infrastructure/aws/main.tf
  terraform/infrastructure/aws/modules/jump_host/main.tf
  terraform/infrastructure/azure/main.tf
  terraform/infrastructure/gcp/main.tf
Labels: no changelog

#3069 deps: update to Go 1.22.3
  .github/actions/versionsapi/Dockerfile
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  WORKSPACE.bazel
  dev-docs/workflows/bump-go-version.md
  go.work
  renovate.json5
Labels: dependencies

#2937 ci: disable e2e-attestationconfigapi on PRs
  .github/workflows/e2e-attestationconfigapi.yml
Labels: no changelog

#3071 deps: update all Go dependencies
  bazel/toolchains/go_module_deps.bzl
  bootstrapper/initproto/init.pb.go
  cli/internal/libvirt/BUILD.bazel
  cli/internal/libvirt/libvirt.go
  debugd/service/debugd.pb.go
  disk-mapper/recoverproto/recover.pb.go
  go.mod
  go.sum
  internal/config/config.go
  internal/versions/components/components.pb.go
  joinservice/joinproto/join.pb.go
  keyservice/keyserviceproto/keyservice.pb.go
  renovate.json5
  upgrade-agent/upgradeproto/upgrade.pb.go
  verify/verifyproto/verify.pb.go
Labels: dependencies

#3062 helm: Restore the ability to start a cluster in conformance mode by disabling the cilium ipmasq agent when in conformance mode
  internal/constellation/helm/overrides.go
Labels: bug fix

#3063 terraform: add missing policies for AWS ALB
  .github/actions/e2e_lb/action.yml
  .github/actions/e2e_lb/aws-ingress.yml
  .github/actions/e2e_test/action.yml
  docs/docs/workflows/lb.md
  terraform/BUILD.bazel
  terraform/infrastructure/iam/aws/alb_policy.json
  terraform/infrastructure/iam/aws/main.tf
Labels: bug fix, needs backport

#3075 deps: update bazel buildtools
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
Labels: dependencies

#3077 ci: disable BuildBuddy
  .bazelrc
  .github/actions/e2e_attestationconfigapi/action.yml
  .github/actions/e2e_mini/action.yml
  .github/actions/e2e_s3proxy/action.yml
  .github/actions/e2e_test/action.yml
  .github/actions/setup_bazel_nix/action.yml
  .github/workflows/build-binaries.yml
  .github/workflows/build-libvirt-container.yml
  .github/workflows/e2e-attestationconfigapi.yml
  .github/workflows/e2e-mini.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-provider-example.yml
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-upgrade.yml
  .github/workflows/e2e-windows.yml
  .github/workflows/on-release.yml
  .github/workflows/reproducible-builds.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-tidy.yml
  .github/workflows/test-unittest.yml
  .github/workflows/update-rpms.yml
  dev-docs/workflows/bazel.md
Labels: no changelog

#3079 deps: update LTS and mainline kernels
  bazel/toolchains/linux_kernel.bzl
Labels: dependencies

#3080 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3074 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3088 cloud: hide kubernetes iptables usage behind linux build tag
  internal/cloud/azure/BUILD.bazel
  internal/cloud/azure/azure.go
  internal/cloud/azure/iptables_cross.go
  internal/cloud/azure/iptables_linux.go
Labels: no changelog

#3089 deps: bump stackit terraform provider to 0.17.0
  terraform/infrastructure/openstack/.terraform.lock.hcl
  terraform/infrastructure/openstack/main.tf
  terraform/infrastructure/openstack/modules/stackit_loadbalancer/main.tf
Labels: dependencies, needs backport

#3091 ci: only assign reviewer to bot PRs
  .github/workflows/assign_reviewer.yml
Labels: no changelog

#3081 deps: remove replacement of go-tpm with fork
  bazel/toolchains/go_module_deps.bzl
  go.mod
  go.sum
Labels: no changelog

#3092 ci: explicitly set bazel test timeout to four hours for e2e tests
  .github/actions/e2e_lb/action.yml
  .github/actions/e2e_malicious_join/action.yml
  .github/actions/e2e_mini/action.yml
  .github/workflows/e2e-test-provider-example.yml
  .github/workflows/e2e-upgrade.yml
Labels: no changelog

#3093 s3proxy: commit image version on release, too
  .github/workflows/release.yml
Labels: no changelog

#3085 terraform: only set `confidential_instance_type` if `cc_technology` is `SEV_SNP`
  terraform/infrastructure/gcp/modules/instance_group/main.tf
Labels: no changelog

#3100 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3101 renovate: group all Terraform dependency updates into one PR
  renovate.json5
Labels: no changelog

#3105 cli: simplify log message on init call
  internal/constellation/applyinit.go
Labels: no changelog

#3110 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3111 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3113 operators: ignore node deletion errors on absence
  operators/constellation-node-operator/internal/cloud/aws/client/nodeimage.go
  operators/constellation-node-operator/internal/cloud/aws/client/nodeimage_test.go
  operators/constellation-node-operator/internal/cloud/gcp/client/nodeimage.go
Labels: bug fix

#3118 ci: ignore missing files when creating archive
  .github/actions/artifact_download/action.yml
  .github/actions/artifact_upload/action.yml
Labels: no changelog

#3119 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3115 metadata-api: support dnsmasq
  hack/qemu-metadata-api/BUILD.bazel
  hack/qemu-metadata-api/dhcp/BUILD.bazel
  hack/qemu-metadata-api/dhcp/dhcp.go
  hack/qemu-metadata-api/dhcp/dnsmasq/BUILD.bazel
  hack/qemu-metadata-api/dhcp/dnsmasq/dnsmasq.go
  hack/qemu-metadata-api/dhcp/dnsmasq/dnsmasq_test.go
  hack/qemu-metadata-api/dhcp/virtwrapper/BUILD.bazel
  hack/qemu-metadata-api/dhcp/virtwrapper/virtwrapper.go
  hack/qemu-metadata-api/dhcp/virtwrapper/virtwrapper_cgo.go
  hack/qemu-metadata-api/dhcp/virtwrapper/virtwrapper_cross.go
  hack/qemu-metadata-api/main.go
  hack/qemu-metadata-api/server/BUILD.bazel
  hack/qemu-metadata-api/server/server.go
  hack/qemu-metadata-api/server/server_cgo_test.go
  hack/qemu-metadata-api/server/server_cross_test.go
  hack/qemu-metadata-api/server/server_test.go
  hack/qemu-metadata-api/virtwrapper/virtwrapper_cgo.go
  hack/qemu-metadata-api/virtwrapper/virtwrapper_cross.go
Labels: no changelog

#3124 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3128 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3109 ci: clean up failed miniconstellation e2e tests
  .github/actions/e2e_mini/action.yml
  .github/workflows/e2e-mini.yml
  .github/workflows/e2e-test-daily.yml
  .github/workflows/e2e-test-weekly.yml
  e2e/miniconstellation/main.sh.in
  e2e/miniconstellation/output.tf
Labels: no changelog
