Repository edgelesssys/constellation, pull requests merged in 2025-01, with the labels that each got.

#3567 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3566 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3569 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3571 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3572 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3576 fix(docs): reference up to date longhorn guide
  dev-docs/howto/longhorn.md
Labels: documentation, no changelog

#3577 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3587 ci: allow unrestricted user namespaces in image builds
  .github/workflows/build-os-image.yml
Labels: no changelog

#3599 dependencies: bump Go to v1.23.5
  .github/workflows/build-ccm-gcp.yml
  .github/workflows/build-os-image-scheduled.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test-operator-codegen.yml
  3rdparty/gcp-guest-agent/Dockerfile
  MODULE.bazel
  dev-docs/workflows/bump-go-version.md
  go.mod
  go.work
  hack/tools/go.mod
Labels: dependencies

#3610 renovate: reformat config file for json5
  renovate.json5
Labels: no changelog

#3613 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3620 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3568 cli: add `ssh` command to securely connect with nodes over ssh
  bootstrapper/internal/initserver/BUILD.bazel
  bootstrapper/internal/initserver/initserver.go
  bootstrapper/internal/joinclient/joinclient.go
  bootstrapper/internal/joinclient/joinclient_test.go
  cli/cmd/root.go
  cli/internal/cmd/BUILD.bazel
  cli/internal/cmd/ssh.go
  cli/internal/cmd/ssh_test.go
  docs/docs/reference/cli.md
  internal/constants/constants.go
  internal/crypto/BUILD.bazel
  internal/crypto/crypto.go
  internal/crypto/crypto_test.go
  joinservice/internal/server/BUILD.bazel
  joinservice/internal/server/server.go
  joinservice/internal/server/server_test.go
  joinservice/joinproto/join.pb.go
  joinservice/joinproto/join.proto
Labels: feature

#3628 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog
