Repository edgelesssys/constellation, pull requests merged in 2025-02, with the labels that each got.

#3630 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3632 helm: grant configmap watch permission to constellation-operator-cont…
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/AWS/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/OpenStack/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  operators/constellation-node-operator/controllers/nodeversion_controller.go
Labels: no changelog

#3636 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3641 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3645 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3644 attestation: fix Azure SNP attestation issuing caused by a bug in MAA PCR11 handling
  go.mod
  go.sum
Labels: bug fix

#3647 Post v2.20.1 release updates to main
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#3649 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3650 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3651 ci: supply STACKIT credentials to cleanup job
  .github/actions/e2e_cleanup_timeframe/action.yml
  .github/workflows/e2e-cleanup-weekly.yml
Labels: no changelog

#3653 operator: bump controller-gen version
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/crds/autoscalingstrategy-crd.yaml
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/crds/joiningnode-crd.yaml
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/crds/nodeversion-crd.yaml
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/crds/pendingnode-crd.yaml
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/crds/scalinggroup-crd.yaml
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/AWS/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/OpenStack/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  internal/constellation/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/manager-rbac.yaml
  operators/constellation-node-operator/Makefile
  operators/constellation-node-operator/api/v1alpha1/zz_generated.deepcopy.go
  operators/constellation-node-operator/config/crd/bases/update.edgeless.systems_autoscalingstrategies.yaml
  operators/constellation-node-operator/config/crd/bases/update.edgeless.systems_joiningnodes.yaml
  operators/constellation-node-operator/config/crd/bases/update.edgeless.systems_nodeversions.yaml
  operators/constellation-node-operator/config/crd/bases/update.edgeless.systems_pendingnodes.yaml
  operators/constellation-node-operator/config/crd/bases/update.edgeless.systems_scalinggroups.yaml
  operators/constellation-node-operator/config/rbac/role.yaml
Labels: no changelog

#3655 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3658 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3662 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3661 dev-docs: fix attestationconfigapi instructions
  dev-docs/workflows/attestationconfigapi.md
Labels: no changelog

#3664 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3667 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog
