Repository edgelesssys/constellation, pull requests merged in 2025-03, with the labels that each got.

#3672 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3674 ci: replace tenv linter with usetesting
  .golangci.yml
Labels: no changelog

#3654 e2e: check measurements reproducibility test for images
  .github/actions/check_measurements_reproducibility/action.yml
  .github/actions/check_measurements_reproducibility/compare_measurements.sh
  .github/actions/check_measurements_reproducibility/create_measurements.sh
  .github/workflows/check-measurements-reproducibility.yml
  .github/workflows/release.yml
Labels: no changelog

#3681 terraform: update AWS LB permissions
  3rdparty/bazel/com_github_kubernetes_sigs_aws_load_balancer_controller/BUILD.bazel
  3rdparty/bazel/com_github_kubernetes_sigs_aws_load_balancer_controller/pull_files.sh
  3rdparty/bazel/com_github_kubernetes_sigs_aws_load_balancer_controller/source.bzl
  WORKSPACE.bzlmod
  bazel/ci/BUILD.bazel
  docs/docs/reference/migration.md
  terraform/infrastructure/iam/aws/alb_policy.json
Labels: bug fix

#3687 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3691 terraform: remove legacy infrastructure modules
  bazel/ci/terraform.sh.in
  terraform/legacy-module/README.md
  terraform/legacy-module/aws-constellation/main.tf
  terraform/legacy-module/aws-constellation/variables.tf
  terraform/legacy-module/azure-constellation/main.tf
  terraform/legacy-module/azure-constellation/variables.tf
  terraform/legacy-module/common/fetch-image/main.tf
  terraform/legacy-module/common/fetch-image/output.tf
  terraform/legacy-module/common/fetch-image/variables.tf
  terraform/legacy-module/common/install-yq.sh
  terraform/legacy-module/constellation-cluster/install-constellation.sh
  terraform/legacy-module/constellation-cluster/main.tf
  terraform/legacy-module/constellation-cluster/variables.tf
  terraform/legacy-module/gcp-constellation/main.tf
  terraform/legacy-module/gcp-constellation/variables.tf
Labels: breaking change

#3693 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3695 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3699 ci: add k8s v1.31 and remove v1.28 from stackit e2e test
  .github/workflows/e2e-test-stackit.yml
Labels: no changelog

#3700 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3698 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3707 deps: bump github.com/containerd/containerd to v1.7.27
  go.mod
  go.sum
Labels: dependencies

#3557 feat: implement RFC 16 to allow emergency node access
  .github/actions/e2e_emergency_ssh/action.yml
  .github/actions/e2e_test/action.yml
  .github/workflows/e2e-test-weekly.yml
  .github/workflows/e2e-test.yml
  cli/internal/cmd/ssh.go
  cli/internal/cmd/ssh_test.go
  docs/docs/reference/cli.md
  docs/docs/workflows/troubleshooting.md
  image/base/mkosi.conf
  image/base/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset
  image/base/mkosi.skeleton/usr/lib/systemd/system/create-host-ssh-key.service
  image/mirror/SHA256SUMS
  image/mirror/packages.txt
  image/sysroot-tree/etc/ssh/sshd_config
  rfc/016-node-access.md
  terraform/infrastructure/aws/main.tf
  terraform/infrastructure/aws/outputs.tf
  terraform/infrastructure/aws/variables.tf
  terraform/infrastructure/azure/main.tf
  terraform/infrastructure/azure/outputs.tf
  terraform/infrastructure/azure/variables.tf
  terraform/infrastructure/gcp/main.tf
  terraform/infrastructure/gcp/outputs.tf
  terraform/infrastructure/gcp/variables.tf
  terraform/infrastructure/openstack/main.tf
  terraform/infrastructure/openstack/outputs.tf
  terraform/infrastructure/openstack/variables.tf
Labels: feature

#3656 gcp: support projects with no default permissions
  .github/actions/constellation_iam_create/action.yml
  .github/actions/e2e_test/action.yml
  cli/internal/cloudcmd/iam.go
  cli/internal/cloudcmd/iamupgrade.go
  cli/internal/cloudcmd/tfvars.go
  cli/internal/cmd/apply_test.go
  cli/internal/cmd/iamcreate.go
  cli/internal/cmd/iamcreate_test.go
  cli/internal/cmd/iamcreategcp.go
  cli/internal/cmd/init_test.go
  cli/internal/terraform/terraform.go
  cli/internal/terraform/terraform_test.go
  cli/internal/terraform/variables.go
  cli/internal/terraform/variables_test.go
  docs/docs/getting-started/first-steps.md
  docs/docs/getting-started/install.md
  docs/docs/reference/cli.md
  docs/docs/workflows/config.md
  internal/config/config.go
  internal/config/config_doc.go
  internal/config/config_test.go
  internal/constellation/helm/charts/edgeless/constellation-services/charts/join-service/templates/daemonset.yaml
  internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/AWS/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/AWS/constellation-services/charts/join-service/templates/daemonset.yaml
  internal/constellation/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/Azure/constellation-services/charts/join-service/templates/daemonset.yaml
  internal/constellation/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/GCP/constellation-services/charts/join-service/templates/daemonset.yaml
  internal/constellation/helm/testdata/OpenStack/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/OpenStack/constellation-services/charts/join-service/templates/daemonset.yaml
  internal/constellation/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/deployment.yaml
  internal/constellation/helm/testdata/QEMU/constellation-services/charts/join-service/templates/daemonset.yaml
  operators/constellation-node-operator/config/manager/manager.yaml
  terraform-provider-constellation/examples/full/gcp/main.tf
  terraform/infrastructure/gcp/main.tf
  terraform/infrastructure/gcp/modules/instance_group/main.tf
  terraform/infrastructure/gcp/modules/instance_group/variables.tf
  terraform/infrastructure/gcp/variables.tf
  terraform/infrastructure/iam/gcp/main.tf
  terraform/infrastructure/iam/gcp/outputs.tf
  terraform/infrastructure/iam/gcp/variables.tf
Labels: feature, breaking change, iam upgrade

#3713 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3718 ci: bump slsa verifier
  .github/workflows/draft-release.yml
Labels: no changelog

#3721 ci: exclude go vulns that don't affect library usage
  bazel/ci/govulncheck.sh.in
Labels: no changelog

#3727 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies
