Repository edgelesssys/constellation, pull requests merged in 2025-08, with the labels that each got.

#3901 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3894 helm: bump Cilium version to v1.15.19-edg.0
  internal/constellation/helm/BUILD.bazel
  internal/constellation/helm/charts/cilium/Chart.yaml
  internal/constellation/helm/charts/cilium/README.md
  internal/constellation/helm/charts/cilium/files/cilium-envoy/configmap/bootstrap-config.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-envoy/configmap.yaml
  internal/constellation/helm/charts/cilium/templates/cilium-envoy/daemonset.yaml
  internal/constellation/helm/charts/cilium/templates/hubble-ui/_nginx.tpl
  internal/constellation/helm/charts/cilium/templates/hubble/tls-certmanager/relay-client-secret.yaml
  internal/constellation/helm/charts/cilium/templates/hubble/tls-certmanager/relay-server-secret.yaml
  internal/constellation/helm/charts/cilium/templates/hubble/tls-certmanager/server-secret.yaml
  internal/constellation/helm/charts/cilium/templates/hubble/tls-certmanager/ui-client-certs.yaml
  internal/constellation/helm/charts/cilium/values.yaml
  internal/constellation/helm/charts/cilium/values.yaml.tmpl
  internal/constellation/helm/generateCilium.sh
  internal/constellation/helm/helm_test.go
  internal/constellation/helm/loader.go
Labels: security fix

#3908 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3933 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3934 deps: switch to edgeless go-sev-guest fork
  go.mod
  go.sum
  renovate.json5
Labels: dependencies
