Repository edgelesssys/constellation, pull requests merged in 2025-05, with the labels that each got.

#3794 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3793 terraform-provider: pass ServiceCIDR from resource to chart loader
  terraform-provider-constellation/internal/provider/cluster_resource.go
Labels: bug fix

#3796 CODEOWNERS: update
  CODEOWNERS
Labels: no changelog

#3806 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3778 docs: GCP iam migration
  cli/internal/cloudcmd/iamupgrade.go
  docs/docs/getting-started/install.md
  docs/docs/reference/migration.md
  docs/versioned_docs/version-2.23/getting-started/install.md
  docs/versioned_docs/version-2.23/reference/migration.md
Labels: no changelog

#3821 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3819 ci: run e2e cleanup daily
  .github/actions/e2e_cleanup_timeframe/e2e-cleanup.sh
  .github/workflows/e2e-cleanup.yml
Labels: no changelog

#3822 helm: force app creds in GCP CCM
  internal/constellation/helm/charts/edgeless/constellation-services/charts/ccm/templates/gcp-cm.yaml
  internal/constellation/helm/testdata/GCP/constellation-services/charts/ccm/templates/gcp-cm.yaml
Labels: no changelog

#3824 image: update locked rpms
  image/mirror/SHA256SUMS
Labels: dependencies

#3827 ci: dont fail if Azure resources were already deleted
  .github/actions/e2e_cleanup_timeframe/e2e-cleanup.sh
Labels: no changelog

#3795 Post v2.23.1 release updates to main
  .github/workflows/e2e-test-release.yml
  .github/workflows/e2e-test-weekly.yml
Labels: no changelog

#3830 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3834 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3838 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog

#3841 image: update measurements and image version
  internal/attestation/measurements/measurements_enterprise.go
  internal/config/image_enterprise.go
Labels: no changelog
